// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: anticheat/v1/anticheat.proto

package anticheatv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	v1 "github.com/leighmacdonald/gbans/internal/database/query/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Detection int32

const (
	Detection_DETECTION_UNSPECIFIED          Detection = 0
	Detection_DETECTION_SILENT_AIM           Detection = 1
	Detection_DETECTION_AIM_SNAP             Detection = 2
	Detection_DETECTION_TOO_MANY_CONNECTIONS Detection = 3
	Detection_DETECTION_INTERP               Detection = 4
	Detection_DETECTION_BHOP                 Detection = 5
	Detection_DETECTION_CMD_NUM_SPIKE        Detection = 6
	Detection_DETECTION_EYE_ANGLES           Detection = 7
	Detection_DETECTION_INVALID_USER_CMD     Detection = 8
	Detection_DETECTION_OOB_CVAR             Detection = 9
	Detection_DETECTION_CHEAT_CVAR           Detection = 10
)

// Enum value maps for Detection.
var (
	Detection_name = map[int32]string{
		0:  "DETECTION_UNSPECIFIED",
		1:  "DETECTION_SILENT_AIM",
		2:  "DETECTION_AIM_SNAP",
		3:  "DETECTION_TOO_MANY_CONNECTIONS",
		4:  "DETECTION_INTERP",
		5:  "DETECTION_BHOP",
		6:  "DETECTION_CMD_NUM_SPIKE",
		7:  "DETECTION_EYE_ANGLES",
		8:  "DETECTION_INVALID_USER_CMD",
		9:  "DETECTION_OOB_CVAR",
		10: "DETECTION_CHEAT_CVAR",
	}
	Detection_value = map[string]int32{
		"DETECTION_UNSPECIFIED":          0,
		"DETECTION_SILENT_AIM":           1,
		"DETECTION_AIM_SNAP":             2,
		"DETECTION_TOO_MANY_CONNECTIONS": 3,
		"DETECTION_INTERP":               4,
		"DETECTION_BHOP":                 5,
		"DETECTION_CMD_NUM_SPIKE":        6,
		"DETECTION_EYE_ANGLES":           7,
		"DETECTION_INVALID_USER_CMD":     8,
		"DETECTION_OOB_CVAR":             9,
		"DETECTION_CHEAT_CVAR":           10,
	}
)

func (x Detection) Enum() *Detection {
	p := new(Detection)
	*p = x
	return p
}

func (x Detection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Detection) Descriptor() protoreflect.EnumDescriptor {
	return file_anticheat_v1_anticheat_proto_enumTypes[0].Descriptor()
}

func (Detection) Type() protoreflect.EnumType {
	return &file_anticheat_v1_anticheat_proto_enumTypes[0]
}

func (x Detection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Detection.Descriptor instead.
func (Detection) EnumDescriptor() ([]byte, []int) {
	return file_anticheat_v1_anticheat_proto_rawDescGZIP(), []int{0}
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *v1.Filter             `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	SteamId       *int64                 `protobuf:"varint,3,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	Summary       *string                `protobuf:"bytes,4,opt,name=summary" json:"summary,omitempty"`
	Detection     *Detection             `protobuf:"varint,5,opt,name=detection,enum=anticheat.v1.Detection" json:"detection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_anticheat_v1_anticheat_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetFilter() *v1.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *QueryRequest) GetSteamId() int64 {
	if x != nil && x.SteamId != nil {
		return *x.SteamId
	}
	return 0
}

func (x *QueryRequest) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *QueryRequest) GetDetection() Detection {
	if x != nil && x.Detection != nil {
		return *x.Detection
	}
	return Detection_DETECTION_UNSPECIFIED
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*Entry               `protobuf:"bytes,1,rep,name=entries" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_anticheat_v1_anticheat_proto_rawDescGZIP(), []int{1}
}

func (x *QueryResponse) GetEntries() []*Entry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type Entry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnticheatId   *int64                 `protobuf:"varint,1,opt,name=anticheat_id,json=anticheatId" json:"anticheat_id,omitempty"`
	SteamId       *int64                 `protobuf:"varint,2,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	ServerId      *int32                 `protobuf:"varint,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ServerName    *string                `protobuf:"bytes,4,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	DemoId        *int32                 `protobuf:"varint,5,opt,name=demo_id,json=demoId" json:"demo_id,omitempty"`
	DemoName      *string                `protobuf:"bytes,6,opt,name=demo_name,json=demoName" json:"demo_name,omitempty"`
	DemoTick      *int32                 `protobuf:"varint,7,opt,name=demo_tick,json=demoTick" json:"demo_tick,omitempty"`
	Name          *string                `protobuf:"bytes,8,opt,name=name" json:"name,omitempty"`
	Detection     *Detection             `protobuf:"varint,9,opt,name=detection,enum=anticheat.v1.Detection" json:"detection,omitempty"`
	Summary       *string                `protobuf:"bytes,10,opt,name=summary" json:"summary,omitempty"`
	RawLog        *string                `protobuf:"bytes,11,opt,name=raw_log,json=rawLog" json:"raw_log,omitempty"`
	CreatedOn     *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	PersonaName   *string                `protobuf:"bytes,13,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	AvatarHash    *string                `protobuf:"bytes,14,opt,name=avatar_hash,json=avatarHash" json:"avatar_hash,omitempty"`
	Triggered     *int32                 `protobuf:"varint,15,opt,name=triggered" json:"triggered,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Entry) Reset() {
	*x = Entry{}
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entry) ProtoMessage() {}

func (x *Entry) ProtoReflect() protoreflect.Message {
	mi := &file_anticheat_v1_anticheat_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entry.ProtoReflect.Descriptor instead.
func (*Entry) Descriptor() ([]byte, []int) {
	return file_anticheat_v1_anticheat_proto_rawDescGZIP(), []int{2}
}

func (x *Entry) GetAnticheatId() int64 {
	if x != nil && x.AnticheatId != nil {
		return *x.AnticheatId
	}
	return 0
}

func (x *Entry) GetSteamId() int64 {
	if x != nil && x.SteamId != nil {
		return *x.SteamId
	}
	return 0
}

func (x *Entry) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *Entry) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

func (x *Entry) GetDemoId() int32 {
	if x != nil && x.DemoId != nil {
		return *x.DemoId
	}
	return 0
}

func (x *Entry) GetDemoName() string {
	if x != nil && x.DemoName != nil {
		return *x.DemoName
	}
	return ""
}

func (x *Entry) GetDemoTick() int32 {
	if x != nil && x.DemoTick != nil {
		return *x.DemoTick
	}
	return 0
}

func (x *Entry) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Entry) GetDetection() Detection {
	if x != nil && x.Detection != nil {
		return *x.Detection
	}
	return Detection_DETECTION_UNSPECIFIED
}

func (x *Entry) GetSummary() string {
	if x != nil && x.Summary != nil {
		return *x.Summary
	}
	return ""
}

func (x *Entry) GetRawLog() string {
	if x != nil && x.RawLog != nil {
		return *x.RawLog
	}
	return ""
}

func (x *Entry) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Entry) GetPersonaName() string {
	if x != nil && x.PersonaName != nil {
		return *x.PersonaName
	}
	return ""
}

func (x *Entry) GetAvatarHash() string {
	if x != nil && x.AvatarHash != nil {
		return *x.AvatarHash
	}
	return ""
}

func (x *Entry) GetTriggered() int32 {
	if x != nil && x.Triggered != nil {
		return *x.Triggered
	}
	return 0
}

var File_anticheat_v1_anticheat_proto protoreflect.FileDescriptor

const file_anticheat_v1_anticheat_proto_rawDesc = "" +
	"\n" +
	"\x1canticheat/v1/anticheat.proto\x12\fanticheat.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1edatabase/query/v1/filter.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xd4\x01\n" +
	"\fQueryRequest\x121\n" +
	"\x06filter\x18\x01 \x01(\v2\x19.database.query.v1.FilterR\x06filter\x12\x1b\n" +
	"\x04name\x18\x02 \x01(\tB\a\xbaH\x04r\x02\x18 R\x04name\x12\x19\n" +
	"\bsteam_id\x18\x03 \x01(\x03R\asteamId\x12\x18\n" +
	"\asummary\x18\x04 \x01(\tR\asummary\x12?\n" +
	"\tdetection\x18\x05 \x01(\x0e2\x17.anticheat.v1.DetectionB\b\xbaH\x05\x82\x01\x02\x10\x01R\tdetection\"F\n" +
	"\rQueryResponse\x125\n" +
	"\aentries\x18\x01 \x03(\v2\x13.anticheat.v1.EntryB\x06\xbaH\x03\xc8\x01\x01R\aentries\"\xfb\x04\n" +
	"\x05Entry\x12)\n" +
	"\fanticheat_id\x18\x01 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\vanticheatId\x12%\n" +
	"\bsteam_id\x18\x02 \x01(\x03B\n" +
	"\xbaH\a\xc8\x01\x01\"\x02 \x00R\asteamId\x12'\n" +
	"\tserver_id\x18\x03 \x01(\x05B\n" +
	"\xbaH\a\xc8\x01\x01\x1a\x02 \x00R\bserverId\x12'\n" +
	"\vserver_name\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\n" +
	"serverName\x12\x17\n" +
	"\ademo_id\x18\x05 \x01(\x05R\x06demoId\x12\x1b\n" +
	"\tdemo_name\x18\x06 \x01(\tR\bdemoName\x12\x1b\n" +
	"\tdemo_tick\x18\a \x01(\x05R\bdemoTick\x12\x1a\n" +
	"\x04name\x18\b \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12B\n" +
	"\tdetection\x18\t \x01(\x0e2\x17.anticheat.v1.DetectionB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\tdetection\x12 \n" +
	"\asummary\x18\n" +
	" \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\asummary\x12#\n" +
	"\araw_log\x18\v \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x10\x01R\x06rawLog\x12T\n" +
	"\n" +
	"created_on\x18\f \x01(\v2\x1a.google.protobuf.TimestampB\x19\xbaH\x16\xc8\x01\x01\xb2\x01\x10\x1a\x06\b\x80\xff\xf8\xa4\a*\x06\b\x80\x9e\xe1\xac\x04R\tcreatedOn\x12-\n" +
	"\fpersona_name\x18\r \x01(\tB\n" +
	"\xbaH\a\xc8\x01\x01r\x02\x18 R\vpersonaName\x12)\n" +
	"\vavatar_hash\x18\x0e \x01(\tB\b\xbaH\x05r\x03\x98\x01(R\n" +
	"avatarHash\x12$\n" +
	"\ttriggered\x18\x0f \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\ttriggered*\xaf\x02\n" +
	"\tDetection\x12\x19\n" +
	"\x15DETECTION_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14DETECTION_SILENT_AIM\x10\x01\x12\x16\n" +
	"\x12DETECTION_AIM_SNAP\x10\x02\x12\"\n" +
	"\x1eDETECTION_TOO_MANY_CONNECTIONS\x10\x03\x12\x14\n" +
	"\x10DETECTION_INTERP\x10\x04\x12\x12\n" +
	"\x0eDETECTION_BHOP\x10\x05\x12\x1b\n" +
	"\x17DETECTION_CMD_NUM_SPIKE\x10\x06\x12\x18\n" +
	"\x14DETECTION_EYE_ANGLES\x10\a\x12\x1e\n" +
	"\x1aDETECTION_INVALID_USER_CMD\x10\b\x12\x16\n" +
	"\x12DETECTION_OOB_CVAR\x10\t\x12\x18\n" +
	"\x14DETECTION_CHEAT_CVAR\x10\n" +
	"2V\n" +
	"\x10AnticheatService\x12B\n" +
	"\x05Query\x12\x1a.anticheat.v1.QueryRequest\x1a\x1b.anticheat.v1.QueryResponse\"\x00B\xb6\x01\n" +
	"\x10com.anticheat.v1B\x0eAnticheatProtoP\x01ZAgithub.com/leighmacdonald/gbans/internal/anticheat/v1;anticheatv1\xa2\x02\x03AXX\xaa\x02\fAnticheat.V1\xca\x02\fAnticheat\\V1\xe2\x02\x18Anticheat\\V1\\GPBMetadata\xea\x02\rAnticheat::V1b\beditionsp\xe8\a"

var (
	file_anticheat_v1_anticheat_proto_rawDescOnce sync.Once
	file_anticheat_v1_anticheat_proto_rawDescData []byte
)

func file_anticheat_v1_anticheat_proto_rawDescGZIP() []byte {
	file_anticheat_v1_anticheat_proto_rawDescOnce.Do(func() {
		file_anticheat_v1_anticheat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_anticheat_v1_anticheat_proto_rawDesc), len(file_anticheat_v1_anticheat_proto_rawDesc)))
	})
	return file_anticheat_v1_anticheat_proto_rawDescData
}

var file_anticheat_v1_anticheat_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_anticheat_v1_anticheat_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_anticheat_v1_anticheat_proto_goTypes = []any{
	(Detection)(0),                // 0: anticheat.v1.Detection
	(*QueryRequest)(nil),          // 1: anticheat.v1.QueryRequest
	(*QueryResponse)(nil),         // 2: anticheat.v1.QueryResponse
	(*Entry)(nil),                 // 3: anticheat.v1.Entry
	(*v1.Filter)(nil),             // 4: database.query.v1.Filter
	(*timestamppb.Timestamp)(nil), // 5: google.protobuf.Timestamp
}
var file_anticheat_v1_anticheat_proto_depIdxs = []int32{
	4, // 0: anticheat.v1.QueryRequest.filter:type_name -> database.query.v1.Filter
	0, // 1: anticheat.v1.QueryRequest.detection:type_name -> anticheat.v1.Detection
	3, // 2: anticheat.v1.QueryResponse.entries:type_name -> anticheat.v1.Entry
	0, // 3: anticheat.v1.Entry.detection:type_name -> anticheat.v1.Detection
	5, // 4: anticheat.v1.Entry.created_on:type_name -> google.protobuf.Timestamp
	1, // 5: anticheat.v1.AnticheatService.Query:input_type -> anticheat.v1.QueryRequest
	2, // 6: anticheat.v1.AnticheatService.Query:output_type -> anticheat.v1.QueryResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_anticheat_v1_anticheat_proto_init() }
func file_anticheat_v1_anticheat_proto_init() {
	if File_anticheat_v1_anticheat_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_anticheat_v1_anticheat_proto_rawDesc), len(file_anticheat_v1_anticheat_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_anticheat_v1_anticheat_proto_goTypes,
		DependencyIndexes: file_anticheat_v1_anticheat_proto_depIdxs,
		EnumInfos:         file_anticheat_v1_anticheat_proto_enumTypes,
		MessageInfos:      file_anticheat_v1_anticheat_proto_msgTypes,
	}.Build()
	File_anticheat_v1_anticheat_proto = out.File
	file_anticheat_v1_anticheat_proto_goTypes = nil
	file_anticheat_v1_anticheat_proto_depIdxs = nil
}
