// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,valid_types=legacy_required+protovalidate_required"
// @generated from file asset/v1/asset.proto (package asset.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file asset/v1/asset.proto.
 */
export const file_asset_v1_asset: GenFile =
	/*@__PURE__*/
	fileDesc(
		"ChRhc3NldC92MS9hc3NldC5wcm90bxIIYXNzZXQudjEiLgoNRGVsZXRlUmVxdWVzdBIdCghhc3NldF9pZBgBIAEoCUILukgIyAEBcgOwAQEiJgoORGVsZXRlUmVzcG9uc2USFAoEc2l6ZRgBIAEoA0IGukgDyAEBIjcKDUNyZWF0ZVJlcXVlc3QSGAoIY29udGVudHMYASABKAxCBrpIA8gBARIMCgRuYW1lGAIgASgJIjgKDkNyZWF0ZVJlc3BvbnNlEiYKBWFzc2V0GAEgASgLMg8uYXNzZXQudjEuQXNzZXRCBrpIA8gBASLCAgoFQXNzZXQSHQoIYXNzZXRfaWQYASABKAlCC7pICMgBAXIDsAEBEhYKBmJ1Y2tldBgCIAEoCUIGukgDyAEBEhkKCWF1dGhvcl9pZBgDIAEoA0IGukgDyAEBEhQKBGhhc2gYBCABKAlCBrpIA8gBARIaCgppc19wcml2YXRlGAUgASgIQga6SAPIAQESGQoJbWltZV90eXBlGAYgASgJQga6SAPIAQESFAoEbmFtZRgHIAEoCUIGukgDyAEBEhQKBHNpemUYCCABKANCBrpIA8gBARI2CgpjcmVhdGVkX29uGAkgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcEIGukgDyAEBEjYKCnVwZGF0ZWRfb24YCiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQga6SAPIAQEyjAEKDEFzc2V0U2VydmljZRI9CgZDcmVhdGUSFy5hc3NldC52MS5DcmVhdGVSZXF1ZXN0GhguYXNzZXQudjEuQ3JlYXRlUmVzcG9uc2UiABI9CgZEZWxldGUSFy5hc3NldC52MS5EZWxldGVSZXF1ZXN0GhguYXNzZXQudjEuRGVsZXRlUmVzcG9uc2UiAEKWAQoMY29tLmFzc2V0LnYxQgpBc3NldFByb3RvUAFaOWdpdGh1Yi5jb20vbGVpZ2htYWNkb25hbGQvZ2JhbnMvaW50ZXJuYWwvYXNzZXQvdjE7YXNzZXR2MaICA0FYWKoCCEFzc2V0LlYxygIIQXNzZXRcVjHiAhRBc3NldFxWMVxHUEJNZXRhZGF0YeoCCUFzc2V0OjpWMWIIZWRpdGlvbnNw6Ac",
		[file_buf_validate_validate, file_google_protobuf_timestamp],
	);

/**
 * @generated from message asset.v1.DeleteRequest
 */
export type DeleteRequest = Message<"asset.v1.DeleteRequest"> & {
	/**
	 * @generated from field: string asset_id = 1;
	 */
	assetId: string;
};

/**
 * @generated from message asset.v1.DeleteRequest
 */
export type DeleteRequestValid = Message<"asset.v1.DeleteRequest"> & {
	/**
	 * @generated from field: string asset_id = 1;
	 */
	assetId: string;
};

/**
 * Describes the message asset.v1.DeleteRequest.
 * Use `create(DeleteRequestSchema)` to create a new message.
 */
export const DeleteRequestSchema: GenMessage<DeleteRequest, { validType: DeleteRequestValid }> =
	/*@__PURE__*/
	messageDesc(file_asset_v1_asset, 0);

/**
 * @generated from message asset.v1.DeleteResponse
 */
export type DeleteResponse = Message<"asset.v1.DeleteResponse"> & {
	/**
	 * @generated from field: int64 size = 1;
	 */
	size: bigint;
};

/**
 * @generated from message asset.v1.DeleteResponse
 */
export type DeleteResponseValid = Message<"asset.v1.DeleteResponse"> & {
	/**
	 * @generated from field: int64 size = 1;
	 */
	size: bigint;
};

/**
 * Describes the message asset.v1.DeleteResponse.
 * Use `create(DeleteResponseSchema)` to create a new message.
 */
export const DeleteResponseSchema: GenMessage<DeleteResponse, { validType: DeleteResponseValid }> =
	/*@__PURE__*/
	messageDesc(file_asset_v1_asset, 1);

/**
 * @generated from message asset.v1.CreateRequest
 */
export type CreateRequest = Message<"asset.v1.CreateRequest"> & {
	/**
	 * @generated from field: bytes contents = 1;
	 */
	contents: Uint8Array;

	/**
	 * @generated from field: string name = 2;
	 */
	name: string;
};

/**
 * @generated from message asset.v1.CreateRequest
 */
export type CreateRequestValid = Message<"asset.v1.CreateRequest"> & {
	/**
	 * @generated from field: bytes contents = 1;
	 */
	contents: Uint8Array;

	/**
	 * @generated from field: string name = 2;
	 */
	name: string;
};

/**
 * Describes the message asset.v1.CreateRequest.
 * Use `create(CreateRequestSchema)` to create a new message.
 */
export const CreateRequestSchema: GenMessage<CreateRequest, { validType: CreateRequestValid }> =
	/*@__PURE__*/
	messageDesc(file_asset_v1_asset, 2);

/**
 * @generated from message asset.v1.CreateResponse
 */
export type CreateResponse = Message<"asset.v1.CreateResponse"> & {
	/**
	 * @generated from field: asset.v1.Asset asset = 1;
	 */
	asset?: Asset;
};

/**
 * @generated from message asset.v1.CreateResponse
 */
export type CreateResponseValid = Message<"asset.v1.CreateResponse"> & {
	/**
	 * @generated from field: asset.v1.Asset asset = 1;
	 */
	asset: AssetValid;
};

/**
 * Describes the message asset.v1.CreateResponse.
 * Use `create(CreateResponseSchema)` to create a new message.
 */
export const CreateResponseSchema: GenMessage<CreateResponse, { validType: CreateResponseValid }> =
	/*@__PURE__*/
	messageDesc(file_asset_v1_asset, 3);

/**
 * @generated from message asset.v1.Asset
 */
export type Asset = Message<"asset.v1.Asset"> & {
	/**
	 * @generated from field: string asset_id = 1;
	 */
	assetId: string;

	/**
	 * @generated from field: string bucket = 2;
	 */
	bucket: string;

	/**
	 * @generated from field: int64 author_id = 3;
	 */
	authorId: bigint;

	/**
	 * @generated from field: string hash = 4;
	 */
	hash: string;

	/**
	 * @generated from field: bool is_private = 5;
	 */
	isPrivate: boolean;

	/**
	 * @generated from field: string mime_type = 6;
	 */
	mimeType: string;

	/**
	 * @generated from field: string name = 7;
	 */
	name: string;

	/**
	 * @generated from field: int64 size = 8;
	 */
	size: bigint;

	/**
	 * @generated from field: google.protobuf.Timestamp created_on = 9;
	 */
	createdOn?: Timestamp;

	/**
	 * @generated from field: google.protobuf.Timestamp updated_on = 10;
	 */
	updatedOn?: Timestamp;
};

/**
 * @generated from message asset.v1.Asset
 */
export type AssetValid = Message<"asset.v1.Asset"> & {
	/**
	 * @generated from field: string asset_id = 1;
	 */
	assetId: string;

	/**
	 * @generated from field: string bucket = 2;
	 */
	bucket: string;

	/**
	 * @generated from field: int64 author_id = 3;
	 */
	authorId: bigint;

	/**
	 * @generated from field: string hash = 4;
	 */
	hash: string;

	/**
	 * @generated from field: bool is_private = 5;
	 */
	isPrivate: boolean;

	/**
	 * @generated from field: string mime_type = 6;
	 */
	mimeType: string;

	/**
	 * @generated from field: string name = 7;
	 */
	name: string;

	/**
	 * @generated from field: int64 size = 8;
	 */
	size: bigint;

	/**
	 * @generated from field: google.protobuf.Timestamp created_on = 9;
	 */
	createdOn: Timestamp;

	/**
	 * @generated from field: google.protobuf.Timestamp updated_on = 10;
	 */
	updatedOn: Timestamp;
};

/**
 * Describes the message asset.v1.Asset.
 * Use `create(AssetSchema)` to create a new message.
 */
export const AssetSchema: GenMessage<Asset, { validType: AssetValid }> =
	/*@__PURE__*/
	messageDesc(file_asset_v1_asset, 4);

/**
 * @generated from service asset.v1.AssetService
 */
export const AssetService: GenService<{
	/**
	 * @generated from rpc asset.v1.AssetService.Create
	 */
	create: {
		methodKind: "unary";
		input: typeof CreateRequestSchema;
		output: typeof CreateResponseSchema;
	};
	/**
	 * @generated from rpc asset.v1.AssetService.Delete
	 */
	delete: {
		methodKind: "unary";
		input: typeof DeleteRequestSchema;
		output: typeof DeleteResponseSchema;
	};
}> = /*@__PURE__*/ serviceDesc(file_asset_v1_asset, 0);
