// Code generated by mockery v2.43.1. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/leighmacdonald/gbans/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// MockConfigRepository is an autogenerated mock type for the ConfigRepository type
type MockConfigRepository struct {
	mock.Mock
}

type MockConfigRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockConfigRepository) EXPECT() *MockConfigRepository_Expecter {
	return &MockConfigRepository_Expecter{mock: &_m.Mock}
}

// Init provides a mock function with given fields: ctx
func (_m *MockConfigRepository) Init(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Init")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigRepository_Init_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Init'
type MockConfigRepository_Init_Call struct {
	*mock.Call
}

// Init is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigRepository_Expecter) Init(ctx interface{}) *MockConfigRepository_Init_Call {
	return &MockConfigRepository_Init_Call{Call: _e.mock.On("Init", ctx)}
}

func (_c *MockConfigRepository_Init_Call) Run(run func(ctx context.Context)) *MockConfigRepository_Init_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigRepository_Init_Call) Return(_a0 error) *MockConfigRepository_Init_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigRepository_Init_Call) RunAndReturn(run func(context.Context) error) *MockConfigRepository_Init_Call {
	_c.Call.Return(run)
	return _c
}

// Read provides a mock function with given fields: ctx
func (_m *MockConfigRepository) Read(ctx context.Context) (domain.Config, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Read")
	}

	var r0 domain.Config
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (domain.Config, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) domain.Config); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Get(0).(domain.Config)
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockConfigRepository_Read_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Read'
type MockConfigRepository_Read_Call struct {
	*mock.Call
}

// Read is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockConfigRepository_Expecter) Read(ctx interface{}) *MockConfigRepository_Read_Call {
	return &MockConfigRepository_Read_Call{Call: _e.mock.On("Read", ctx)}
}

func (_c *MockConfigRepository_Read_Call) Run(run func(ctx context.Context)) *MockConfigRepository_Read_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockConfigRepository_Read_Call) Return(_a0 domain.Config, _a1 error) *MockConfigRepository_Read_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockConfigRepository_Read_Call) RunAndReturn(run func(context.Context) (domain.Config, error)) *MockConfigRepository_Read_Call {
	_c.Call.Return(run)
	return _c
}

// Write provides a mock function with given fields: ctx, config
func (_m *MockConfigRepository) Write(ctx context.Context, config domain.Config) error {
	ret := _m.Called(ctx, config)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, domain.Config) error); ok {
		r0 = rf(ctx, config)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockConfigRepository_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockConfigRepository_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - ctx context.Context
//   - config domain.Config
func (_e *MockConfigRepository_Expecter) Write(ctx interface{}, config interface{}) *MockConfigRepository_Write_Call {
	return &MockConfigRepository_Write_Call{Call: _e.mock.On("Write", ctx, config)}
}

func (_c *MockConfigRepository_Write_Call) Run(run func(ctx context.Context, config domain.Config)) *MockConfigRepository_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(domain.Config))
	})
	return _c
}

func (_c *MockConfigRepository_Write_Call) Return(_a0 error) *MockConfigRepository_Write_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockConfigRepository_Write_Call) RunAndReturn(run func(context.Context, domain.Config) error) *MockConfigRepository_Write_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockConfigRepository creates a new instance of MockConfigRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockConfigRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockConfigRepository {
	mock := &MockConfigRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
