// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ban/v1/ban.proto

package banv1

import (
	_ "github.com/leighmacdonald/gbans/internal/rpc"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BanType int32

const (
	BanType_BAN_TYPE_OK_UNSPECIFIED BanType = 0
	BanType_BAN_TYPE_NO_COMM        BanType = 1
	BanType_BAN_TYPE_BANNED         BanType = 2
	BanType_BAN_TYPE_NETWORK        BanType = 3
)

// Enum value maps for BanType.
var (
	BanType_name = map[int32]string{
		0: "BAN_TYPE_OK_UNSPECIFIED",
		1: "BAN_TYPE_NO_COMM",
		2: "BAN_TYPE_BANNED",
		3: "BAN_TYPE_NETWORK",
	}
	BanType_value = map[string]int32{
		"BAN_TYPE_OK_UNSPECIFIED": 0,
		"BAN_TYPE_NO_COMM":        1,
		"BAN_TYPE_BANNED":         2,
		"BAN_TYPE_NETWORK":        3,
	}
)

func (x BanType) Enum() *BanType {
	p := new(BanType)
	*p = x
	return p
}

func (x BanType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BanType) Descriptor() protoreflect.EnumDescriptor {
	return file_ban_v1_ban_proto_enumTypes[0].Descriptor()
}

func (BanType) Type() protoreflect.EnumType {
	return &file_ban_v1_ban_proto_enumTypes[0]
}

func (x BanType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BanType.Descriptor instead.
func (BanType) EnumDescriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{0}
}

type AppealState int32

const (
	AppealState_APPEAL_STATE_OPEN_UNSPECIFIED AppealState = 0
	AppealState_APPEAL_STATE_DENIED           AppealState = 1
	AppealState_APPEAL_STATE_ACCEPTED         AppealState = 2
	AppealState_APPEAL_STATE_REDUCED          AppealState = 3
	AppealState_APPEAL_STATE_NO_APPEAL        AppealState = 4
)

// Enum value maps for AppealState.
var (
	AppealState_name = map[int32]string{
		0: "APPEAL_STATE_OPEN_UNSPECIFIED",
		1: "APPEAL_STATE_DENIED",
		2: "APPEAL_STATE_ACCEPTED",
		3: "APPEAL_STATE_REDUCED",
		4: "APPEAL_STATE_NO_APPEAL",
	}
	AppealState_value = map[string]int32{
		"APPEAL_STATE_OPEN_UNSPECIFIED": 0,
		"APPEAL_STATE_DENIED":           1,
		"APPEAL_STATE_ACCEPTED":         2,
		"APPEAL_STATE_REDUCED":          3,
		"APPEAL_STATE_NO_APPEAL":        4,
	}
)

func (x AppealState) Enum() *AppealState {
	p := new(AppealState)
	*p = x
	return p
}

func (x AppealState) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AppealState) Descriptor() protoreflect.EnumDescriptor {
	return file_ban_v1_ban_proto_enumTypes[1].Descriptor()
}

func (AppealState) Type() protoreflect.EnumType {
	return &file_ban_v1_ban_proto_enumTypes[1]
}

func (x AppealState) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AppealState.Descriptor instead.
func (AppealState) EnumDescriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{1}
}

type BanReason int32

const (
	BanReason_BAN_REASON_UNSPECIFIED       BanReason = 0
	BanReason_BAN_REASON_CUSTOM            BanReason = 1
	BanReason_BAN_REASON_EXTERNAL          BanReason = 2
	BanReason_BAN_REASON_CHEATING          BanReason = 3
	BanReason_BAN_REASON_RACISM            BanReason = 4
	BanReason_BAN_REASON_HARASSMENT        BanReason = 5
	BanReason_BAN_REASON_EXPLOITING        BanReason = 6
	BanReason_BAN_REASON_WARNINGS_EXCEEDED BanReason = 7
	BanReason_BAN_REASON_SPAM              BanReason = 8
	BanReason_BAN_REASON_LANGUAGE          BanReason = 9
	BanReason_BAN_REASON_PROFILE           BanReason = 10
	BanReason_BAN_REASON_ITEM_DESCRIPTIONS BanReason = 11
	BanReason_BAN_REASON_BOT_HOST          BanReason = 12
	BanReason_BAN_REASON_EVADING           BanReason = 13
	BanReason_BAN_REASON_USERNAME          BanReason = 14
)

// Enum value maps for BanReason.
var (
	BanReason_name = map[int32]string{
		0:  "BAN_REASON_UNSPECIFIED",
		1:  "BAN_REASON_CUSTOM",
		2:  "BAN_REASON_EXTERNAL",
		3:  "BAN_REASON_CHEATING",
		4:  "BAN_REASON_RACISM",
		5:  "BAN_REASON_HARASSMENT",
		6:  "BAN_REASON_EXPLOITING",
		7:  "BAN_REASON_WARNINGS_EXCEEDED",
		8:  "BAN_REASON_SPAM",
		9:  "BAN_REASON_LANGUAGE",
		10: "BAN_REASON_PROFILE",
		11: "BAN_REASON_ITEM_DESCRIPTIONS",
		12: "BAN_REASON_BOT_HOST",
		13: "BAN_REASON_EVADING",
		14: "BAN_REASON_USERNAME",
	}
	BanReason_value = map[string]int32{
		"BAN_REASON_UNSPECIFIED":       0,
		"BAN_REASON_CUSTOM":            1,
		"BAN_REASON_EXTERNAL":          2,
		"BAN_REASON_CHEATING":          3,
		"BAN_REASON_RACISM":            4,
		"BAN_REASON_HARASSMENT":        5,
		"BAN_REASON_EXPLOITING":        6,
		"BAN_REASON_WARNINGS_EXCEEDED": 7,
		"BAN_REASON_SPAM":              8,
		"BAN_REASON_LANGUAGE":          9,
		"BAN_REASON_PROFILE":           10,
		"BAN_REASON_ITEM_DESCRIPTIONS": 11,
		"BAN_REASON_BOT_HOST":          12,
		"BAN_REASON_EVADING":           13,
		"BAN_REASON_USERNAME":          14,
	}
)

func (x BanReason) Enum() *BanReason {
	p := new(BanReason)
	*p = x
	return p
}

func (x BanReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BanReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ban_v1_ban_proto_enumTypes[2].Descriptor()
}

func (BanReason) Type() protoreflect.EnumType {
	return &file_ban_v1_ban_proto_enumTypes[2]
}

func (x BanReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BanReason.Descriptor instead.
func (BanReason) EnumDescriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{2}
}

type Origin int32

const (
	Origin_ORIGIN_SYSTEM_UNSPECIFIED Origin = 0
	Origin_ORIGIN_BOT                Origin = 1
	Origin_ORIGIN_WEB                Origin = 2
	Origin_ORIGIN_IN_GAME            Origin = 3
	Origin_ORIGIN_REPORTED           Origin = 4
)

// Enum value maps for Origin.
var (
	Origin_name = map[int32]string{
		0: "ORIGIN_SYSTEM_UNSPECIFIED",
		1: "ORIGIN_BOT",
		2: "ORIGIN_WEB",
		3: "ORIGIN_IN_GAME",
		4: "ORIGIN_REPORTED",
	}
	Origin_value = map[string]int32{
		"ORIGIN_SYSTEM_UNSPECIFIED": 0,
		"ORIGIN_BOT":                1,
		"ORIGIN_WEB":                2,
		"ORIGIN_IN_GAME":            3,
		"ORIGIN_REPORTED":           4,
	}
)

func (x Origin) Enum() *Origin {
	p := new(Origin)
	*p = x
	return p
}

func (x Origin) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Origin) Descriptor() protoreflect.EnumDescriptor {
	return file_ban_v1_ban_proto_enumTypes[3].Descriptor()
}

func (Origin) Type() protoreflect.EnumType {
	return &file_ban_v1_ban_proto_enumTypes[3]
}

func (x Origin) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Origin.Descriptor instead.
func (Origin) EnumDescriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{3}
}

type ExportTF2BDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExportTF2BDResponse) Reset() {
	*x = ExportTF2BDResponse{}
	mi := &file_ban_v1_ban_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExportTF2BDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExportTF2BDResponse) ProtoMessage() {}

func (x *ExportTF2BDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ban_v1_ban_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExportTF2BDResponse.ProtoReflect.Descriptor instead.
func (*ExportTF2BDResponse) Descriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{0}
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BanId         *int64                 `protobuf:"varint,1,opt,name=ban_id,json=banId" json:"ban_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_ban_v1_ban_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ban_v1_ban_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{1}
}

func (x *DeleteRequest) GetBanId() int64 {
	if x != nil && x.BanId != nil {
		return *x.BanId
	}
	return 0
}

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SourceId      *string                `protobuf:"bytes,1,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	TargetId      *string                `protobuf:"bytes,2,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	GroupsOnly    *bool                  `protobuf:"varint,3,opt,name=groups_only,json=groupsOnly" json:"groups_only,omitempty"`
	Deleted       *bool                  `protobuf:"varint,4,opt,name=deleted" json:"deleted,omitempty"`
	Cidr          *string                `protobuf:"bytes,5,opt,name=cidr" json:"cidr,omitempty"`
	CidrOnly      *bool                  `protobuf:"varint,6,opt,name=cidr_only,json=cidrOnly" json:"cidr_only,omitempty"`
	Reason        []BanReason            `protobuf:"varint,7,rep,packed,name=reason,enum=ban.v1.BanReason" json:"reason,omitempty"`
	AppealState   *int32                 `protobuf:"varint,8,opt,name=appeal_state,json=appealState" json:"appeal_state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_ban_v1_ban_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ban_v1_ban_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{2}
}

func (x *QueryRequest) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *QueryRequest) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *QueryRequest) GetGroupsOnly() bool {
	if x != nil && x.GroupsOnly != nil {
		return *x.GroupsOnly
	}
	return false
}

func (x *QueryRequest) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *QueryRequest) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *QueryRequest) GetCidrOnly() bool {
	if x != nil && x.CidrOnly != nil {
		return *x.CidrOnly
	}
	return false
}

func (x *QueryRequest) GetReason() []BanReason {
	if x != nil {
		return x.Reason
	}
	return nil
}

func (x *QueryRequest) GetAppealState() int32 {
	if x != nil && x.AppealState != nil {
		return *x.AppealState
	}
	return 0
}

type QueryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bans          []*Ban                 `protobuf:"bytes,1,rep,name=bans" json:"bans,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResponse) Reset() {
	*x = QueryResponse{}
	mi := &file_ban_v1_ban_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResponse) ProtoMessage() {}

func (x *QueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ban_v1_ban_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResponse.ProtoReflect.Descriptor instead.
func (*QueryResponse) Descriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{3}
}

func (x *QueryResponse) GetBans() []*Ban {
	if x != nil {
		return x.Bans
	}
	return nil
}

type Ban struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TargetId          *string                `protobuf:"bytes,1,opt,name=target_id,json=targetId" json:"target_id,omitempty"`
	SourceId          *string                `protobuf:"bytes,2,opt,name=source_id,json=sourceId" json:"source_id,omitempty"`
	BanId             *int64                 `protobuf:"varint,3,opt,name=ban_id,json=banId" json:"ban_id,omitempty"`
	ReportId          *int64                 `protobuf:"varint,4,opt,name=report_id,json=reportId" json:"report_id,omitempty"`
	LastIp            *string                `protobuf:"bytes,5,opt,name=last_ip,json=lastIp" json:"last_ip,omitempty"`
	EvadeOk           *bool                  `protobuf:"varint,6,opt,name=evade_ok,json=evadeOk" json:"evade_ok,omitempty"`
	Bantype           *BanType               `protobuf:"varint,7,opt,name=bantype,enum=ban.v1.BanType" json:"bantype,omitempty"`
	Reason            *BanReason             `protobuf:"varint,8,opt,name=reason,enum=ban.v1.BanReason" json:"reason,omitempty"`
	ReasonText        *string                `protobuf:"bytes,9,opt,name=reason_text,json=reasonText" json:"reason_text,omitempty"`
	UnbanReasonText   *string                `protobuf:"bytes,10,opt,name=unban_reason_text,json=unbanReasonText" json:"unban_reason_text,omitempty"`
	Note              *string                `protobuf:"bytes,11,opt,name=note" json:"note,omitempty"`
	Origin            *Origin                `protobuf:"varint,12,opt,name=origin,enum=ban.v1.Origin" json:"origin,omitempty"`
	Cidr              *string                `protobuf:"bytes,13,opt,name=cidr" json:"cidr,omitempty"`
	AppealState       *AppealState           `protobuf:"varint,14,opt,name=appeal_state,json=appealState,enum=ban.v1.AppealState" json:"appeal_state,omitempty"`
	Name              *string                `protobuf:"bytes,15,opt,name=name" json:"name,omitempty"`
	Deleted           *bool                  `protobuf:"varint,16,opt,name=deleted" json:"deleted,omitempty"`
	IsEnabled         *bool                  `protobuf:"varint,17,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	ValidUntil        *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=valid_until,json=validUntil" json:"valid_until,omitempty"`
	CreatedOn         *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn         *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	SourcePersonaname *string                `protobuf:"bytes,21,opt,name=source_personaname,json=sourcePersonaname" json:"source_personaname,omitempty"`
	SourceAvatarhash  *string                `protobuf:"bytes,22,opt,name=source_avatarhash,json=sourceAvatarhash" json:"source_avatarhash,omitempty"`
	TargetPersonaname *string                `protobuf:"bytes,23,opt,name=target_personaname,json=targetPersonaname" json:"target_personaname,omitempty"`
	TargetAvatarhash  *string                `protobuf:"bytes,24,opt,name=target_avatarhash,json=targetAvatarhash" json:"target_avatarhash,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *Ban) Reset() {
	*x = Ban{}
	mi := &file_ban_v1_ban_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ban) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ban) ProtoMessage() {}

func (x *Ban) ProtoReflect() protoreflect.Message {
	mi := &file_ban_v1_ban_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ban.ProtoReflect.Descriptor instead.
func (*Ban) Descriptor() ([]byte, []int) {
	return file_ban_v1_ban_proto_rawDescGZIP(), []int{4}
}

func (x *Ban) GetTargetId() string {
	if x != nil && x.TargetId != nil {
		return *x.TargetId
	}
	return ""
}

func (x *Ban) GetSourceId() string {
	if x != nil && x.SourceId != nil {
		return *x.SourceId
	}
	return ""
}

func (x *Ban) GetBanId() int64 {
	if x != nil && x.BanId != nil {
		return *x.BanId
	}
	return 0
}

func (x *Ban) GetReportId() int64 {
	if x != nil && x.ReportId != nil {
		return *x.ReportId
	}
	return 0
}

func (x *Ban) GetLastIp() string {
	if x != nil && x.LastIp != nil {
		return *x.LastIp
	}
	return ""
}

func (x *Ban) GetEvadeOk() bool {
	if x != nil && x.EvadeOk != nil {
		return *x.EvadeOk
	}
	return false
}

func (x *Ban) GetBantype() BanType {
	if x != nil && x.Bantype != nil {
		return *x.Bantype
	}
	return BanType_BAN_TYPE_OK_UNSPECIFIED
}

func (x *Ban) GetReason() BanReason {
	if x != nil && x.Reason != nil {
		return *x.Reason
	}
	return BanReason_BAN_REASON_UNSPECIFIED
}

func (x *Ban) GetReasonText() string {
	if x != nil && x.ReasonText != nil {
		return *x.ReasonText
	}
	return ""
}

func (x *Ban) GetUnbanReasonText() string {
	if x != nil && x.UnbanReasonText != nil {
		return *x.UnbanReasonText
	}
	return ""
}

func (x *Ban) GetNote() string {
	if x != nil && x.Note != nil {
		return *x.Note
	}
	return ""
}

func (x *Ban) GetOrigin() Origin {
	if x != nil && x.Origin != nil {
		return *x.Origin
	}
	return Origin_ORIGIN_SYSTEM_UNSPECIFIED
}

func (x *Ban) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *Ban) GetAppealState() AppealState {
	if x != nil && x.AppealState != nil {
		return *x.AppealState
	}
	return AppealState_APPEAL_STATE_OPEN_UNSPECIFIED
}

func (x *Ban) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Ban) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *Ban) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *Ban) GetValidUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.ValidUntil
	}
	return nil
}

func (x *Ban) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Ban) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

func (x *Ban) GetSourcePersonaname() string {
	if x != nil && x.SourcePersonaname != nil {
		return *x.SourcePersonaname
	}
	return ""
}

func (x *Ban) GetSourceAvatarhash() string {
	if x != nil && x.SourceAvatarhash != nil {
		return *x.SourceAvatarhash
	}
	return ""
}

func (x *Ban) GetTargetPersonaname() string {
	if x != nil && x.TargetPersonaname != nil {
		return *x.TargetPersonaname
	}
	return ""
}

func (x *Ban) GetTargetAvatarhash() string {
	if x != nil && x.TargetAvatarhash != nil {
		return *x.TargetAvatarhash
	}
	return ""
}

var File_ban_v1_ban_proto protoreflect.FileDescriptor

const file_ban_v1_ban_proto_rawDesc = "" +
	"\n" +
	"\x10ban/v1/ban.proto\x12\x06ban.v1\x1a\ffilter.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x15\n" +
	"\x13ExportTF2BDResponse\"&\n" +
	"\rDeleteRequest\x12\x15\n" +
	"\x06ban_id\x18\x01 \x01(\x03R\x05banId\"\x82\x02\n" +
	"\fQueryRequest\x12\x1b\n" +
	"\tsource_id\x18\x01 \x01(\tR\bsourceId\x12\x1b\n" +
	"\ttarget_id\x18\x02 \x01(\tR\btargetId\x12\x1f\n" +
	"\vgroups_only\x18\x03 \x01(\bR\n" +
	"groupsOnly\x12\x18\n" +
	"\adeleted\x18\x04 \x01(\bR\adeleted\x12\x12\n" +
	"\x04cidr\x18\x05 \x01(\tR\x04cidr\x12\x1b\n" +
	"\tcidr_only\x18\x06 \x01(\bR\bcidrOnly\x12)\n" +
	"\x06reason\x18\a \x03(\x0e2\x11.ban.v1.BanReasonR\x06reason\x12!\n" +
	"\fappeal_state\x18\b \x01(\x05R\vappealState\"0\n" +
	"\rQueryResponse\x12\x1f\n" +
	"\x04bans\x18\x01 \x03(\v2\v.ban.v1.BanR\x04bans\"\x8a\a\n" +
	"\x03Ban\x12\x1b\n" +
	"\ttarget_id\x18\x01 \x01(\tR\btargetId\x12\x1b\n" +
	"\tsource_id\x18\x02 \x01(\tR\bsourceId\x12\x15\n" +
	"\x06ban_id\x18\x03 \x01(\x03R\x05banId\x12\x1b\n" +
	"\treport_id\x18\x04 \x01(\x03R\breportId\x12\x17\n" +
	"\alast_ip\x18\x05 \x01(\tR\x06lastIp\x12\x19\n" +
	"\bevade_ok\x18\x06 \x01(\bR\aevadeOk\x12)\n" +
	"\abantype\x18\a \x01(\x0e2\x0f.ban.v1.BanTypeR\abantype\x12)\n" +
	"\x06reason\x18\b \x01(\x0e2\x11.ban.v1.BanReasonR\x06reason\x12\x1f\n" +
	"\vreason_text\x18\t \x01(\tR\n" +
	"reasonText\x12*\n" +
	"\x11unban_reason_text\x18\n" +
	" \x01(\tR\x0funbanReasonText\x12\x12\n" +
	"\x04note\x18\v \x01(\tR\x04note\x12&\n" +
	"\x06origin\x18\f \x01(\x0e2\x0e.ban.v1.OriginR\x06origin\x12\x12\n" +
	"\x04cidr\x18\r \x01(\tR\x04cidr\x126\n" +
	"\fappeal_state\x18\x0e \x01(\x0e2\x13.ban.v1.AppealStateR\vappealState\x12\x12\n" +
	"\x04name\x18\x0f \x01(\tR\x04name\x12\x18\n" +
	"\adeleted\x18\x10 \x01(\bR\adeleted\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x11 \x01(\bR\tisEnabled\x12;\n" +
	"\vvalid_until\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"validUntil\x129\n" +
	"\n" +
	"created_on\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x129\n" +
	"\n" +
	"updated_on\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedOn\x12-\n" +
	"\x12source_personaname\x18\x15 \x01(\tR\x11sourcePersonaname\x12+\n" +
	"\x11source_avatarhash\x18\x16 \x01(\tR\x10sourceAvatarhash\x12-\n" +
	"\x12target_personaname\x18\x17 \x01(\tR\x11targetPersonaname\x12+\n" +
	"\x11target_avatarhash\x18\x18 \x01(\tR\x10targetAvatarhash*g\n" +
	"\aBanType\x12\x1b\n" +
	"\x17BAN_TYPE_OK_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10BAN_TYPE_NO_COMM\x10\x01\x12\x13\n" +
	"\x0fBAN_TYPE_BANNED\x10\x02\x12\x14\n" +
	"\x10BAN_TYPE_NETWORK\x10\x03*\x9a\x01\n" +
	"\vAppealState\x12!\n" +
	"\x1dAPPEAL_STATE_OPEN_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13APPEAL_STATE_DENIED\x10\x01\x12\x19\n" +
	"\x15APPEAL_STATE_ACCEPTED\x10\x02\x12\x18\n" +
	"\x14APPEAL_STATE_REDUCED\x10\x03\x12\x1a\n" +
	"\x16APPEAL_STATE_NO_APPEAL\x10\x04*\x91\x03\n" +
	"\tBanReason\x12\x1a\n" +
	"\x16BAN_REASON_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11BAN_REASON_CUSTOM\x10\x01\x12\x17\n" +
	"\x13BAN_REASON_EXTERNAL\x10\x02\x12\x17\n" +
	"\x13BAN_REASON_CHEATING\x10\x03\x12\x15\n" +
	"\x11BAN_REASON_RACISM\x10\x04\x12\x19\n" +
	"\x15BAN_REASON_HARASSMENT\x10\x05\x12\x19\n" +
	"\x15BAN_REASON_EXPLOITING\x10\x06\x12 \n" +
	"\x1cBAN_REASON_WARNINGS_EXCEEDED\x10\a\x12\x13\n" +
	"\x0fBAN_REASON_SPAM\x10\b\x12\x17\n" +
	"\x13BAN_REASON_LANGUAGE\x10\t\x12\x16\n" +
	"\x12BAN_REASON_PROFILE\x10\n" +
	"\x12 \n" +
	"\x1cBAN_REASON_ITEM_DESCRIPTIONS\x10\v\x12\x17\n" +
	"\x13BAN_REASON_BOT_HOST\x10\f\x12\x16\n" +
	"\x12BAN_REASON_EVADING\x10\r\x12\x17\n" +
	"\x13BAN_REASON_USERNAME\x10\x0e*p\n" +
	"\x06Origin\x12\x1d\n" +
	"\x19ORIGIN_SYSTEM_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"ORIGIN_BOT\x10\x01\x12\x0e\n" +
	"\n" +
	"ORIGIN_WEB\x10\x02\x12\x12\n" +
	"\x0eORIGIN_IN_GAME\x10\x03\x12\x13\n" +
	"\x0fORIGIN_REPORTED\x10\x042\xc5\x01\n" +
	"\n" +
	"BanService\x126\n" +
	"\x05Query\x12\x14.ban.v1.QueryRequest\x1a\x15.ban.v1.QueryResponse\"\x00\x12D\n" +
	"\vExportTF2BD\x12\x16.google.protobuf.Empty\x1a\x1b.ban.v1.ExportTF2BDResponse\"\x00\x129\n" +
	"\x06Delete\x12\x15.ban.v1.DeleteRequest\x1a\x16.google.protobuf.Empty\"\x00B\x8a\x01\n" +
	"\n" +
	"com.ban.v1B\bBanProtoP\x01Z9github.com/leighmacdonald/gbans/internal/rpc/ban/v1;banv1\xa2\x02\x03BXX\xaa\x02\x06Ban.V1\xca\x02\x06Ban\\V1\xe2\x02\x12Ban\\V1\\GPBMetadata\xea\x02\aBan::V1b\beditionsp\xe8\a"

var (
	file_ban_v1_ban_proto_rawDescOnce sync.Once
	file_ban_v1_ban_proto_rawDescData []byte
)

func file_ban_v1_ban_proto_rawDescGZIP() []byte {
	file_ban_v1_ban_proto_rawDescOnce.Do(func() {
		file_ban_v1_ban_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ban_v1_ban_proto_rawDesc), len(file_ban_v1_ban_proto_rawDesc)))
	})
	return file_ban_v1_ban_proto_rawDescData
}

var file_ban_v1_ban_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_ban_v1_ban_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_ban_v1_ban_proto_goTypes = []any{
	(BanType)(0),                  // 0: ban.v1.BanType
	(AppealState)(0),              // 1: ban.v1.AppealState
	(BanReason)(0),                // 2: ban.v1.BanReason
	(Origin)(0),                   // 3: ban.v1.Origin
	(*ExportTF2BDResponse)(nil),   // 4: ban.v1.ExportTF2BDResponse
	(*DeleteRequest)(nil),         // 5: ban.v1.DeleteRequest
	(*QueryRequest)(nil),          // 6: ban.v1.QueryRequest
	(*QueryResponse)(nil),         // 7: ban.v1.QueryResponse
	(*Ban)(nil),                   // 8: ban.v1.Ban
	(*timestamppb.Timestamp)(nil), // 9: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 10: google.protobuf.Empty
}
var file_ban_v1_ban_proto_depIdxs = []int32{
	2,  // 0: ban.v1.QueryRequest.reason:type_name -> ban.v1.BanReason
	8,  // 1: ban.v1.QueryResponse.bans:type_name -> ban.v1.Ban
	0,  // 2: ban.v1.Ban.bantype:type_name -> ban.v1.BanType
	2,  // 3: ban.v1.Ban.reason:type_name -> ban.v1.BanReason
	3,  // 4: ban.v1.Ban.origin:type_name -> ban.v1.Origin
	1,  // 5: ban.v1.Ban.appeal_state:type_name -> ban.v1.AppealState
	9,  // 6: ban.v1.Ban.valid_until:type_name -> google.protobuf.Timestamp
	9,  // 7: ban.v1.Ban.created_on:type_name -> google.protobuf.Timestamp
	9,  // 8: ban.v1.Ban.updated_on:type_name -> google.protobuf.Timestamp
	6,  // 9: ban.v1.BanService.Query:input_type -> ban.v1.QueryRequest
	10, // 10: ban.v1.BanService.ExportTF2BD:input_type -> google.protobuf.Empty
	5,  // 11: ban.v1.BanService.Delete:input_type -> ban.v1.DeleteRequest
	7,  // 12: ban.v1.BanService.Query:output_type -> ban.v1.QueryResponse
	4,  // 13: ban.v1.BanService.ExportTF2BD:output_type -> ban.v1.ExportTF2BDResponse
	10, // 14: ban.v1.BanService.Delete:output_type -> google.protobuf.Empty
	12, // [12:15] is the sub-list for method output_type
	9,  // [9:12] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_ban_v1_ban_proto_init() }
func file_ban_v1_ban_proto_init() {
	if File_ban_v1_ban_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ban_v1_ban_proto_rawDesc), len(file_ban_v1_ban_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ban_v1_ban_proto_goTypes,
		DependencyIndexes: file_ban_v1_ban_proto_depIdxs,
		EnumInfos:         file_ban_v1_ban_proto_enumTypes,
		MessageInfos:      file_ban_v1_ban_proto_msgTypes,
	}.Build()
	File_ban_v1_ban_proto = out.File
	file_ban_v1_ban_proto_goTypes = nil
	file_ban_v1_ban_proto_depIdxs = nil
}
