env_files = [".env"]

[build]
cmd = "go generate && CGO_ENABLED=0 go build -gcflags=all=\"-N -l\" -o ./tmp/main-gbans . && killall -9 main-gbans || true"
full_bin = "./tmp/main-gbans"
rerun = true
include_dir = ["internal", "pkg", "proto"]
include_file = ["main.go"]
exclude_regex = ["testdata", "frotend/rpc"]
delay = 2500
send_interrupt = false
stop_on_error = true

[proxy]
enabled = false
