version: "2"
linters:
  default: none
  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - containedctx
    - copyloopvar
    - decorder
    - dogsled
    - dupword
    - err113
    - errcheck
    - errchkjson
    - errname
    - errorlint
    - forbidigo
    - forcetypeassert
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gochecksumtype
    - goconst
    - gocritic
    - godot
    - goheader
    - gomoddirectives
    - gomodguard
    - goprintffuncname
    - gosec
    - gosmopolitan
    - govet
    - grouper
    - importas
    - inamedparam
    - ineffassign
    - interfacebloat
    - intrange
    - loggercheck
    - maintidx
    - makezero
    - mirror
    - misspell
    - musttag
    - nakedret
    - nilerr
    - nilnil
    - nlreturn
    - noctx
    - nonamedreturns
    - nosprintfhostport
    - perfsprint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - revive
    - rowserrcheck
    - sloglint
    - spancheck
    - sqlclosecheck
    - staticcheck
    - tagliatelle
    - testableexamples
    - testifylint
    - testpackage
    - thelper
    - unconvert
    - unparam
    # - unused
    - usestdlibvars
    - usetesting
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
  settings:
    varnamelen:
      ignore-decls:
        - t *testing.T
        - T any
        - r *gin.Engine
        - r fixture.CreateRouter
    depguard:
      rules:
        errors:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: go.uber.org/zap
              desc: Replaced with log/slog
    funlen:
      lines: 100
      statements: -1
    interfacebloat:
      max: 26
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - river.JobCancel(
      ignore-package-globs:
        - github.com/leighmacdonald/gbans/pkg/*
        - github.com/leighmacdonald/gbans/internal/*
        - github.com/leighmacdonald/discordgo-lipstick/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/web/data.go
      - pkg/msqp
      - pkg/mm
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/web/data.go
      - pkg/msqp
      - pkg/mm
      - third_party$
      - builtin$
      - examples$
