version: "2"
linters:
  default: all
  disable:
    - contextcheck
    - dupl
    - durationcheck
    - exhaustive
    - gocognit
    - gocyclo
    - funcorder
    - ireturn
    - lll
    - exhaustruct
    - mnd
    - godoclint
    - godox
    - noinlineerr
    - nolintlint
    - paralleltest
    - tagalign
    - wsl_v5
    - wsl
    - unused
  settings:
    cyclop:
      # The maximal code complexity to report.
      # Default: 10
      max-complexity: 25

    nestif:
      # Minimal complexity of if statements to report.
      min-complexity: 10
    varnamelen:
      ignore-decls:
        - t *testing.T
        - T any
        - r *gin.Engine
        - r fixture.CreateRouter
    depguard:
      rules:
        errors:
          deny:
            - pkg: github.com/pkg/errors
              desc: Should be replaced by standard lib errors package
            - pkg: go.uber.org/zap
              desc: Replaced with log/slog
    funlen:
      lines: 200
      statements: -1
    interfacebloat:
      max: 26
    tagliatelle:
      case:
        rules:
          json: snake
          yaml: snake
        use-field-name: true
    wrapcheck:
      ignore-sigs:
        - .Errorf(
        - errors.New(
        - errors.Unwrap(
        - errors.Join(
        - .Wrap(
        - .Wrapf(
        - .WithMessage(
        - .WithMessagef(
        - .WithStack(
        - river.JobCancel(
      ignore-package-globs:
        - github.com/leighmacdonald/gbans/pkg/*
        - github.com/leighmacdonald/gbans/internal/*
        - github.com/leighmacdonald/discordgo-lipstick/*
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    paths:
      - internal/web/data.go
      - pkg/msqp
      - pkg/mm
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
  exclusions:
    generated: lax
    paths:
      - internal/web/data.go
      - pkg/msqp
      - pkg/mm
      - third_party$
      - builtin$
      - examples$
