version: 2
project_name: gbans

before:
  hooks:
    - make frontend

dockers:
  - dockerfile: "docker/Dockerfile"
    skip_push: false
    ids: ["gbans"]
    image_templates:
      - "ghcr.io/leighmacdonald/gbans:latest"
      - "ghcr.io/leighmacdonald/gbans:{{ .Tag }}"
      - "ghcr.io/leighmacdonald/gbans:v{{ .Major }}"
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title={{.ProjectName}}"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"

builds:
  - id: gbans
    env: [CGO_ENABLED=0]
    goos:
      - linux
      - windows
    goarch:
      - amd64
    tags:
      - release
    ldflags:
      - -s
      - -w
      #- -X github.com/leighmacdonald/gbans/internal/app.SentryDSN={{ .Env.SENTRY_DSN }}
      - -X github.com/leighmacdonald/gbans/internal/app.BuildVersion={{.Version}}
      - -X github.com/leighmacdonald/gbans/internal/app.BuildCommit={{.Commit}}
      - -X github.com/leighmacdonald/gbans/internal/app.BuildDate={{.Date}}

nfpms:
  - maintainer: Leigh MacDonald <leigh.macdonald@gmail.com>
    description: TF2 Community Backend
    homepage: https://github.com/leighmacdonald/gbans
    license: MIT
    formats:
      - deb
      - rpm
      - apk

archives:
  - formats: ["tar.gz"]
    files:
      - LICENSE.md
      - README.md
      - gbans_example.yml
      - sourcemod/plugins/gbans.smx
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_{{- title .Os }}_{{- .Version }}-
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        formats: ["zip"]

checksum:
  name_template: "checksums.txt"

release:
  github:
    owner: leighmacdonald
    name: gbans
  draft: false
  replace_existing_draft: true
  prerelease: auto

changelog:
  use: github-native
#signs:
#  - artifacts: checksum
#    args:
#      - "--batch"
#      - "-u"
#      - "{{ .Env.GPG_FINGERPRINT }}"
#      - "--output"
#      - "${signature}"
#      - "--detach-sign"
#      - "${artifact}"

#sboms:
#  - artifacts: archive

#announce:
#  discord:
#    enabled: true
#    message_template: 'gbans {{.Tag}} is out!'
#
#    # Set author of the embed.
#    # Defaults to `GoReleaser`
#    author: 'Leigh MacDonald'
#    # color: ''
#
#    # URL to an image to use as the icon for the embed.
#    # Defaults to `https://goreleaser.com/static/avatar.png`
#    # icon_url: ''

# yaml-language-server: $schema=https://goreleaser.com/static/schema-pro.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj
