// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: sourcemod/v1/sourcemod.proto

package sourcemodv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverrideType int32

const (
	OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED OverrideType = 0
	OverrideType_OVERRIDE_TYPE_GROUP               OverrideType = 1
)

// Enum value maps for OverrideType.
var (
	OverrideType_name = map[int32]string{
		0: "OVERRIDE_TYPE_COMMAND_UNSPECIFIED",
		1: "OVERRIDE_TYPE_GROUP",
	}
	OverrideType_value = map[string]int32{
		"OVERRIDE_TYPE_COMMAND_UNSPECIFIED": 0,
		"OVERRIDE_TYPE_GROUP":               1,
	}
)

func (x OverrideType) Enum() *OverrideType {
	p := new(OverrideType)
	*p = x
	return p
}

func (x OverrideType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverrideType) Descriptor() protoreflect.EnumDescriptor {
	return file_sourcemod_v1_sourcemod_proto_enumTypes[0].Descriptor()
}

func (OverrideType) Type() protoreflect.EnumType {
	return &file_sourcemod_v1_sourcemod_proto_enumTypes[0]
}

func (x OverrideType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverrideType.Descriptor instead.
func (OverrideType) EnumDescriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{0}
}

type OverrideAccess int32

const (
	OverrideAccess_OVERRIDE_ACCESS_ALLOW_UNSPECIFIED OverrideAccess = 0
	OverrideAccess_OVERRIDE_ACCESS_DENY              OverrideAccess = 1
)

// Enum value maps for OverrideAccess.
var (
	OverrideAccess_name = map[int32]string{
		0: "OVERRIDE_ACCESS_ALLOW_UNSPECIFIED",
		1: "OVERRIDE_ACCESS_DENY",
	}
	OverrideAccess_value = map[string]int32{
		"OVERRIDE_ACCESS_ALLOW_UNSPECIFIED": 0,
		"OVERRIDE_ACCESS_DENY":              1,
	}
)

func (x OverrideAccess) Enum() *OverrideAccess {
	p := new(OverrideAccess)
	*p = x
	return p
}

func (x OverrideAccess) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OverrideAccess) Descriptor() protoreflect.EnumDescriptor {
	return file_sourcemod_v1_sourcemod_proto_enumTypes[1].Descriptor()
}

func (OverrideAccess) Type() protoreflect.EnumType {
	return &file_sourcemod_v1_sourcemod_proto_enumTypes[1]
}

func (x OverrideAccess) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OverrideAccess.Descriptor instead.
func (OverrideAccess) EnumDescriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{1}
}

type AuthType int32

const (
	AuthType_AUTH_TYPE_STEAM_UNSPECIFIED AuthType = 0
	AuthType_AUTH_TYPE_NAME              AuthType = 1
	AuthType_AUTH_TYPE_IP                AuthType = 2
)

// Enum value maps for AuthType.
var (
	AuthType_name = map[int32]string{
		0: "AUTH_TYPE_STEAM_UNSPECIFIED",
		1: "AUTH_TYPE_NAME",
		2: "AUTH_TYPE_IP",
	}
	AuthType_value = map[string]int32{
		"AUTH_TYPE_STEAM_UNSPECIFIED": 0,
		"AUTH_TYPE_NAME":              1,
		"AUTH_TYPE_IP":                2,
	}
)

func (x AuthType) Enum() *AuthType {
	p := new(AuthType)
	*p = x
	return p
}

func (x AuthType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthType) Descriptor() protoreflect.EnumDescriptor {
	return file_sourcemod_v1_sourcemod_proto_enumTypes[2].Descriptor()
}

func (AuthType) Type() protoreflect.EnumType {
	return &file_sourcemod_v1_sourcemod_proto_enumTypes[2]
}

func (x AuthType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthType.Descriptor instead.
func (AuthType) EnumDescriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{2}
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Flags         *string                `protobuf:"bytes,2,opt,name=flags" json:"flags,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	ImmunityLevel *int32                 `protobuf:"varint,4,opt,name=immunity_level,json=immunityLevel" json:"immunity_level,omitempty"`
	CreatedOn     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{0}
}

func (x *Group) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *Group) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Group) GetImmunityLevel() int32 {
	if x != nil && x.ImmunityLevel != nil {
		return *x.ImmunityLevel
	}
	return 0
}

func (x *Group) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Group) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

type GroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups" json:"groups,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupsResponse) Reset() {
	*x = GroupsResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupsResponse) ProtoMessage() {}

func (x *GroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupsResponse.ProtoReflect.Descriptor instead.
func (*GroupsResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{1}
}

func (x *GroupsResponse) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

type CreateGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Immunity      *int32                 `protobuf:"varint,2,opt,name=immunity" json:"immunity,omitempty"`
	Flags         *string                `protobuf:"bytes,3,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupRequest) Reset() {
	*x = CreateGroupRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupRequest) ProtoMessage() {}

func (x *CreateGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{2}
}

func (x *CreateGroupRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateGroupRequest) GetImmunity() int32 {
	if x != nil && x.Immunity != nil {
		return *x.Immunity
	}
	return 0
}

func (x *CreateGroupRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

type CreateGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupResponse) Reset() {
	*x = CreateGroupResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupResponse) ProtoMessage() {}

func (x *CreateGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{3}
}

func (x *CreateGroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type EditGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Immunity      *int32                 `protobuf:"varint,3,opt,name=immunity" json:"immunity,omitempty"`
	Flags         *string                `protobuf:"bytes,4,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditGroupsRequest) Reset() {
	*x = EditGroupsRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupsRequest) ProtoMessage() {}

func (x *EditGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupsRequest.ProtoReflect.Descriptor instead.
func (*EditGroupsRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{4}
}

func (x *EditGroupsRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *EditGroupsRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditGroupsRequest) GetImmunity() int32 {
	if x != nil && x.Immunity != nil {
		return *x.Immunity
	}
	return 0
}

func (x *EditGroupsRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

type EditGroupsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Group         *Group                 `protobuf:"bytes,1,opt,name=group" json:"group,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditGroupsResponse) Reset() {
	*x = EditGroupsResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupsResponse) ProtoMessage() {}

func (x *EditGroupsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupsResponse.ProtoReflect.Descriptor instead.
func (*EditGroupsResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{5}
}

func (x *EditGroupsResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

type DeleteGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupRequest) Reset() {
	*x = DeleteGroupRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupRequest) ProtoMessage() {}

func (x *DeleteGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteGroupRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type GroupOverridesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOverridesRequest) Reset() {
	*x = GroupOverridesRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOverridesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOverridesRequest) ProtoMessage() {}

func (x *GroupOverridesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOverridesRequest.ProtoReflect.Descriptor instead.
func (*GroupOverridesRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{7}
}

func (x *GroupOverridesRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type GroupOverridesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overrides     []*GroupOverrides      `protobuf:"bytes,1,rep,name=overrides" json:"overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupOverridesResponse) Reset() {
	*x = GroupOverridesResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOverridesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOverridesResponse) ProtoMessage() {}

func (x *GroupOverridesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOverridesResponse.ProtoReflect.Descriptor instead.
func (*GroupOverridesResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{8}
}

func (x *GroupOverridesResponse) GetOverrides() []*GroupOverrides {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type CreateGroupOverrideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupOverrideId *int32                 `protobuf:"varint,1,opt,name=group_override_id,json=groupOverrideId" json:"group_override_id,omitempty"`
	GroupId         *int32                 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	Type            *OverrideType          `protobuf:"varint,3,opt,name=type,enum=sourcemod.v1.OverrideType" json:"type,omitempty"`
	Name            *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	Access          *OverrideAccess        `protobuf:"varint,5,opt,name=access,enum=sourcemod.v1.OverrideAccess" json:"access,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateGroupOverrideRequest) Reset() {
	*x = CreateGroupOverrideRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupOverrideRequest) ProtoMessage() {}

func (x *CreateGroupOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupOverrideRequest.ProtoReflect.Descriptor instead.
func (*CreateGroupOverrideRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{9}
}

func (x *CreateGroupOverrideRequest) GetGroupOverrideId() int32 {
	if x != nil && x.GroupOverrideId != nil {
		return *x.GroupOverrideId
	}
	return 0
}

func (x *CreateGroupOverrideRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *CreateGroupOverrideRequest) GetType() OverrideType {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *CreateGroupOverrideRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateGroupOverrideRequest) GetAccess() OverrideAccess {
	if x != nil && x.Access != nil {
		return *x.Access
	}
	return OverrideAccess_OVERRIDE_ACCESS_ALLOW_UNSPECIFIED
}

type CreateGroupOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupOverride *GroupOverrides        `protobuf:"bytes,1,opt,name=group_override,json=groupOverride" json:"group_override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateGroupOverrideResponse) Reset() {
	*x = CreateGroupOverrideResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateGroupOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateGroupOverrideResponse) ProtoMessage() {}

func (x *CreateGroupOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateGroupOverrideResponse.ProtoReflect.Descriptor instead.
func (*CreateGroupOverrideResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{10}
}

func (x *CreateGroupOverrideResponse) GetGroupOverride() *GroupOverrides {
	if x != nil {
		return x.GroupOverride
	}
	return nil
}

type EditGroupOverrideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupId         *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	GroupOverrideId *int32                 `protobuf:"varint,2,opt,name=group_override_id,json=groupOverrideId" json:"group_override_id,omitempty"`
	Name            *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	OverrideType    *OverrideType          `protobuf:"varint,4,opt,name=override_type,json=overrideType,enum=sourcemod.v1.OverrideType" json:"override_type,omitempty"`
	OverrideAccess  *OverrideAccess        `protobuf:"varint,5,opt,name=override_access,json=overrideAccess,enum=sourcemod.v1.OverrideAccess" json:"override_access,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *EditGroupOverrideRequest) Reset() {
	*x = EditGroupOverrideRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupOverrideRequest) ProtoMessage() {}

func (x *EditGroupOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupOverrideRequest.ProtoReflect.Descriptor instead.
func (*EditGroupOverrideRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{11}
}

func (x *EditGroupOverrideRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *EditGroupOverrideRequest) GetGroupOverrideId() int32 {
	if x != nil && x.GroupOverrideId != nil {
		return *x.GroupOverrideId
	}
	return 0
}

func (x *EditGroupOverrideRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditGroupOverrideRequest) GetOverrideType() OverrideType {
	if x != nil && x.OverrideType != nil {
		return *x.OverrideType
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *EditGroupOverrideRequest) GetOverrideAccess() OverrideAccess {
	if x != nil && x.OverrideAccess != nil {
		return *x.OverrideAccess
	}
	return OverrideAccess_OVERRIDE_ACCESS_ALLOW_UNSPECIFIED
}

type EditGroupOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupOverride *GroupOverrides        `protobuf:"bytes,1,opt,name=group_override,json=groupOverride" json:"group_override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditGroupOverrideResponse) Reset() {
	*x = EditGroupOverrideResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditGroupOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditGroupOverrideResponse) ProtoMessage() {}

func (x *EditGroupOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditGroupOverrideResponse.ProtoReflect.Descriptor instead.
func (*EditGroupOverrideResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{12}
}

func (x *EditGroupOverrideResponse) GetGroupOverride() *GroupOverrides {
	if x != nil {
		return x.GroupOverride
	}
	return nil
}

type DeleteGroupOverrideRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupOverrideId *int32                 `protobuf:"varint,1,opt,name=group_override_id,json=groupOverrideId" json:"group_override_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DeleteGroupOverrideRequest) Reset() {
	*x = DeleteGroupOverrideRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupOverrideRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupOverrideRequest) ProtoMessage() {}

func (x *DeleteGroupOverrideRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupOverrideRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupOverrideRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteGroupOverrideRequest) GetGroupOverrideId() int32 {
	if x != nil && x.GroupOverrideId != nil {
		return *x.GroupOverrideId
	}
	return 0
}

type DeleteGroupOverrideResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupOverrideResponse) Reset() {
	*x = DeleteGroupOverrideResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupOverrideResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupOverrideResponse) ProtoMessage() {}

func (x *DeleteGroupOverrideResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupOverrideResponse.ProtoReflect.Descriptor instead.
func (*DeleteGroupOverrideResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{14}
}

type AdminsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admins        []*Admin               `protobuf:"bytes,1,rep,name=admins" json:"admins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdminsResponse) Reset() {
	*x = AdminsResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdminsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdminsResponse) ProtoMessage() {}

func (x *AdminsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdminsResponse.ProtoReflect.Descriptor instead.
func (*AdminsResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{15}
}

func (x *AdminsResponse) GetAdmins() []*Admin {
	if x != nil {
		return x.Admins
	}
	return nil
}

type CreateAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuthType      *AuthType              `protobuf:"varint,1,opt,name=auth_type,json=authType,enum=sourcemod.v1.AuthType" json:"auth_type,omitempty"`
	Identity      *string                `protobuf:"bytes,2,opt,name=identity" json:"identity,omitempty"`
	Password      *string                `protobuf:"bytes,3,opt,name=password" json:"password,omitempty"`
	Flags         *string                `protobuf:"bytes,4,opt,name=flags" json:"flags,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	Immunity      *int32                 `protobuf:"varint,6,opt,name=immunity" json:"immunity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminRequest) Reset() {
	*x = CreateAdminRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminRequest) ProtoMessage() {}

func (x *CreateAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminRequest.ProtoReflect.Descriptor instead.
func (*CreateAdminRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{16}
}

func (x *CreateAdminRequest) GetAuthType() AuthType {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return AuthType_AUTH_TYPE_STEAM_UNSPECIFIED
}

func (x *CreateAdminRequest) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *CreateAdminRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *CreateAdminRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

func (x *CreateAdminRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateAdminRequest) GetImmunity() int32 {
	if x != nil && x.Immunity != nil {
		return *x.Immunity
	}
	return 0
}

type CreateAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateAdminResponse) Reset() {
	*x = CreateAdminResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdminResponse) ProtoMessage() {}

func (x *CreateAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdminResponse.ProtoReflect.Descriptor instead.
func (*CreateAdminResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{17}
}

func (x *CreateAdminResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type EditAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       *int32                 `protobuf:"varint,1,opt,name=admin_id,json=adminId" json:"admin_id,omitempty"`
	AuthType      *AuthType              `protobuf:"varint,2,opt,name=auth_type,json=authType,enum=sourcemod.v1.AuthType" json:"auth_type,omitempty"`
	Identity      *string                `protobuf:"bytes,3,opt,name=identity" json:"identity,omitempty"`
	Password      *string                `protobuf:"bytes,4,opt,name=password" json:"password,omitempty"`
	Flags         *string                `protobuf:"bytes,5,opt,name=flags" json:"flags,omitempty"`
	Name          *string                `protobuf:"bytes,6,opt,name=name" json:"name,omitempty"`
	Immunity      *int32                 `protobuf:"varint,7,opt,name=immunity" json:"immunity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAdminRequest) Reset() {
	*x = EditAdminRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAdminRequest) ProtoMessage() {}

func (x *EditAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAdminRequest.ProtoReflect.Descriptor instead.
func (*EditAdminRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{18}
}

func (x *EditAdminRequest) GetAdminId() int32 {
	if x != nil && x.AdminId != nil {
		return *x.AdminId
	}
	return 0
}

func (x *EditAdminRequest) GetAuthType() AuthType {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return AuthType_AUTH_TYPE_STEAM_UNSPECIFIED
}

func (x *EditAdminRequest) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *EditAdminRequest) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *EditAdminRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

func (x *EditAdminRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditAdminRequest) GetImmunity() int32 {
	if x != nil && x.Immunity != nil {
		return *x.Immunity
	}
	return 0
}

type EditAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditAdminResponse) Reset() {
	*x = EditAdminResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditAdminResponse) ProtoMessage() {}

func (x *EditAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditAdminResponse.ProtoReflect.Descriptor instead.
func (*EditAdminResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{19}
}

func (x *EditAdminResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type DeleteAdminRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       *int32                 `protobuf:"varint,1,opt,name=admin_id,json=adminId" json:"admin_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminRequest) Reset() {
	*x = DeleteAdminRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminRequest) ProtoMessage() {}

func (x *DeleteAdminRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{20}
}

func (x *DeleteAdminRequest) GetAdminId() int32 {
	if x != nil && x.AdminId != nil {
		return *x.AdminId
	}
	return 0
}

type AddAdminGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       *int32                 `protobuf:"varint,1,opt,name=admin_id,json=adminId" json:"admin_id,omitempty"`
	GroupId       *int32                 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminGroupRequest) Reset() {
	*x = AddAdminGroupRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminGroupRequest) ProtoMessage() {}

func (x *AddAdminGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminGroupRequest.ProtoReflect.Descriptor instead.
func (*AddAdminGroupRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{21}
}

func (x *AddAdminGroupRequest) GetAdminId() int32 {
	if x != nil && x.AdminId != nil {
		return *x.AdminId
	}
	return 0
}

func (x *AddAdminGroupRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type AddAdminGroupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Admin         *Admin                 `protobuf:"bytes,1,opt,name=admin" json:"admin,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddAdminGroupResponse) Reset() {
	*x = AddAdminGroupResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddAdminGroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddAdminGroupResponse) ProtoMessage() {}

func (x *AddAdminGroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddAdminGroupResponse.ProtoReflect.Descriptor instead.
func (*AddAdminGroupResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{22}
}

func (x *AddAdminGroupResponse) GetAdmin() *Admin {
	if x != nil {
		return x.Admin
	}
	return nil
}

type DeleteAdminGroupRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       *int32                 `protobuf:"varint,1,opt,name=admin_id,json=adminId" json:"admin_id,omitempty"`
	GroupId       *int32                 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteAdminGroupRequest) Reset() {
	*x = DeleteAdminGroupRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteAdminGroupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAdminGroupRequest) ProtoMessage() {}

func (x *DeleteAdminGroupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAdminGroupRequest.ProtoReflect.Descriptor instead.
func (*DeleteAdminGroupRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{23}
}

func (x *DeleteAdminGroupRequest) GetAdminId() int32 {
	if x != nil && x.AdminId != nil {
		return *x.AdminId
	}
	return 0
}

func (x *DeleteAdminGroupRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

type OverridesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Overrides     []*Override            `protobuf:"bytes,1,rep,name=overrides" json:"overrides,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverridesResponse) Reset() {
	*x = OverridesResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverridesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverridesResponse) ProtoMessage() {}

func (x *OverridesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverridesResponse.ProtoReflect.Descriptor instead.
func (*OverridesResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{24}
}

func (x *OverridesResponse) GetOverrides() []*Override {
	if x != nil {
		return x.Overrides
	}
	return nil
}

type CreateOverridesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	OverrideType  *OverrideType          `protobuf:"varint,2,opt,name=override_type,json=overrideType,enum=sourcemod.v1.OverrideType" json:"override_type,omitempty"`
	Flags         *string                `protobuf:"bytes,3,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOverridesRequest) Reset() {
	*x = CreateOverridesRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOverridesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOverridesRequest) ProtoMessage() {}

func (x *CreateOverridesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOverridesRequest.ProtoReflect.Descriptor instead.
func (*CreateOverridesRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{25}
}

func (x *CreateOverridesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateOverridesRequest) GetOverrideType() OverrideType {
	if x != nil && x.OverrideType != nil {
		return *x.OverrideType
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *CreateOverridesRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

type CreateOverridesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Override      *Override              `protobuf:"bytes,1,opt,name=override" json:"override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOverridesResponse) Reset() {
	*x = CreateOverridesResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOverridesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOverridesResponse) ProtoMessage() {}

func (x *CreateOverridesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOverridesResponse.ProtoReflect.Descriptor instead.
func (*CreateOverridesResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{26}
}

func (x *CreateOverridesResponse) GetOverride() *Override {
	if x != nil {
		return x.Override
	}
	return nil
}

type EditOverridesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverrideId    *int32                 `protobuf:"varint,1,opt,name=override_id,json=overrideId" json:"override_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	OverrideType  *OverrideType          `protobuf:"varint,3,opt,name=override_type,json=overrideType,enum=sourcemod.v1.OverrideType" json:"override_type,omitempty"`
	Flags         *string                `protobuf:"bytes,4,opt,name=flags" json:"flags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditOverridesRequest) Reset() {
	*x = EditOverridesRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditOverridesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditOverridesRequest) ProtoMessage() {}

func (x *EditOverridesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditOverridesRequest.ProtoReflect.Descriptor instead.
func (*EditOverridesRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{27}
}

func (x *EditOverridesRequest) GetOverrideId() int32 {
	if x != nil && x.OverrideId != nil {
		return *x.OverrideId
	}
	return 0
}

func (x *EditOverridesRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *EditOverridesRequest) GetOverrideType() OverrideType {
	if x != nil && x.OverrideType != nil {
		return *x.OverrideType
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *EditOverridesRequest) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

type EditOverridesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Override      *Override              `protobuf:"bytes,1,opt,name=override" json:"override,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditOverridesResponse) Reset() {
	*x = EditOverridesResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditOverridesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditOverridesResponse) ProtoMessage() {}

func (x *EditOverridesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditOverridesResponse.ProtoReflect.Descriptor instead.
func (*EditOverridesResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{28}
}

func (x *EditOverridesResponse) GetOverride() *Override {
	if x != nil {
		return x.Override
	}
	return nil
}

type DeleteOverridesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverrideId    *int32                 `protobuf:"varint,1,opt,name=override_id,json=overrideId" json:"override_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteOverridesRequest) Reset() {
	*x = DeleteOverridesRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteOverridesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteOverridesRequest) ProtoMessage() {}

func (x *DeleteOverridesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteOverridesRequest.ProtoReflect.Descriptor instead.
func (*DeleteOverridesRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{29}
}

func (x *DeleteOverridesRequest) GetOverrideId() int32 {
	if x != nil && x.OverrideId != nil {
		return *x.OverrideId
	}
	return 0
}

type GroupImmunitiesResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupImmunities []*GroupImmunity       `protobuf:"bytes,1,rep,name=group_immunities,json=groupImmunities" json:"group_immunities,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupImmunitiesResponse) Reset() {
	*x = GroupImmunitiesResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupImmunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupImmunitiesResponse) ProtoMessage() {}

func (x *GroupImmunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupImmunitiesResponse.ProtoReflect.Descriptor instead.
func (*GroupImmunitiesResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{30}
}

func (x *GroupImmunitiesResponse) GetGroupImmunities() []*GroupImmunity {
	if x != nil {
		return x.GroupImmunities
	}
	return nil
}

type CreateImmunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       *int32                 `protobuf:"varint,1,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	OtherId       *int32                 `protobuf:"varint,2,opt,name=other_id,json=otherId" json:"other_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImmunityRequest) Reset() {
	*x = CreateImmunityRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImmunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImmunityRequest) ProtoMessage() {}

func (x *CreateImmunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImmunityRequest.ProtoReflect.Descriptor instead.
func (*CreateImmunityRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{31}
}

func (x *CreateImmunityRequest) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *CreateImmunityRequest) GetOtherId() int32 {
	if x != nil && x.OtherId != nil {
		return *x.OtherId
	}
	return 0
}

type CreateImmunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupImmunity *GroupImmunity         `protobuf:"bytes,1,opt,name=group_immunity,json=groupImmunity" json:"group_immunity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateImmunityResponse) Reset() {
	*x = CreateImmunityResponse{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateImmunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateImmunityResponse) ProtoMessage() {}

func (x *CreateImmunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateImmunityResponse.ProtoReflect.Descriptor instead.
func (*CreateImmunityResponse) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{32}
}

func (x *CreateImmunityResponse) GetGroupImmunity() *GroupImmunity {
	if x != nil {
		return x.GroupImmunity
	}
	return nil
}

type DeleteImmunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ImmunityId    *int32                 `protobuf:"varint,1,opt,name=immunity_id,json=immunityId" json:"immunity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteImmunityRequest) Reset() {
	*x = DeleteImmunityRequest{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteImmunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteImmunityRequest) ProtoMessage() {}

func (x *DeleteImmunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteImmunityRequest.ProtoReflect.Descriptor instead.
func (*DeleteImmunityRequest) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{33}
}

func (x *DeleteImmunityRequest) GetImmunityId() int32 {
	if x != nil && x.ImmunityId != nil {
		return *x.ImmunityId
	}
	return 0
}

type GroupImmunity struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupImmunityId *int32                 `protobuf:"varint,1,opt,name=group_immunity_id,json=groupImmunityId" json:"group_immunity_id,omitempty"`
	Group           *Group                 `protobuf:"bytes,2,opt,name=group" json:"group,omitempty"`
	Other           *Group                 `protobuf:"bytes,3,opt,name=other" json:"other,omitempty"`
	CreatedOn       *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupImmunity) Reset() {
	*x = GroupImmunity{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupImmunity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupImmunity) ProtoMessage() {}

func (x *GroupImmunity) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupImmunity.ProtoReflect.Descriptor instead.
func (*GroupImmunity) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{34}
}

func (x *GroupImmunity) GetGroupImmunityId() int32 {
	if x != nil && x.GroupImmunityId != nil {
		return *x.GroupImmunityId
	}
	return 0
}

func (x *GroupImmunity) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupImmunity) GetOther() *Group {
	if x != nil {
		return x.Other
	}
	return nil
}

func (x *GroupImmunity) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

type GroupOverrides struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	GroupOverrideId *int32                 `protobuf:"varint,1,opt,name=group_override_id,json=groupOverrideId" json:"group_override_id,omitempty"`
	GroupId         *int32                 `protobuf:"varint,2,opt,name=group_id,json=groupId" json:"group_id,omitempty"`
	OverrideType    *OverrideType          `protobuf:"varint,3,opt,name=override_type,json=overrideType,enum=sourcemod.v1.OverrideType" json:"override_type,omitempty"`
	Name            *string                `protobuf:"bytes,4,opt,name=name" json:"name,omitempty"`
	OverrideAccess  *OverrideAccess        `protobuf:"varint,5,opt,name=override_access,json=overrideAccess,enum=sourcemod.v1.OverrideAccess" json:"override_access,omitempty"`
	CreatedOn       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn       *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GroupOverrides) Reset() {
	*x = GroupOverrides{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupOverrides) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupOverrides) ProtoMessage() {}

func (x *GroupOverrides) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupOverrides.ProtoReflect.Descriptor instead.
func (*GroupOverrides) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{35}
}

func (x *GroupOverrides) GetGroupOverrideId() int32 {
	if x != nil && x.GroupOverrideId != nil {
		return *x.GroupOverrideId
	}
	return 0
}

func (x *GroupOverrides) GetGroupId() int32 {
	if x != nil && x.GroupId != nil {
		return *x.GroupId
	}
	return 0
}

func (x *GroupOverrides) GetOverrideType() OverrideType {
	if x != nil && x.OverrideType != nil {
		return *x.OverrideType
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *GroupOverrides) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *GroupOverrides) GetOverrideAccess() OverrideAccess {
	if x != nil && x.OverrideAccess != nil {
		return *x.OverrideAccess
	}
	return OverrideAccess_OVERRIDE_ACCESS_ALLOW_UNSPECIFIED
}

func (x *GroupOverrides) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *GroupOverrides) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

type Admin struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AdminId       *int32                 `protobuf:"varint,1,opt,name=admin_id,json=adminId" json:"admin_id,omitempty"`
	SteamId       *int64                 `protobuf:"varint,2,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	AuthType      *AuthType              `protobuf:"varint,3,opt,name=auth_type,json=authType,enum=sourcemod.v1.AuthType" json:"auth_type,omitempty"`
	Identity      *string                `protobuf:"bytes,4,opt,name=identity" json:"identity,omitempty"`
	Password      *string                `protobuf:"bytes,5,opt,name=password" json:"password,omitempty"`
	Flags         *string                `protobuf:"bytes,6,opt,name=flags" json:"flags,omitempty"`
	Name          *string                `protobuf:"bytes,7,opt,name=name" json:"name,omitempty"`
	Immunity      *int32                 `protobuf:"varint,8,opt,name=immunity" json:"immunity,omitempty"`
	Groups        []*Group               `protobuf:"bytes,9,rep,name=groups" json:"groups,omitempty"`
	CreatedOn     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Admin) Reset() {
	*x = Admin{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Admin) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Admin) ProtoMessage() {}

func (x *Admin) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Admin.ProtoReflect.Descriptor instead.
func (*Admin) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{36}
}

func (x *Admin) GetAdminId() int32 {
	if x != nil && x.AdminId != nil {
		return *x.AdminId
	}
	return 0
}

func (x *Admin) GetSteamId() int64 {
	if x != nil && x.SteamId != nil {
		return *x.SteamId
	}
	return 0
}

func (x *Admin) GetAuthType() AuthType {
	if x != nil && x.AuthType != nil {
		return *x.AuthType
	}
	return AuthType_AUTH_TYPE_STEAM_UNSPECIFIED
}

func (x *Admin) GetIdentity() string {
	if x != nil && x.Identity != nil {
		return *x.Identity
	}
	return ""
}

func (x *Admin) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Admin) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

func (x *Admin) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Admin) GetImmunity() int32 {
	if x != nil && x.Immunity != nil {
		return *x.Immunity
	}
	return 0
}

func (x *Admin) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *Admin) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Admin) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

type Override struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OverrideId    *int32                 `protobuf:"varint,1,opt,name=override_id,json=overrideId" json:"override_id,omitempty"`
	OverrideType  *OverrideType          `protobuf:"varint,2,opt,name=override_type,json=overrideType,enum=sourcemod.v1.OverrideType" json:"override_type,omitempty"`
	Name          *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Flags         *string                `protobuf:"bytes,4,opt,name=flags" json:"flags,omitempty"`
	CreatedOn     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Override) Reset() {
	*x = Override{}
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Override) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Override) ProtoMessage() {}

func (x *Override) ProtoReflect() protoreflect.Message {
	mi := &file_sourcemod_v1_sourcemod_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Override.ProtoReflect.Descriptor instead.
func (*Override) Descriptor() ([]byte, []int) {
	return file_sourcemod_v1_sourcemod_proto_rawDescGZIP(), []int{37}
}

func (x *Override) GetOverrideId() int32 {
	if x != nil && x.OverrideId != nil {
		return *x.OverrideId
	}
	return 0
}

func (x *Override) GetOverrideType() OverrideType {
	if x != nil && x.OverrideType != nil {
		return *x.OverrideType
	}
	return OverrideType_OVERRIDE_TYPE_COMMAND_UNSPECIFIED
}

func (x *Override) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Override) GetFlags() string {
	if x != nil && x.Flags != nil {
		return *x.Flags
	}
	return ""
}

func (x *Override) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Override) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

var File_sourcemod_v1_sourcemod_proto protoreflect.FileDescriptor

const file_sourcemod_v1_sourcemod_proto_rawDesc = "" +
	"\n" +
	"\x1csourcemod/v1/sourcemod.proto\x12\fsourcemod.v1\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x89\x02\n" +
	"\x05Group\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x12\x1c\n" +
	"\x05flags\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\x12\x1a\n" +
	"\x04name\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12-\n" +
	"\x0eimmunity_level\x18\x04 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\rimmunityLevel\x129\n" +
	"\n" +
	"created_on\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x129\n" +
	"\n" +
	"updated_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedOn\"E\n" +
	"\x0eGroupsResponse\x123\n" +
	"\x06groups\x18\x01 \x03(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x06groups\"u\n" +
	"\x12CreateGroupRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12%\n" +
	"\bimmunity\x18\x02 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bimmunity\x12\x1c\n" +
	"\x05flags\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\"H\n" +
	"\x13CreateGroupResponse\x121\n" +
	"\x05group\x18\x01 \x01(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x05group\"\x97\x01\n" +
	"\x11EditGroupsRequest\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12%\n" +
	"\bimmunity\x18\x03 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bimmunity\x12\x1c\n" +
	"\x05flags\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\"G\n" +
	"\x12EditGroupsResponse\x121\n" +
	"\x05group\x18\x01 \x01(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x05group\"7\n" +
	"\x12DeleteGroupRequest\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\":\n" +
	"\x15GroupOverridesRequest\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\"\\\n" +
	"\x16GroupOverridesResponse\x12B\n" +
	"\toverrides\x18\x01 \x03(\v2\x1c.sourcemod.v1.GroupOverridesB\x06\xbaH\x03\xc8\x01\x01R\toverrides\"\x85\x02\n" +
	"\x1aCreateGroupOverrideRequest\x122\n" +
	"\x11group_override_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x0fgroupOverrideId\x12!\n" +
	"\bgroup_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x126\n" +
	"\x04type\x18\x03 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\x04type\x12\x1a\n" +
	"\x04name\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12<\n" +
	"\x06access\x18\x05 \x01(\x0e2\x1c.sourcemod.v1.OverrideAccessB\x06\xbaH\x03\xc8\x01\x01R\x06access\"j\n" +
	"\x1bCreateGroupOverrideResponse\x12K\n" +
	"\x0egroup_override\x18\x01 \x01(\v2\x1c.sourcemod.v1.GroupOverridesB\x06\xbaH\x03\xc8\x01\x01R\rgroupOverride\"\xa5\x02\n" +
	"\x18EditGroupOverrideRequest\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x122\n" +
	"\x11group_override_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x0fgroupOverrideId\x12\x1a\n" +
	"\x04name\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12G\n" +
	"\roverride_type\x18\x04 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\foverrideType\x12M\n" +
	"\x0foverride_access\x18\x05 \x01(\x0e2\x1c.sourcemod.v1.OverrideAccessB\x06\xbaH\x03\xc8\x01\x01R\x0eoverrideAccess\"h\n" +
	"\x19EditGroupOverrideResponse\x12K\n" +
	"\x0egroup_override\x18\x01 \x01(\v2\x1c.sourcemod.v1.GroupOverridesB\x06\xbaH\x03\xc8\x01\x01R\rgroupOverride\"P\n" +
	"\x1aDeleteGroupOverrideRequest\x122\n" +
	"\x11group_override_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x0fgroupOverrideId\"\x1d\n" +
	"\x1bDeleteGroupOverrideResponse\"E\n" +
	"\x0eAdminsResponse\x123\n" +
	"\x06admins\x18\x01 \x03(\v2\x13.sourcemod.v1.AdminB\x06\xbaH\x03\xc8\x01\x01R\x06admins\"\xf5\x01\n" +
	"\x12CreateAdminRequest\x12;\n" +
	"\tauth_type\x18\x01 \x01(\x0e2\x16.sourcemod.v1.AuthTypeB\x06\xbaH\x03\xc8\x01\x01R\bauthType\x12\"\n" +
	"\bidentity\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bidentity\x12\x1a\n" +
	"\bpassword\x18\x03 \x01(\tR\bpassword\x12\x1c\n" +
	"\x05flags\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\x12\x1a\n" +
	"\x04name\x18\x05 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12(\n" +
	"\bimmunity\x18\x06 \x01(\x05B\f\xbaH\t\xc8\x01\x01\x1a\x04\x18d(\x00R\bimmunity\"H\n" +
	"\x13CreateAdminResponse\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x13.sourcemod.v1.AdminB\x06\xbaH\x03\xc8\x01\x01R\x05admin\"\x96\x02\n" +
	"\x10EditAdminRequest\x12!\n" +
	"\badmin_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aadminId\x12;\n" +
	"\tauth_type\x18\x02 \x01(\x0e2\x16.sourcemod.v1.AuthTypeB\x06\xbaH\x03\xc8\x01\x01R\bauthType\x12\"\n" +
	"\bidentity\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bidentity\x12\x1a\n" +
	"\bpassword\x18\x04 \x01(\tR\bpassword\x12\x1c\n" +
	"\x05flags\x18\x05 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\x12\x1a\n" +
	"\x04name\x18\x06 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12(\n" +
	"\bimmunity\x18\a \x01(\x05B\f\xbaH\t\xc8\x01\x01\x1a\x04\x18d(\x00R\bimmunity\"F\n" +
	"\x11EditAdminResponse\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x13.sourcemod.v1.AdminB\x06\xbaH\x03\xc8\x01\x01R\x05admin\"7\n" +
	"\x12DeleteAdminRequest\x12!\n" +
	"\badmin_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aadminId\"\\\n" +
	"\x14AddAdminGroupRequest\x12!\n" +
	"\badmin_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aadminId\x12!\n" +
	"\bgroup_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\"J\n" +
	"\x15AddAdminGroupResponse\x121\n" +
	"\x05admin\x18\x01 \x01(\v2\x13.sourcemod.v1.AdminB\x06\xbaH\x03\xc8\x01\x01R\x05admin\"_\n" +
	"\x17DeleteAdminGroupRequest\x12!\n" +
	"\badmin_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aadminId\x12!\n" +
	"\bgroup_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\"Q\n" +
	"\x11OverridesResponse\x12<\n" +
	"\toverrides\x18\x01 \x03(\v2\x16.sourcemod.v1.OverrideB\x06\xbaH\x03\xc8\x01\x01R\toverrides\"\x9b\x01\n" +
	"\x16CreateOverridesRequest\x12\x1a\n" +
	"\x04name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12G\n" +
	"\roverride_type\x18\x02 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\foverrideType\x12\x1c\n" +
	"\x05flags\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\"U\n" +
	"\x17CreateOverridesResponse\x12:\n" +
	"\boverride\x18\x01 \x01(\v2\x16.sourcemod.v1.OverrideB\x06\xbaH\x03\xc8\x01\x01R\boverride\"\xc2\x01\n" +
	"\x14EditOverridesRequest\x12'\n" +
	"\voverride_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"overrideId\x12\x1a\n" +
	"\x04name\x18\x02 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12G\n" +
	"\roverride_type\x18\x03 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\foverrideType\x12\x1c\n" +
	"\x05flags\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\"S\n" +
	"\x15EditOverridesResponse\x12:\n" +
	"\boverride\x18\x01 \x01(\v2\x16.sourcemod.v1.OverrideB\x06\xbaH\x03\xc8\x01\x01R\boverride\"A\n" +
	"\x16DeleteOverridesRequest\x12'\n" +
	"\voverride_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"overrideId\"i\n" +
	"\x17GroupImmunitiesResponse\x12N\n" +
	"\x10group_immunities\x18\x01 \x03(\v2\x1b.sourcemod.v1.GroupImmunityB\x06\xbaH\x03\xc8\x01\x01R\x0fgroupImmunities\"]\n" +
	"\x15CreateImmunityRequest\x12!\n" +
	"\bgroup_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x12!\n" +
	"\bother_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aotherId\"d\n" +
	"\x16CreateImmunityResponse\x12J\n" +
	"\x0egroup_immunity\x18\x01 \x01(\v2\x1b.sourcemod.v1.GroupImmunityB\x06\xbaH\x03\xc8\x01\x01R\rgroupImmunity\"@\n" +
	"\x15DeleteImmunityRequest\x12'\n" +
	"\vimmunity_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"immunityId\"\xec\x01\n" +
	"\rGroupImmunity\x122\n" +
	"\x11group_immunity_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x0fgroupImmunityId\x121\n" +
	"\x05group\x18\x02 \x01(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x05group\x121\n" +
	"\x05other\x18\x03 \x01(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x05other\x12A\n" +
	"\n" +
	"created_on\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedOn\"\xa1\x03\n" +
	"\x0eGroupOverrides\x122\n" +
	"\x11group_override_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\x0fgroupOverrideId\x12!\n" +
	"\bgroup_id\x18\x02 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\agroupId\x12G\n" +
	"\roverride_type\x18\x03 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\foverrideType\x12\x1a\n" +
	"\x04name\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12M\n" +
	"\x0foverride_access\x18\x05 \x01(\x0e2\x1c.sourcemod.v1.OverrideAccessB\x06\xbaH\x03\xc8\x01\x01R\x0eoverrideAccess\x12A\n" +
	"\n" +
	"created_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedOn\x12A\n" +
	"\n" +
	"updated_on\x18\a \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedOn\"\xee\x03\n" +
	"\x05Admin\x12!\n" +
	"\badmin_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\aadminId\x12!\n" +
	"\bsteam_id\x18\x02 \x01(\x03B\x06\xbaH\x03\xc8\x01\x01R\asteamId\x12;\n" +
	"\tauth_type\x18\x03 \x01(\x0e2\x16.sourcemod.v1.AuthTypeB\x06\xbaH\x03\xc8\x01\x01R\bauthType\x12\"\n" +
	"\bidentity\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bidentity\x12\"\n" +
	"\bpassword\x18\x05 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\bpassword\x12\x1c\n" +
	"\x05flags\x18\x06 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\x12\x1a\n" +
	"\x04name\x18\a \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12%\n" +
	"\bimmunity\x18\b \x01(\x05B\t\xbaH\x06\x1a\x04\x18d(\x00R\bimmunity\x123\n" +
	"\x06groups\x18\t \x03(\v2\x13.sourcemod.v1.GroupB\x06\xbaH\x03\xc8\x01\x01R\x06groups\x12A\n" +
	"\n" +
	"created_on\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedOn\x12A\n" +
	"\n" +
	"updated_on\x18\v \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedOn\"\xbc\x02\n" +
	"\bOverride\x12'\n" +
	"\voverride_id\x18\x01 \x01(\x05B\x06\xbaH\x03\xc8\x01\x01R\n" +
	"overrideId\x12G\n" +
	"\roverride_type\x18\x02 \x01(\x0e2\x1a.sourcemod.v1.OverrideTypeB\x06\xbaH\x03\xc8\x01\x01R\foverrideType\x12\x1a\n" +
	"\x04name\x18\x03 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x04name\x12\x1c\n" +
	"\x05flags\x18\x04 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x05flags\x12A\n" +
	"\n" +
	"created_on\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tcreatedOn\x12A\n" +
	"\n" +
	"updated_on\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampB\x06\xbaH\x03\xc8\x01\x01R\tupdatedOn*N\n" +
	"\fOverrideType\x12%\n" +
	"!OVERRIDE_TYPE_COMMAND_UNSPECIFIED\x10\x00\x12\x17\n" +
	"\x13OVERRIDE_TYPE_GROUP\x10\x01*Q\n" +
	"\x0eOverrideAccess\x12%\n" +
	"!OVERRIDE_ACCESS_ALLOW_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14OVERRIDE_ACCESS_DENY\x10\x01*Q\n" +
	"\bAuthType\x12\x1f\n" +
	"\x1bAUTH_TYPE_STEAM_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eAUTH_TYPE_NAME\x10\x01\x12\x10\n" +
	"\fAUTH_TYPE_IP\x10\x022\x99\x0e\n" +
	"\x10SourcemodService\x12@\n" +
	"\x06Groups\x12\x16.google.protobuf.Empty\x1a\x1c.sourcemod.v1.GroupsResponse\"\x00\x12T\n" +
	"\vCreateGroup\x12 .sourcemod.v1.CreateGroupRequest\x1a!.sourcemod.v1.CreateGroupResponse\"\x00\x12Q\n" +
	"\n" +
	"EditGroups\x12\x1f.sourcemod.v1.EditGroupsRequest\x1a .sourcemod.v1.EditGroupsResponse\"\x00\x12I\n" +
	"\vDeleteGroup\x12 .sourcemod.v1.DeleteGroupRequest\x1a\x16.google.protobuf.Empty\"\x00\x12]\n" +
	"\x0eGroupOverrides\x12#.sourcemod.v1.GroupOverridesRequest\x1a$.sourcemod.v1.GroupOverridesResponse\"\x00\x12l\n" +
	"\x13CreateGroupOverride\x12(.sourcemod.v1.CreateGroupOverrideRequest\x1a).sourcemod.v1.CreateGroupOverrideResponse\"\x00\x12f\n" +
	"\x11EditGroupOverride\x12&.sourcemod.v1.EditGroupOverrideRequest\x1a'.sourcemod.v1.EditGroupOverrideResponse\"\x00\x12Y\n" +
	"\x13DeleteGroupOverride\x12(.sourcemod.v1.DeleteGroupOverrideRequest\x1a\x16.google.protobuf.Empty\"\x00\x12@\n" +
	"\x06Admins\x12\x16.google.protobuf.Empty\x1a\x1c.sourcemod.v1.AdminsResponse\"\x00\x12T\n" +
	"\vCreateAdmin\x12 .sourcemod.v1.CreateAdminRequest\x1a!.sourcemod.v1.CreateAdminResponse\"\x00\x12N\n" +
	"\tEditAdmin\x12\x1e.sourcemod.v1.EditAdminRequest\x1a\x1f.sourcemod.v1.EditAdminResponse\"\x00\x12I\n" +
	"\vDeleteAdmin\x12 .sourcemod.v1.DeleteAdminRequest\x1a\x16.google.protobuf.Empty\"\x00\x12Z\n" +
	"\rAddAdminGroup\x12\".sourcemod.v1.AddAdminGroupRequest\x1a#.sourcemod.v1.AddAdminGroupResponse\"\x00\x12S\n" +
	"\x10DeleteAdminGroup\x12%.sourcemod.v1.DeleteAdminGroupRequest\x1a\x16.google.protobuf.Empty\"\x00\x12F\n" +
	"\tOverrides\x12\x16.google.protobuf.Empty\x1a\x1f.sourcemod.v1.OverridesResponse\"\x00\x12`\n" +
	"\x0fCreateOverrides\x12$.sourcemod.v1.CreateOverridesRequest\x1a%.sourcemod.v1.CreateOverridesResponse\"\x00\x12Z\n" +
	"\rEditOverrides\x12\".sourcemod.v1.EditOverridesRequest\x1a#.sourcemod.v1.EditOverridesResponse\"\x00\x12Q\n" +
	"\x0fDeleteOverrides\x12$.sourcemod.v1.DeleteOverridesRequest\x1a\x16.google.protobuf.Empty\"\x00\x12R\n" +
	"\x0fGroupImmunities\x12\x16.google.protobuf.Empty\x1a%.sourcemod.v1.GroupImmunitiesResponse\"\x00\x12]\n" +
	"\x0eCreateImmunity\x12#.sourcemod.v1.CreateImmunityRequest\x1a$.sourcemod.v1.CreateImmunityResponse\"\x00\x12O\n" +
	"\x0eDeleteImmunity\x12#.sourcemod.v1.DeleteImmunityRequest\x1a\x16.google.protobuf.Empty\"\x00B\xb6\x01\n" +
	"\x10com.sourcemod.v1B\x0eSourcemodProtoP\x01ZAgithub.com/leighmacdonald/gbans/internal/sourcemod/v1;sourcemodv1\xa2\x02\x03SXX\xaa\x02\fSourcemod.V1\xca\x02\fSourcemod\\V1\xe2\x02\x18Sourcemod\\V1\\GPBMetadata\xea\x02\rSourcemod::V1b\beditionsp\xe8\a"

var (
	file_sourcemod_v1_sourcemod_proto_rawDescOnce sync.Once
	file_sourcemod_v1_sourcemod_proto_rawDescData []byte
)

func file_sourcemod_v1_sourcemod_proto_rawDescGZIP() []byte {
	file_sourcemod_v1_sourcemod_proto_rawDescOnce.Do(func() {
		file_sourcemod_v1_sourcemod_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_sourcemod_v1_sourcemod_proto_rawDesc), len(file_sourcemod_v1_sourcemod_proto_rawDesc)))
	})
	return file_sourcemod_v1_sourcemod_proto_rawDescData
}

var file_sourcemod_v1_sourcemod_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_sourcemod_v1_sourcemod_proto_msgTypes = make([]protoimpl.MessageInfo, 38)
var file_sourcemod_v1_sourcemod_proto_goTypes = []any{
	(OverrideType)(0),                   // 0: sourcemod.v1.OverrideType
	(OverrideAccess)(0),                 // 1: sourcemod.v1.OverrideAccess
	(AuthType)(0),                       // 2: sourcemod.v1.AuthType
	(*Group)(nil),                       // 3: sourcemod.v1.Group
	(*GroupsResponse)(nil),              // 4: sourcemod.v1.GroupsResponse
	(*CreateGroupRequest)(nil),          // 5: sourcemod.v1.CreateGroupRequest
	(*CreateGroupResponse)(nil),         // 6: sourcemod.v1.CreateGroupResponse
	(*EditGroupsRequest)(nil),           // 7: sourcemod.v1.EditGroupsRequest
	(*EditGroupsResponse)(nil),          // 8: sourcemod.v1.EditGroupsResponse
	(*DeleteGroupRequest)(nil),          // 9: sourcemod.v1.DeleteGroupRequest
	(*GroupOverridesRequest)(nil),       // 10: sourcemod.v1.GroupOverridesRequest
	(*GroupOverridesResponse)(nil),      // 11: sourcemod.v1.GroupOverridesResponse
	(*CreateGroupOverrideRequest)(nil),  // 12: sourcemod.v1.CreateGroupOverrideRequest
	(*CreateGroupOverrideResponse)(nil), // 13: sourcemod.v1.CreateGroupOverrideResponse
	(*EditGroupOverrideRequest)(nil),    // 14: sourcemod.v1.EditGroupOverrideRequest
	(*EditGroupOverrideResponse)(nil),   // 15: sourcemod.v1.EditGroupOverrideResponse
	(*DeleteGroupOverrideRequest)(nil),  // 16: sourcemod.v1.DeleteGroupOverrideRequest
	(*DeleteGroupOverrideResponse)(nil), // 17: sourcemod.v1.DeleteGroupOverrideResponse
	(*AdminsResponse)(nil),              // 18: sourcemod.v1.AdminsResponse
	(*CreateAdminRequest)(nil),          // 19: sourcemod.v1.CreateAdminRequest
	(*CreateAdminResponse)(nil),         // 20: sourcemod.v1.CreateAdminResponse
	(*EditAdminRequest)(nil),            // 21: sourcemod.v1.EditAdminRequest
	(*EditAdminResponse)(nil),           // 22: sourcemod.v1.EditAdminResponse
	(*DeleteAdminRequest)(nil),          // 23: sourcemod.v1.DeleteAdminRequest
	(*AddAdminGroupRequest)(nil),        // 24: sourcemod.v1.AddAdminGroupRequest
	(*AddAdminGroupResponse)(nil),       // 25: sourcemod.v1.AddAdminGroupResponse
	(*DeleteAdminGroupRequest)(nil),     // 26: sourcemod.v1.DeleteAdminGroupRequest
	(*OverridesResponse)(nil),           // 27: sourcemod.v1.OverridesResponse
	(*CreateOverridesRequest)(nil),      // 28: sourcemod.v1.CreateOverridesRequest
	(*CreateOverridesResponse)(nil),     // 29: sourcemod.v1.CreateOverridesResponse
	(*EditOverridesRequest)(nil),        // 30: sourcemod.v1.EditOverridesRequest
	(*EditOverridesResponse)(nil),       // 31: sourcemod.v1.EditOverridesResponse
	(*DeleteOverridesRequest)(nil),      // 32: sourcemod.v1.DeleteOverridesRequest
	(*GroupImmunitiesResponse)(nil),     // 33: sourcemod.v1.GroupImmunitiesResponse
	(*CreateImmunityRequest)(nil),       // 34: sourcemod.v1.CreateImmunityRequest
	(*CreateImmunityResponse)(nil),      // 35: sourcemod.v1.CreateImmunityResponse
	(*DeleteImmunityRequest)(nil),       // 36: sourcemod.v1.DeleteImmunityRequest
	(*GroupImmunity)(nil),               // 37: sourcemod.v1.GroupImmunity
	(*GroupOverrides)(nil),              // 38: sourcemod.v1.GroupOverrides
	(*Admin)(nil),                       // 39: sourcemod.v1.Admin
	(*Override)(nil),                    // 40: sourcemod.v1.Override
	(*timestamppb.Timestamp)(nil),       // 41: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 42: google.protobuf.Empty
}
var file_sourcemod_v1_sourcemod_proto_depIdxs = []int32{
	41, // 0: sourcemod.v1.Group.created_on:type_name -> google.protobuf.Timestamp
	41, // 1: sourcemod.v1.Group.updated_on:type_name -> google.protobuf.Timestamp
	3,  // 2: sourcemod.v1.GroupsResponse.groups:type_name -> sourcemod.v1.Group
	3,  // 3: sourcemod.v1.CreateGroupResponse.group:type_name -> sourcemod.v1.Group
	3,  // 4: sourcemod.v1.EditGroupsResponse.group:type_name -> sourcemod.v1.Group
	38, // 5: sourcemod.v1.GroupOverridesResponse.overrides:type_name -> sourcemod.v1.GroupOverrides
	0,  // 6: sourcemod.v1.CreateGroupOverrideRequest.type:type_name -> sourcemod.v1.OverrideType
	1,  // 7: sourcemod.v1.CreateGroupOverrideRequest.access:type_name -> sourcemod.v1.OverrideAccess
	38, // 8: sourcemod.v1.CreateGroupOverrideResponse.group_override:type_name -> sourcemod.v1.GroupOverrides
	0,  // 9: sourcemod.v1.EditGroupOverrideRequest.override_type:type_name -> sourcemod.v1.OverrideType
	1,  // 10: sourcemod.v1.EditGroupOverrideRequest.override_access:type_name -> sourcemod.v1.OverrideAccess
	38, // 11: sourcemod.v1.EditGroupOverrideResponse.group_override:type_name -> sourcemod.v1.GroupOverrides
	39, // 12: sourcemod.v1.AdminsResponse.admins:type_name -> sourcemod.v1.Admin
	2,  // 13: sourcemod.v1.CreateAdminRequest.auth_type:type_name -> sourcemod.v1.AuthType
	39, // 14: sourcemod.v1.CreateAdminResponse.admin:type_name -> sourcemod.v1.Admin
	2,  // 15: sourcemod.v1.EditAdminRequest.auth_type:type_name -> sourcemod.v1.AuthType
	39, // 16: sourcemod.v1.EditAdminResponse.admin:type_name -> sourcemod.v1.Admin
	39, // 17: sourcemod.v1.AddAdminGroupResponse.admin:type_name -> sourcemod.v1.Admin
	40, // 18: sourcemod.v1.OverridesResponse.overrides:type_name -> sourcemod.v1.Override
	0,  // 19: sourcemod.v1.CreateOverridesRequest.override_type:type_name -> sourcemod.v1.OverrideType
	40, // 20: sourcemod.v1.CreateOverridesResponse.override:type_name -> sourcemod.v1.Override
	0,  // 21: sourcemod.v1.EditOverridesRequest.override_type:type_name -> sourcemod.v1.OverrideType
	40, // 22: sourcemod.v1.EditOverridesResponse.override:type_name -> sourcemod.v1.Override
	37, // 23: sourcemod.v1.GroupImmunitiesResponse.group_immunities:type_name -> sourcemod.v1.GroupImmunity
	37, // 24: sourcemod.v1.CreateImmunityResponse.group_immunity:type_name -> sourcemod.v1.GroupImmunity
	3,  // 25: sourcemod.v1.GroupImmunity.group:type_name -> sourcemod.v1.Group
	3,  // 26: sourcemod.v1.GroupImmunity.other:type_name -> sourcemod.v1.Group
	41, // 27: sourcemod.v1.GroupImmunity.created_on:type_name -> google.protobuf.Timestamp
	0,  // 28: sourcemod.v1.GroupOverrides.override_type:type_name -> sourcemod.v1.OverrideType
	1,  // 29: sourcemod.v1.GroupOverrides.override_access:type_name -> sourcemod.v1.OverrideAccess
	41, // 30: sourcemod.v1.GroupOverrides.created_on:type_name -> google.protobuf.Timestamp
	41, // 31: sourcemod.v1.GroupOverrides.updated_on:type_name -> google.protobuf.Timestamp
	2,  // 32: sourcemod.v1.Admin.auth_type:type_name -> sourcemod.v1.AuthType
	3,  // 33: sourcemod.v1.Admin.groups:type_name -> sourcemod.v1.Group
	41, // 34: sourcemod.v1.Admin.created_on:type_name -> google.protobuf.Timestamp
	41, // 35: sourcemod.v1.Admin.updated_on:type_name -> google.protobuf.Timestamp
	0,  // 36: sourcemod.v1.Override.override_type:type_name -> sourcemod.v1.OverrideType
	41, // 37: sourcemod.v1.Override.created_on:type_name -> google.protobuf.Timestamp
	41, // 38: sourcemod.v1.Override.updated_on:type_name -> google.protobuf.Timestamp
	42, // 39: sourcemod.v1.SourcemodService.Groups:input_type -> google.protobuf.Empty
	5,  // 40: sourcemod.v1.SourcemodService.CreateGroup:input_type -> sourcemod.v1.CreateGroupRequest
	7,  // 41: sourcemod.v1.SourcemodService.EditGroups:input_type -> sourcemod.v1.EditGroupsRequest
	9,  // 42: sourcemod.v1.SourcemodService.DeleteGroup:input_type -> sourcemod.v1.DeleteGroupRequest
	10, // 43: sourcemod.v1.SourcemodService.GroupOverrides:input_type -> sourcemod.v1.GroupOverridesRequest
	12, // 44: sourcemod.v1.SourcemodService.CreateGroupOverride:input_type -> sourcemod.v1.CreateGroupOverrideRequest
	14, // 45: sourcemod.v1.SourcemodService.EditGroupOverride:input_type -> sourcemod.v1.EditGroupOverrideRequest
	16, // 46: sourcemod.v1.SourcemodService.DeleteGroupOverride:input_type -> sourcemod.v1.DeleteGroupOverrideRequest
	42, // 47: sourcemod.v1.SourcemodService.Admins:input_type -> google.protobuf.Empty
	19, // 48: sourcemod.v1.SourcemodService.CreateAdmin:input_type -> sourcemod.v1.CreateAdminRequest
	21, // 49: sourcemod.v1.SourcemodService.EditAdmin:input_type -> sourcemod.v1.EditAdminRequest
	23, // 50: sourcemod.v1.SourcemodService.DeleteAdmin:input_type -> sourcemod.v1.DeleteAdminRequest
	24, // 51: sourcemod.v1.SourcemodService.AddAdminGroup:input_type -> sourcemod.v1.AddAdminGroupRequest
	26, // 52: sourcemod.v1.SourcemodService.DeleteAdminGroup:input_type -> sourcemod.v1.DeleteAdminGroupRequest
	42, // 53: sourcemod.v1.SourcemodService.Overrides:input_type -> google.protobuf.Empty
	28, // 54: sourcemod.v1.SourcemodService.CreateOverrides:input_type -> sourcemod.v1.CreateOverridesRequest
	30, // 55: sourcemod.v1.SourcemodService.EditOverrides:input_type -> sourcemod.v1.EditOverridesRequest
	32, // 56: sourcemod.v1.SourcemodService.DeleteOverrides:input_type -> sourcemod.v1.DeleteOverridesRequest
	42, // 57: sourcemod.v1.SourcemodService.GroupImmunities:input_type -> google.protobuf.Empty
	34, // 58: sourcemod.v1.SourcemodService.CreateImmunity:input_type -> sourcemod.v1.CreateImmunityRequest
	36, // 59: sourcemod.v1.SourcemodService.DeleteImmunity:input_type -> sourcemod.v1.DeleteImmunityRequest
	4,  // 60: sourcemod.v1.SourcemodService.Groups:output_type -> sourcemod.v1.GroupsResponse
	6,  // 61: sourcemod.v1.SourcemodService.CreateGroup:output_type -> sourcemod.v1.CreateGroupResponse
	8,  // 62: sourcemod.v1.SourcemodService.EditGroups:output_type -> sourcemod.v1.EditGroupsResponse
	42, // 63: sourcemod.v1.SourcemodService.DeleteGroup:output_type -> google.protobuf.Empty
	11, // 64: sourcemod.v1.SourcemodService.GroupOverrides:output_type -> sourcemod.v1.GroupOverridesResponse
	13, // 65: sourcemod.v1.SourcemodService.CreateGroupOverride:output_type -> sourcemod.v1.CreateGroupOverrideResponse
	15, // 66: sourcemod.v1.SourcemodService.EditGroupOverride:output_type -> sourcemod.v1.EditGroupOverrideResponse
	42, // 67: sourcemod.v1.SourcemodService.DeleteGroupOverride:output_type -> google.protobuf.Empty
	18, // 68: sourcemod.v1.SourcemodService.Admins:output_type -> sourcemod.v1.AdminsResponse
	20, // 69: sourcemod.v1.SourcemodService.CreateAdmin:output_type -> sourcemod.v1.CreateAdminResponse
	22, // 70: sourcemod.v1.SourcemodService.EditAdmin:output_type -> sourcemod.v1.EditAdminResponse
	42, // 71: sourcemod.v1.SourcemodService.DeleteAdmin:output_type -> google.protobuf.Empty
	25, // 72: sourcemod.v1.SourcemodService.AddAdminGroup:output_type -> sourcemod.v1.AddAdminGroupResponse
	42, // 73: sourcemod.v1.SourcemodService.DeleteAdminGroup:output_type -> google.protobuf.Empty
	27, // 74: sourcemod.v1.SourcemodService.Overrides:output_type -> sourcemod.v1.OverridesResponse
	29, // 75: sourcemod.v1.SourcemodService.CreateOverrides:output_type -> sourcemod.v1.CreateOverridesResponse
	31, // 76: sourcemod.v1.SourcemodService.EditOverrides:output_type -> sourcemod.v1.EditOverridesResponse
	42, // 77: sourcemod.v1.SourcemodService.DeleteOverrides:output_type -> google.protobuf.Empty
	33, // 78: sourcemod.v1.SourcemodService.GroupImmunities:output_type -> sourcemod.v1.GroupImmunitiesResponse
	35, // 79: sourcemod.v1.SourcemodService.CreateImmunity:output_type -> sourcemod.v1.CreateImmunityResponse
	42, // 80: sourcemod.v1.SourcemodService.DeleteImmunity:output_type -> google.protobuf.Empty
	60, // [60:81] is the sub-list for method output_type
	39, // [39:60] is the sub-list for method input_type
	39, // [39:39] is the sub-list for extension type_name
	39, // [39:39] is the sub-list for extension extendee
	0,  // [0:39] is the sub-list for field type_name
}

func init() { file_sourcemod_v1_sourcemod_proto_init() }
func file_sourcemod_v1_sourcemod_proto_init() {
	if File_sourcemod_v1_sourcemod_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_sourcemod_v1_sourcemod_proto_rawDesc), len(file_sourcemod_v1_sourcemod_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   38,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_sourcemod_v1_sourcemod_proto_goTypes,
		DependencyIndexes: file_sourcemod_v1_sourcemod_proto_depIdxs,
		EnumInfos:         file_sourcemod_v1_sourcemod_proto_enumTypes,
		MessageInfos:      file_sourcemod_v1_sourcemod_proto_msgTypes,
	}.Build()
	File_sourcemod_v1_sourcemod_proto = out.File
	file_sourcemod_v1_sourcemod_proto_goTypes = nil
	file_sourcemod_v1_sourcemod_proto_depIdxs = nil
}
