// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: network/v1/network.proto

package networkv1

import (
	internal "github.com/leighmacdonald/gbans/internal"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ThreatType int32

const (
	ThreatType_THREAT_TYPE_UNSPECIFIED         ThreatType = 0
	ThreatType_THREAT_TYPE_SPAM                ThreatType = 1
	ThreatType_THREAT_TYPE_BOTNET              ThreatType = 2
	ThreatType_THREAT_TYPE_SCANNER             ThreatType = 3
	ThreatType_THREAT_TYPE_SPAM_BOTNET         ThreatType = 4
	ThreatType_THREAT_TYPE_SPAM_SCANNER        ThreatType = 5
	ThreatType_THREAT_TYPE_SPAM_SCANNER_BOTNET ThreatType = 6
)

// Enum value maps for ThreatType.
var (
	ThreatType_name = map[int32]string{
		0: "THREAT_TYPE_UNSPECIFIED",
		1: "THREAT_TYPE_SPAM",
		2: "THREAT_TYPE_BOTNET",
		3: "THREAT_TYPE_SCANNER",
		4: "THREAT_TYPE_SPAM_BOTNET",
		5: "THREAT_TYPE_SPAM_SCANNER",
		6: "THREAT_TYPE_SPAM_SCANNER_BOTNET",
	}
	ThreatType_value = map[string]int32{
		"THREAT_TYPE_UNSPECIFIED":         0,
		"THREAT_TYPE_SPAM":                1,
		"THREAT_TYPE_BOTNET":              2,
		"THREAT_TYPE_SCANNER":             3,
		"THREAT_TYPE_SPAM_BOTNET":         4,
		"THREAT_TYPE_SPAM_SCANNER":        5,
		"THREAT_TYPE_SPAM_SCANNER_BOTNET": 6,
	}
)

func (x ThreatType) Enum() *ThreatType {
	p := new(ThreatType)
	*p = x
	return p
}

func (x ThreatType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ThreatType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[0].Descriptor()
}

func (ThreatType) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[0]
}

func (x ThreatType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ThreatType.Descriptor instead.
func (ThreatType) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

type UsageType int32

const (
	UsageType_USAGE_TYPE_UNSPECIFIED      UsageType = 0
	UsageType_USAGE_TYPE_CDN              UsageType = 1
	UsageType_USAGE_TYPE_ISP_FIXED_MOBILE UsageType = 2
	UsageType_USAGE_TYPE_COMMERCIAL       UsageType = 3
	UsageType_USAGE_TYPE_ISP_MOBILE       UsageType = 4
	UsageType_USAGE_TYPE_LIBRARY          UsageType = 5
	UsageType_USAGE_TYPE_DATA_CENTER      UsageType = 6
	UsageType_USAGE_TYPE_MILITARY         UsageType = 7
	UsageType_USAGE_TYPE_GOVERNMENT       UsageType = 8
	UsageType_USAGE_TYPE_ISP_FIXED        UsageType = 9
	UsageType_USAGE_TYPE_ORGANIZATION     UsageType = 10
	UsageType_USAGE_TYPE_EDUCATION        UsageType = 11
)

// Enum value maps for UsageType.
var (
	UsageType_name = map[int32]string{
		0:  "USAGE_TYPE_UNSPECIFIED",
		1:  "USAGE_TYPE_CDN",
		2:  "USAGE_TYPE_ISP_FIXED_MOBILE",
		3:  "USAGE_TYPE_COMMERCIAL",
		4:  "USAGE_TYPE_ISP_MOBILE",
		5:  "USAGE_TYPE_LIBRARY",
		6:  "USAGE_TYPE_DATA_CENTER",
		7:  "USAGE_TYPE_MILITARY",
		8:  "USAGE_TYPE_GOVERNMENT",
		9:  "USAGE_TYPE_ISP_FIXED",
		10: "USAGE_TYPE_ORGANIZATION",
		11: "USAGE_TYPE_EDUCATION",
	}
	UsageType_value = map[string]int32{
		"USAGE_TYPE_UNSPECIFIED":      0,
		"USAGE_TYPE_CDN":              1,
		"USAGE_TYPE_ISP_FIXED_MOBILE": 2,
		"USAGE_TYPE_COMMERCIAL":       3,
		"USAGE_TYPE_ISP_MOBILE":       4,
		"USAGE_TYPE_LIBRARY":          5,
		"USAGE_TYPE_DATA_CENTER":      6,
		"USAGE_TYPE_MILITARY":         7,
		"USAGE_TYPE_GOVERNMENT":       8,
		"USAGE_TYPE_ISP_FIXED":        9,
		"USAGE_TYPE_ORGANIZATION":     10,
		"USAGE_TYPE_EDUCATION":        11,
	}
)

func (x UsageType) Enum() *UsageType {
	p := new(UsageType)
	*p = x
	return p
}

func (x UsageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UsageType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[1].Descriptor()
}

func (UsageType) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[1]
}

func (x UsageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UsageType.Descriptor instead.
func (UsageType) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

type ProxyType int32

const (
	ProxyType_PROXY_TYPE_PUB_UNSPECIFIED ProxyType = 0
)

// Enum value maps for ProxyType.
var (
	ProxyType_name = map[int32]string{
		0: "PROXY_TYPE_PUB_UNSPECIFIED",
	}
	ProxyType_value = map[string]int32{
		"PROXY_TYPE_PUB_UNSPECIFIED": 0,
	}
)

func (x ProxyType) Enum() *ProxyType {
	p := new(ProxyType)
	*p = x
	return p
}

func (x ProxyType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ProxyType) Descriptor() protoreflect.EnumDescriptor {
	return file_network_v1_network_proto_enumTypes[2].Descriptor()
}

func (ProxyType) Type() protoreflect.EnumType {
	return &file_network_v1_network_proto_enumTypes[2]
}

func (x ProxyType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ProxyType.Descriptor instead.
func (ProxyType) EnumDescriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{2}
}

type QueryNetworkRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *internal.Filter       `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	Ip            *string                `protobuf:"bytes,2,opt,name=ip" json:"ip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNetworkRequest) Reset() {
	*x = QueryNetworkRequest{}
	mi := &file_network_v1_network_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNetworkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNetworkRequest) ProtoMessage() {}

func (x *QueryNetworkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNetworkRequest.ProtoReflect.Descriptor instead.
func (*QueryNetworkRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{0}
}

func (x *QueryNetworkRequest) GetFilter() *internal.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryNetworkRequest) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

type Details struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location" json:"location,omitempty"`
	Asn           *ASN                   `protobuf:"bytes,2,opt,name=asn" json:"asn,omitempty"`
	Proxy         *Proxy                 `protobuf:"bytes,3,opt,name=proxy" json:"proxy,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Details) Reset() {
	*x = Details{}
	mi := &file_network_v1_network_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Details) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Details) ProtoMessage() {}

func (x *Details) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Details.ProtoReflect.Descriptor instead.
func (*Details) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{1}
}

func (x *Details) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

func (x *Details) GetAsn() *ASN {
	if x != nil {
		return x.Asn
	}
	return nil
}

func (x *Details) GetProxy() *Proxy {
	if x != nil {
		return x.Proxy
	}
	return nil
}

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          *string                `protobuf:"bytes,1,opt,name=cidr" json:"cidr,omitempty"`
	CountryCode   *string                `protobuf:"bytes,2,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	CountryName   *string                `protobuf:"bytes,3,opt,name=country_name,json=countryName" json:"country_name,omitempty"`
	RegionName    *string                `protobuf:"bytes,4,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	CityName      *string                `protobuf:"bytes,5,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	LatLong       *LatLong               `protobuf:"bytes,6,opt,name=lat_long,json=latLong" json:"lat_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_network_v1_network_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{2}
}

func (x *Location) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *Location) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *Location) GetCountryName() string {
	if x != nil && x.CountryName != nil {
		return *x.CountryName
	}
	return ""
}

func (x *Location) GetRegionName() string {
	if x != nil && x.RegionName != nil {
		return *x.RegionName
	}
	return ""
}

func (x *Location) GetCityName() string {
	if x != nil && x.CityName != nil {
		return *x.CityName
	}
	return ""
}

func (x *Location) GetLatLong() *LatLong {
	if x != nil {
		return x.LatLong
	}
	return nil
}

type ASN struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          *string                `protobuf:"bytes,1,opt,name=cidr" json:"cidr,omitempty"`
	AsNum         *uint64                `protobuf:"varint,2,opt,name=as_num,json=asNum" json:"as_num,omitempty"`
	AsName        *string                `protobuf:"bytes,3,opt,name=as_name,json=asName" json:"as_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ASN) Reset() {
	*x = ASN{}
	mi := &file_network_v1_network_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ASN) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ASN) ProtoMessage() {}

func (x *ASN) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ASN.ProtoReflect.Descriptor instead.
func (*ASN) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{3}
}

func (x *ASN) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *ASN) GetAsNum() uint64 {
	if x != nil && x.AsNum != nil {
		return *x.AsNum
	}
	return 0
}

func (x *ASN) GetAsName() string {
	if x != nil && x.AsName != nil {
		return *x.AsName
	}
	return ""
}

type Proxy struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cidr          *string                `protobuf:"bytes,1,opt,name=cidr" json:"cidr,omitempty"`
	ProxyType     *ProxyType             `protobuf:"varint,2,opt,name=proxy_type,json=proxyType,enum=network.v1.ProxyType" json:"proxy_type,omitempty"`
	CountryCode   *string                `protobuf:"bytes,3,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	CountryName   *string                `protobuf:"bytes,4,opt,name=country_name,json=countryName" json:"country_name,omitempty"`
	RegionName    *string                `protobuf:"bytes,5,opt,name=region_name,json=regionName" json:"region_name,omitempty"`
	CityName      *string                `protobuf:"bytes,6,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	Isp           *string                `protobuf:"bytes,7,opt,name=isp" json:"isp,omitempty"`
	Domain        *string                `protobuf:"bytes,8,opt,name=domain" json:"domain,omitempty"`
	UsageType     *UsageType             `protobuf:"varint,9,opt,name=usage_type,json=usageType,enum=network.v1.UsageType" json:"usage_type,omitempty"`
	Asn           *int64                 `protobuf:"varint,10,opt,name=asn" json:"asn,omitempty"`
	AsName        *string                `protobuf:"bytes,11,opt,name=as_name,json=asName" json:"as_name,omitempty"`
	LastSeen      *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=last_seen,json=lastSeen" json:"last_seen,omitempty"`
	ThreatType    *ThreatType            `protobuf:"varint,13,opt,name=threat_type,json=threatType,enum=network.v1.ThreatType" json:"threat_type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Proxy) Reset() {
	*x = Proxy{}
	mi := &file_network_v1_network_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Proxy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Proxy) ProtoMessage() {}

func (x *Proxy) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Proxy.ProtoReflect.Descriptor instead.
func (*Proxy) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{4}
}

func (x *Proxy) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *Proxy) GetProxyType() ProxyType {
	if x != nil && x.ProxyType != nil {
		return *x.ProxyType
	}
	return ProxyType_PROXY_TYPE_PUB_UNSPECIFIED
}

func (x *Proxy) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *Proxy) GetCountryName() string {
	if x != nil && x.CountryName != nil {
		return *x.CountryName
	}
	return ""
}

func (x *Proxy) GetRegionName() string {
	if x != nil && x.RegionName != nil {
		return *x.RegionName
	}
	return ""
}

func (x *Proxy) GetCityName() string {
	if x != nil && x.CityName != nil {
		return *x.CityName
	}
	return ""
}

func (x *Proxy) GetIsp() string {
	if x != nil && x.Isp != nil {
		return *x.Isp
	}
	return ""
}

func (x *Proxy) GetDomain() string {
	if x != nil && x.Domain != nil {
		return *x.Domain
	}
	return ""
}

func (x *Proxy) GetUsageType() UsageType {
	if x != nil && x.UsageType != nil {
		return *x.UsageType
	}
	return UsageType_USAGE_TYPE_UNSPECIFIED
}

func (x *Proxy) GetAsn() int64 {
	if x != nil && x.Asn != nil {
		return *x.Asn
	}
	return 0
}

func (x *Proxy) GetAsName() string {
	if x != nil && x.AsName != nil {
		return *x.AsName
	}
	return ""
}

func (x *Proxy) GetLastSeen() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSeen
	}
	return nil
}

func (x *Proxy) GetThreatType() ThreatType {
	if x != nil && x.ThreatType != nil {
		return *x.ThreatType
	}
	return ThreatType_THREAT_TYPE_UNSPECIFIED
}

type LatLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float32               `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     *float32               `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLong) Reset() {
	*x = LatLong{}
	mi := &file_network_v1_network_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLong) ProtoMessage() {}

func (x *LatLong) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLong.ProtoReflect.Descriptor instead.
func (*LatLong) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{5}
}

func (x *LatLong) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *LatLong) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type QueryNetworkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryNetworkResponse) Reset() {
	*x = QueryNetworkResponse{}
	mi := &file_network_v1_network_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryNetworkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryNetworkResponse) ProtoMessage() {}

func (x *QueryNetworkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryNetworkResponse.ProtoReflect.Descriptor instead.
func (*QueryNetworkResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{6}
}

type QueryConnectionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Filter        *internal.Filter       `protobuf:"bytes,1,opt,name=filter" json:"filter,omitempty"`
	SteamId       *string                `protobuf:"bytes,2,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	Cidr          *string                `protobuf:"bytes,3,opt,name=cidr" json:"cidr,omitempty"`
	CountryCode   *string                `protobuf:"bytes,4,opt,name=country_code,json=countryCode" json:"country_code,omitempty"`
	CountryName   *string                `protobuf:"bytes,5,opt,name=country_name,json=countryName" json:"country_name,omitempty"`
	CityName      *string                `protobuf:"bytes,6,opt,name=city_name,json=cityName" json:"city_name,omitempty"`
	ServerId      []int32                `protobuf:"varint,7,rep,packed,name=server_id,json=serverId" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConnectionsRequest) Reset() {
	*x = QueryConnectionsRequest{}
	mi := &file_network_v1_network_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConnectionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConnectionsRequest) ProtoMessage() {}

func (x *QueryConnectionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConnectionsRequest.ProtoReflect.Descriptor instead.
func (*QueryConnectionsRequest) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{7}
}

func (x *QueryConnectionsRequest) GetFilter() *internal.Filter {
	if x != nil {
		return x.Filter
	}
	return nil
}

func (x *QueryConnectionsRequest) GetSteamId() string {
	if x != nil && x.SteamId != nil {
		return *x.SteamId
	}
	return ""
}

func (x *QueryConnectionsRequest) GetCidr() string {
	if x != nil && x.Cidr != nil {
		return *x.Cidr
	}
	return ""
}

func (x *QueryConnectionsRequest) GetCountryCode() string {
	if x != nil && x.CountryCode != nil {
		return *x.CountryCode
	}
	return ""
}

func (x *QueryConnectionsRequest) GetCountryName() string {
	if x != nil && x.CountryName != nil {
		return *x.CountryName
	}
	return ""
}

func (x *QueryConnectionsRequest) GetCityName() string {
	if x != nil && x.CityName != nil {
		return *x.CityName
	}
	return ""
}

func (x *QueryConnectionsRequest) GetServerId() []int32 {
	if x != nil {
		return x.ServerId
	}
	return nil
}

type QueryConnectionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Connection    []*PersonConnection    `protobuf:"bytes,1,rep,name=connection" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryConnectionsResponse) Reset() {
	*x = QueryConnectionsResponse{}
	mi := &file_network_v1_network_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryConnectionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryConnectionsResponse) ProtoMessage() {}

func (x *QueryConnectionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryConnectionsResponse.ProtoReflect.Descriptor instead.
func (*QueryConnectionsResponse) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{8}
}

func (x *QueryConnectionsResponse) GetConnection() []*PersonConnection {
	if x != nil {
		return x.Connection
	}
	return nil
}

type PersonConnection struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	PersonConnectionId *int64                 `protobuf:"varint,1,opt,name=person_connection_id,json=personConnectionId" json:"person_connection_id,omitempty"`
	IpAddr             *string                `protobuf:"bytes,2,opt,name=ip_addr,json=ipAddr" json:"ip_addr,omitempty"`
	SteamId            *string                `protobuf:"bytes,3,opt,name=steam_id,json=steamId" json:"steam_id,omitempty"`
	PersonaName        *string                `protobuf:"bytes,4,opt,name=persona_name,json=personaName" json:"persona_name,omitempty"`
	ServerId           *int32                 `protobuf:"varint,5,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *PersonConnection) Reset() {
	*x = PersonConnection{}
	mi := &file_network_v1_network_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonConnection) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonConnection) ProtoMessage() {}

func (x *PersonConnection) ProtoReflect() protoreflect.Message {
	mi := &file_network_v1_network_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonConnection.ProtoReflect.Descriptor instead.
func (*PersonConnection) Descriptor() ([]byte, []int) {
	return file_network_v1_network_proto_rawDescGZIP(), []int{9}
}

func (x *PersonConnection) GetPersonConnectionId() int64 {
	if x != nil && x.PersonConnectionId != nil {
		return *x.PersonConnectionId
	}
	return 0
}

func (x *PersonConnection) GetIpAddr() string {
	if x != nil && x.IpAddr != nil {
		return *x.IpAddr
	}
	return ""
}

func (x *PersonConnection) GetSteamId() string {
	if x != nil && x.SteamId != nil {
		return *x.SteamId
	}
	return ""
}

func (x *PersonConnection) GetPersonaName() string {
	if x != nil && x.PersonaName != nil {
		return *x.PersonaName
	}
	return ""
}

func (x *PersonConnection) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

var File_network_v1_network_proto protoreflect.FileDescriptor

const file_network_v1_network_proto_rawDesc = "" +
	"\n" +
	"\x18network/v1/network.proto\x12\n" +
	"network.v1\x1a\ffilter.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"F\n" +
	"\x13QueryNetworkRequest\x12\x1f\n" +
	"\x06filter\x18\x01 \x01(\v2\a.FilterR\x06filter\x12\x0e\n" +
	"\x02ip\x18\x02 \x01(\tR\x02ip\"\x87\x01\n" +
	"\aDetails\x120\n" +
	"\blocation\x18\x01 \x01(\v2\x14.network.v1.LocationR\blocation\x12!\n" +
	"\x03asn\x18\x02 \x01(\v2\x0f.network.v1.ASNR\x03asn\x12'\n" +
	"\x05proxy\x18\x03 \x01(\v2\x11.network.v1.ProxyR\x05proxy\"\xd2\x01\n" +
	"\bLocation\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12!\n" +
	"\fcountry_code\x18\x02 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x03 \x01(\tR\vcountryName\x12\x1f\n" +
	"\vregion_name\x18\x04 \x01(\tR\n" +
	"regionName\x12\x1b\n" +
	"\tcity_name\x18\x05 \x01(\tR\bcityName\x12.\n" +
	"\blat_long\x18\x06 \x01(\v2\x13.network.v1.LatLongR\alatLong\"I\n" +
	"\x03ASN\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x12\x15\n" +
	"\x06as_num\x18\x02 \x01(\x04R\x05asNum\x12\x17\n" +
	"\aas_name\x18\x03 \x01(\tR\x06asName\"\xd2\x03\n" +
	"\x05Proxy\x12\x12\n" +
	"\x04cidr\x18\x01 \x01(\tR\x04cidr\x124\n" +
	"\n" +
	"proxy_type\x18\x02 \x01(\x0e2\x15.network.v1.ProxyTypeR\tproxyType\x12!\n" +
	"\fcountry_code\x18\x03 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x04 \x01(\tR\vcountryName\x12\x1f\n" +
	"\vregion_name\x18\x05 \x01(\tR\n" +
	"regionName\x12\x1b\n" +
	"\tcity_name\x18\x06 \x01(\tR\bcityName\x12\x10\n" +
	"\x03isp\x18\a \x01(\tR\x03isp\x12\x16\n" +
	"\x06domain\x18\b \x01(\tR\x06domain\x124\n" +
	"\n" +
	"usage_type\x18\t \x01(\x0e2\x15.network.v1.UsageTypeR\tusageType\x12\x10\n" +
	"\x03asn\x18\n" +
	" \x01(\x03R\x03asn\x12\x17\n" +
	"\aas_name\x18\v \x01(\tR\x06asName\x127\n" +
	"\tlast_seen\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\blastSeen\x127\n" +
	"\vthreat_type\x18\r \x01(\x0e2\x16.network.v1.ThreatTypeR\n" +
	"threatType\"C\n" +
	"\aLatLong\x12\x1a\n" +
	"\blatitude\x18\x01 \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x02 \x01(\x02R\tlongitude\"\x16\n" +
	"\x14QueryNetworkResponse\"\xe9\x01\n" +
	"\x17QueryConnectionsRequest\x12\x1f\n" +
	"\x06filter\x18\x01 \x01(\v2\a.FilterR\x06filter\x12\x19\n" +
	"\bsteam_id\x18\x02 \x01(\tR\asteamId\x12\x12\n" +
	"\x04cidr\x18\x03 \x01(\tR\x04cidr\x12!\n" +
	"\fcountry_code\x18\x04 \x01(\tR\vcountryCode\x12!\n" +
	"\fcountry_name\x18\x05 \x01(\tR\vcountryName\x12\x1b\n" +
	"\tcity_name\x18\x06 \x01(\tR\bcityName\x12\x1b\n" +
	"\tserver_id\x18\a \x03(\x05R\bserverId\"X\n" +
	"\x18QueryConnectionsResponse\x12<\n" +
	"\n" +
	"connection\x18\x01 \x03(\v2\x1c.network.v1.PersonConnectionR\n" +
	"connection\"\xb8\x01\n" +
	"\x10PersonConnection\x120\n" +
	"\x14person_connection_id\x18\x01 \x01(\x03R\x12personConnectionId\x12\x17\n" +
	"\aip_addr\x18\x02 \x01(\tR\x06ipAddr\x12\x19\n" +
	"\bsteam_id\x18\x03 \x01(\tR\asteamId\x12!\n" +
	"\fpersona_name\x18\x04 \x01(\tR\vpersonaName\x12\x1b\n" +
	"\tserver_id\x18\x05 \x01(\x05R\bserverId*\xd0\x01\n" +
	"\n" +
	"ThreatType\x12\x1b\n" +
	"\x17THREAT_TYPE_UNSPECIFIED\x10\x00\x12\x14\n" +
	"\x10THREAT_TYPE_SPAM\x10\x01\x12\x16\n" +
	"\x12THREAT_TYPE_BOTNET\x10\x02\x12\x17\n" +
	"\x13THREAT_TYPE_SCANNER\x10\x03\x12\x1b\n" +
	"\x17THREAT_TYPE_SPAM_BOTNET\x10\x04\x12\x1c\n" +
	"\x18THREAT_TYPE_SPAM_SCANNER\x10\x05\x12#\n" +
	"\x1fTHREAT_TYPE_SPAM_SCANNER_BOTNET\x10\x06*\xcb\x02\n" +
	"\tUsageType\x12\x1a\n" +
	"\x16USAGE_TYPE_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eUSAGE_TYPE_CDN\x10\x01\x12\x1f\n" +
	"\x1bUSAGE_TYPE_ISP_FIXED_MOBILE\x10\x02\x12\x19\n" +
	"\x15USAGE_TYPE_COMMERCIAL\x10\x03\x12\x19\n" +
	"\x15USAGE_TYPE_ISP_MOBILE\x10\x04\x12\x16\n" +
	"\x12USAGE_TYPE_LIBRARY\x10\x05\x12\x1a\n" +
	"\x16USAGE_TYPE_DATA_CENTER\x10\x06\x12\x17\n" +
	"\x13USAGE_TYPE_MILITARY\x10\a\x12\x19\n" +
	"\x15USAGE_TYPE_GOVERNMENT\x10\b\x12\x18\n" +
	"\x14USAGE_TYPE_ISP_FIXED\x10\t\x12\x1b\n" +
	"\x17USAGE_TYPE_ORGANIZATION\x10\n" +
	"\x12\x18\n" +
	"\x14USAGE_TYPE_EDUCATION\x10\v*+\n" +
	"\tProxyType\x12\x1e\n" +
	"\x1aPROXY_TYPE_PUB_UNSPECIFIED\x10\x002\x84\x02\n" +
	"\x0eNetworkService\x12_\n" +
	"\x10QueryConnections\x12#.network.v1.QueryConnectionsRequest\x1a$.network.v1.QueryConnectionsResponse\"\x00\x12S\n" +
	"\fQueryNetwork\x12\x1f.network.v1.QueryNetworkRequest\x1a .network.v1.QueryNetworkResponse\"\x00\x12<\n" +
	"\bUpdateDB\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\"\x00B\xa6\x01\n" +
	"\x0ecom.network.v1B\fNetworkProtoP\x01Z=github.com/leighmacdonald/gbans/internal/network/v1;networkv1\xa2\x02\x03NXX\xaa\x02\n" +
	"Network.V1\xca\x02\n" +
	"Network\\V1\xe2\x02\x16Network\\V1\\GPBMetadata\xea\x02\vNetwork::V1b\beditionsp\xe8\a"

var (
	file_network_v1_network_proto_rawDescOnce sync.Once
	file_network_v1_network_proto_rawDescData []byte
)

func file_network_v1_network_proto_rawDescGZIP() []byte {
	file_network_v1_network_proto_rawDescOnce.Do(func() {
		file_network_v1_network_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)))
	})
	return file_network_v1_network_proto_rawDescData
}

var file_network_v1_network_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_network_v1_network_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_network_v1_network_proto_goTypes = []any{
	(ThreatType)(0),                  // 0: network.v1.ThreatType
	(UsageType)(0),                   // 1: network.v1.UsageType
	(ProxyType)(0),                   // 2: network.v1.ProxyType
	(*QueryNetworkRequest)(nil),      // 3: network.v1.QueryNetworkRequest
	(*Details)(nil),                  // 4: network.v1.Details
	(*Location)(nil),                 // 5: network.v1.Location
	(*ASN)(nil),                      // 6: network.v1.ASN
	(*Proxy)(nil),                    // 7: network.v1.Proxy
	(*LatLong)(nil),                  // 8: network.v1.LatLong
	(*QueryNetworkResponse)(nil),     // 9: network.v1.QueryNetworkResponse
	(*QueryConnectionsRequest)(nil),  // 10: network.v1.QueryConnectionsRequest
	(*QueryConnectionsResponse)(nil), // 11: network.v1.QueryConnectionsResponse
	(*PersonConnection)(nil),         // 12: network.v1.PersonConnection
	(*internal.Filter)(nil),          // 13: Filter
	(*timestamppb.Timestamp)(nil),    // 14: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),            // 15: google.protobuf.Empty
}
var file_network_v1_network_proto_depIdxs = []int32{
	13, // 0: network.v1.QueryNetworkRequest.filter:type_name -> Filter
	5,  // 1: network.v1.Details.location:type_name -> network.v1.Location
	6,  // 2: network.v1.Details.asn:type_name -> network.v1.ASN
	7,  // 3: network.v1.Details.proxy:type_name -> network.v1.Proxy
	8,  // 4: network.v1.Location.lat_long:type_name -> network.v1.LatLong
	2,  // 5: network.v1.Proxy.proxy_type:type_name -> network.v1.ProxyType
	1,  // 6: network.v1.Proxy.usage_type:type_name -> network.v1.UsageType
	14, // 7: network.v1.Proxy.last_seen:type_name -> google.protobuf.Timestamp
	0,  // 8: network.v1.Proxy.threat_type:type_name -> network.v1.ThreatType
	13, // 9: network.v1.QueryConnectionsRequest.filter:type_name -> Filter
	12, // 10: network.v1.QueryConnectionsResponse.connection:type_name -> network.v1.PersonConnection
	10, // 11: network.v1.NetworkService.QueryConnections:input_type -> network.v1.QueryConnectionsRequest
	3,  // 12: network.v1.NetworkService.QueryNetwork:input_type -> network.v1.QueryNetworkRequest
	15, // 13: network.v1.NetworkService.UpdateDB:input_type -> google.protobuf.Empty
	11, // 14: network.v1.NetworkService.QueryConnections:output_type -> network.v1.QueryConnectionsResponse
	9,  // 15: network.v1.NetworkService.QueryNetwork:output_type -> network.v1.QueryNetworkResponse
	15, // 16: network.v1.NetworkService.UpdateDB:output_type -> google.protobuf.Empty
	14, // [14:17] is the sub-list for method output_type
	11, // [11:14] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_network_v1_network_proto_init() }
func file_network_v1_network_proto_init() {
	if File_network_v1_network_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_network_v1_network_proto_rawDesc), len(file_network_v1_network_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_network_v1_network_proto_goTypes,
		DependencyIndexes: file_network_v1_network_proto_depIdxs,
		EnumInfos:         file_network_v1_network_proto_enumTypes,
		MessageInfos:      file_network_v1_network_proto_msgTypes,
	}.Build()
	File_network_v1_network_proto = out.File
	file_network_v1_network_proto_goTypes = nil
	file_network_v1_network_proto_depIdxs = nil
}
