// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,valid_types=legacy_required+protovalidate_required"
// @generated from file database/query/v1/filter.proto (package database.query.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file database/query/v1/filter.proto.
 */
export const file_database_query_v1_filter: GenFile = /*@__PURE__*/
  fileDesc("Ch5kYXRhYmFzZS9xdWVyeS92MS9maWx0ZXIucHJvdG8SEWRhdGFiYXNlLnF1ZXJ5LnYxIkcKBkZpbHRlchIOCgZvZmZzZXQYASABKAQSDQoFbGltaXQYAiABKAQSDAoEZGVzYxgDIAEoCBIQCghvcmRlcl9ieRgEIAEoCULOAQoVY29tLmRhdGFiYXNlLnF1ZXJ5LnYxQgtGaWx0ZXJQcm90b1ABWkJnaXRodWIuY29tL2xlaWdobWFjZG9uYWxkL2diYW5zL2ludGVybmFsL2RhdGFiYXNlL3F1ZXJ5L3YxO3F1ZXJ5djGiAgNEUViqAhFEYXRhYmFzZS5RdWVyeS5WMcoCEURhdGFiYXNlXFF1ZXJ5XFYx4gIdRGF0YWJhc2VcUXVlcnlcVjFcR1BCTWV0YWRhdGHqAhNEYXRhYmFzZTo6UXVlcnk6OlYxYghlZGl0aW9uc3DoBw");

/**
 * @generated from message database.query.v1.Filter
 */
export type Filter = Message<"database.query.v1.Filter"> & {
  /**
   * @generated from field: uint64 offset = 1;
   */
  offset: bigint;

  /**
   * @generated from field: uint64 limit = 2;
   */
  limit: bigint;

  /**
   * @generated from field: bool desc = 3;
   */
  desc: boolean;

  /**
   * @generated from field: string order_by = 4;
   */
  orderBy: string;
};

export type FilterValid = Filter;

/**
 * Describes the message database.query.v1.Filter.
 * Use `create(FilterSchema)` to create a new message.
 */
export const FilterSchema: GenMessage<Filter, {validType: FilterValid}> = /*@__PURE__*/
  messageDesc(file_database_query_v1_filter, 0);

