declare module '*.png';
// declare module '*.jpg';
// declare module '*.jpeg';
// declare module '*.png';
// declare module '*.gif';
// declare module '*.svg';
// declare module '*.webp';
// declare module '*.html';
// declare module '*.webm';
// declare module '*.zip';
// declare module '*.css';
