BEGIN;

ALTER TABLE person
DROP COLUMN IF EXISTS avatar;

ALTER TABLE person
DROP COLUMN IF EXISTS avatarmedium;

ALTER TABLE person
DROP COLUMN IF EXISTS avatarfull;

ALTER TABLE person
DROP COLUMN IF EXISTS profileurl;

COMMIT;
