version: "3.3"

services:
  gbans:
    build:
      context: "../"
      dockerfile: Dockerfile
    volumes:
      - dl_cache:/app/.cache
      - ./gbans.yml:/app/gbans.yml
    depends_on:
      - postgres
    networks:
      - prod_network
    ports:
      # This is generally expected to run under a reverse proxy, like Caddy.
      - "127.0.0.1:6006:6006"
    environment:
      GBANS_DATABASE_DSN: postgresql://gbans:gbans@postgres:5432/gbans
      GBANS_GENERAL_STEAM_KEY: ${GBANS_GENERAL_STEAM_KEY}
    command: ./gbans serve

  postgres:
    build:
      context: "."
      dockerfile: postgres-ip4r.Dockerfile
    restart: always
    shm_size: 2gb
    volumes:
      - gbans_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: gbans
      POSTGRES_DB: gbans
      POSTGRES_PASSWORD: gbans
      POSTGRES_HOST_AUTH_METHOD: md5
    networks:
      - prod_network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U gbans" ]
      interval: 5s
      timeout: 5s
      retries: 10

volumes:
  dl_cache:
  gbans_db:

networks:
  prod_network:
