package app

import "errors"

var (
	errSaveChanges              = errors.New("cannot save changes")
	errDiscordAlreadyLinked     = errors.New("discord account is already linked")
	errFailedFetchBan           = errors.New("failed to get existing ban")
	errSaveBan                  = errors.New("failed to save ban")
	errGetBanReport             = errors.New("failed to get ban report")
	errReportStateUpdate        = errors.New("failed to update report state")
	errFetchPerson              = errors.New("failed to fetch/create person")
	errFetchSource              = errors.New("failed to fetch source player")
	errFetchTarget              = errors.New("failed to fetch target player")
	errSaveBanGroup             = errors.New("failed to save ban group")
	errGroupValidate            = errors.New("failed to validate group")
	errParseASN                 = errors.New("failed to parse asn")
	errFetchASNBan              = errors.New("failed to fetch asn ban")
	errDropASNBan               = errors.New("failed to drop existing asn ban")
	errUnknownASN               = errors.New("no networks found for asn")
	errFetchASN                 = errors.New("failed to fetch asn networks")
	errASNNoRecords             = errors.New("no records found for asn")
	errOwnerInvalid             = errors.New("configured owner steamid is invalid")
	errCreateAdmin              = errors.New("failed to create admin user")
	errSetupAdmin               = errors.New("failed to setup admin user")
	errSetupNews                = errors.New("failed to create sample news entry")
	errSetupServer              = errors.New("failed to create sample server entry")
	errSetupWiki                = errors.New("failed to create sample wiki entry")
	errSetupWeapons             = errors.New("failed to setup weapon maps")
	errLoadFilters              = errors.New("failed to load chat filters")
	ErrInvalidFilterRegex       = errors.New("could not parse filter regex")
	ErrInvalidFilterID          = errors.New("invalid fiter ID")
	errInitNetBlocks            = errors.New("failed to load net blocks")
	errInitNetWhitelist         = errors.New("failed to load net block whitelists")
	errHTTPServer               = errors.New("http listener returned unexpected error")
	errNotificationSteamIDs     = errors.New("failed to load notification steam ids")
	errNotificationPeople       = errors.New("failed to load notified people")
	errSteamAPIArgLimit         = errors.New("steam api support a max of 100 steam ids")
	errFetchSteamBans           = errors.New("failed to fetch ban status from steam api")
	errSteamAPISummaries        = errors.New("failed to fetch player summaries")
	errSteamAPI                 = errors.New("steam api requests have errors")
	errUpdatePerson             = errors.New("failed to save updated person profile")
	ErrCommandFailed            = errors.New("command failed")
	ErrDiscordCreate            = errors.New("failed to connect to discord")
	ErrDiscordOpen              = errors.New("failed to open discord connection")
	ErrDuplicateCommand         = errors.New("duplicate command registration")
	ErrDiscordMessageSen        = errors.New("failed to send discord message")
	ErrDiscordOverwriteCommands = errors.New("failed to bulk overwrite discord commands")
	ErrInsufficientPlayers      = errors.New("insufficient Match players")
	ErrIncompleteMatch          = errors.New("insufficient match data")
	errSaveMatch                = errors.New("could not save match results")
	errLoadMatch                = errors.New("could not load match results")
	errLoadServer               = errors.New("failed to load match server")
	ErrPatreonFetchCampaign     = errors.New("failed to fetch patreon campaign")
	ErrPatreonInvalidCampaign   = errors.New("patreon campaign does not exist")
	ErrPatreonFetchPledges      = errors.New("failed to fetch patreon pledges")
	ErrRegisterCommand          = errors.New("failed to register discord command")
	ErrBanDoesNotExist          = errors.New("ban does not exist")
	ErrSteamUnset               = errors.New("must set steam id. see /set_steam command")
	ErrFetchClassStats          = errors.New("failed to fetch class stats")
	ErrFetchWeaponStats         = errors.New("failed to fetch weapon stats")
	ErrFetchKillstreakStats     = errors.New("failed to fetch killstreak stats")
	ErrFetchMedicStats          = errors.New("failed to fetch medic stats")
	ErrGetServer                = errors.New("failed to get server")
	ErrReasonInvalid            = errors.New("invalid reason")
	ErrDuplicateBan             = errors.New("duplicate ban")
	ErrCIDRMissing              = errors.New("cidr invalid or missing")
)
