package app

import (
	"github.com/leighmacdonald/gbans/internal/model"
	"github.com/leighmacdonald/gbans/pkg/logparse"
	"github.com/leighmacdonald/golib"
	"github.com/leighmacdonald/steamid/v2/steamid"
	"github.com/pkg/errors"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"io/ioutil"
	"path"
	"strings"
	"testing"
	"time"
)

func TestMatch_Apply(t *testing.T) {
	p := golib.FindFile(path.Join("test_data", "log_3124689.log"), "gbans")
	if p == "" {
		t.Skipf("Cant find test file: log_3124689.log")
		return
	}
	body, errRead := ioutil.ReadFile(p)
	require.NoError(t, errRead)
	playerStateCache := newPlayerCache()
	m := NewMatch()

	players := map[steamid.SID64]*model.Person{}

	mockGetTestPlayer := func(id string, v map[string]any, p *model.Person) error {
		sid1Str, ok := v[id]
		if ok {
			s := steamid.SID3ToSID64(steamid.SID3(sid1Str.(string)))
			_, found := players[s]
			if !found {
				lp := model.NewPerson(s)
				players[s] = &lp
			}
			*p = *players[s]
		}
		return nil
	}

	testServer := model.NewServer("tst-1", "test-1.localhost", 27015)
	mockGetTestServer := func(serverName string, s *model.Server) error {
		if serverName == testServer.ServerName {
			*s = testServer
			return nil
		}
		return errors.New("server not found")
	}
	rows := strings.Split(string(body), "\n")
	for _, line := range rows {
		if line == "" {
			continue
		}
		var se model.ServerEvent
		require.NoError(t, logToServerEvent(model.LogPayload{ServerName: "tst-1", Message: line},
			playerStateCache,
			&se,
			mockGetTestPlayer,
			mockGetTestServer,
		), "Failed to create ServerEvent")
		err := m.Apply(se)
		if err != nil && !errors.Is(err, ErrIgnored) {
			t.Errorf("Failed to Apply: %v", err)
		}
	}

	match3124689, names := testMatch()
	var getName = func(sid64 steamid.SID64) string {
		for name, sid := range names {
			if sid == sid64 {
				return name
			}
		}
		return "???"
	}

	// Player sum values
	for sid := range match3124689.playerSums {
		assert.Equal(t, match3124689.playerSums[sid].Kills,
			m.playerSums[sid].Kills, "Kills incorrect %v", getName(sid))
	}
	for sid := range match3124689.playerSums {
		assert.Equal(t, match3124689.playerSums[sid].Damage,
			m.playerSums[sid].Damage, "Damage incorrect %v", getName(sid))
	}
	for sid := range match3124689.playerSums {
		assert.Equal(t, match3124689.playerSums[sid].Healing,
			m.playerSums[sid].Healing, "Healing incorrect %v", getName(sid))
	}

	// Medic sums
	for sid := range match3124689.medicSums {
		assert.Equal(t, match3124689.medicSums[sid].Drops,
			m.medicSums[sid].Drops, "Drops incorrect %v", getName(sid))
	}
}

// https://logs.tf/3124689
func testMatch() (Match, map[string]steamid.SID64) {
	name := map[string]steamid.SID64{
		"var":                76561198164892406,
		"para":               76561198057150173,
		"sentar":             76561198126692772,
		"Pride (Pyro Main)":  76561198036671190,
		"jumbuck":            76561198084686835,
		"freakyjoy1.ttv":     76561198061174192,
		"avg Q enjoyer":      76561198113244106,
		"ExCalibre":          76561198423392803,
		"nomodick":           76561198051884373,
		"Lochlore":           76561198087442614,
		"Link":               76561198043171944,
		"Tunaaaaaa":          76561198809011070,
		"Tiger":              76561198271399587,
		"Invidia":            76561198096251579,
		"El Sur":             76561198383642609,
		"maz":                76561198050517054,
		"Golden Terrestrial": 76561198082713023,
		"Doctrine":           76561199050447792,
		"WitlessConnor":      76561198073709029,
	}

	match := Match{
		title:   "Qixalite Booking: RED vs BLU",
		mapName: "koth_cascade_rc2",
		playerSums: map[steamid.SID64]*MatchPlayerSum{
			name["var"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       12,
				Assists:     10,
				Deaths:      14,
				Damage:      5078,
				DamageTaken: 5399,
				HealthPacks: 16,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    3,
				Classes:     []logparse.PlayerClass{logparse.Scout},
				Healing:     370,
			},
			name["para"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       9,
				Assists:     1,
				Deaths:      23,
				Damage:      4022,
				DamageTaken: 4616,
				HealthPacks: 27,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    1,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Soldier},
				Healing:     754,
			},
			name["sentar"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       13,
				Assists:     8,
				Deaths:      5,
				Damage:      3873,
				DamageTaken: 3537,
				HealthPacks: 16,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Pyro},
				Healing:     481,
			},
			name["Pride (Pyro Main)"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       13,
				Assists:     4,
				Deaths:      16,
				Damage:      7598,
				DamageTaken: 6936,
				HealthPacks: 10,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Demo},
				Healing:     436,
			},
			name["jumbuck"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       18,
				Assists:     1,
				Deaths:      9,
				Damage:      7250,
				DamageTaken: 8918,
				HealthPacks: 24,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Heavy},
				Healing:     1187,
			},
			name["freakyjoy1.ttv"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       3,
				Assists:     1,
				Deaths:      14,
				Damage:      3385,
				DamageTaken: 3246,
				HealthPacks: 16,
				BackStabs:   0,
				HeadShots:   8,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Engineer, logparse.Sniper},
				Healing:     686,
			},
			name["avg Q enjoyer"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       4,
				Assists:     8,
				Deaths:      9,
				Damage:      1098,
				DamageTaken: 3169,
				HealthPacks: 10,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Medic},
				Healing:     17708,
			},
			name["ExCalibre"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       7,
				Assists:     0,
				Deaths:      19,
				Damage:      2809,
				DamageTaken: 4023,
				HealthPacks: 5,
				BackStabs:   0,
				HeadShots:   4,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Sniper, logparse.Engineer},
				Healing:     395,
			},
			name["nomodick"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       13,
				Assists:     4,
				Deaths:      17,
				Damage:      9672,
				DamageTaken: 3450,
				HealthPacks: 23,
				BackStabs:   9,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Spy, logparse.Pyro},
				Healing:     456,
			},
			name["Lochlore"]: {
				Team:        logparse.BLU,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       12,
				Assists:     1,
				Deaths:      17,
				Damage:      8796,
				DamageTaken: 3517,
				HealthPacks: 22,
				BackStabs:   9,
				HeadShots:   0,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Spy},
				Healing:     546,
			},
			name["Link"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       28,
				Assists:     5,
				Deaths:      11,
				Damage:      6236,
				DamageTaken: 2932,
				HealthPacks: 46,
				BackStabs:   9,
				HeadShots:   0,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Scout},
				Healing:     1036,
			},
			name["Tunaaaaaa"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       26,
				Assists:     2,
				Deaths:      9,
				Damage:      6107,
				DamageTaken: 4053,
				HealthPacks: 29,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    1,
				Captures:    2,
				Classes:     []logparse.PlayerClass{logparse.Soldier},
				Healing:     1313,
			},
			name["Tiger"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       9,
				Assists:     13,
				Deaths:      8,
				Damage:      4613,
				DamageTaken: 5054,
				HealthPacks: 16,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    2,
				Classes:     []logparse.PlayerClass{logparse.Pyro},
				Healing:     553,
			},
			name["Invidia"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       7,
				Assists:     6,
				Deaths:      15,
				Damage:      3859,
				DamageTaken: 6871,
				HealthPacks: 0,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Demo},
				Healing:     0,
			},
			name["El Sur"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       15,
				Assists:     6,
				Deaths:      11,
				Damage:      6708,
				DamageTaken: 8299,
				HealthPacks: 20,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    3,
				Classes:     []logparse.PlayerClass{logparse.Heavy},
				Healing:     1216,
			},
			name["maz"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       18,
				Assists:     9,
				Deaths:      12,
				Damage:      6309,
				DamageTaken: 4655,
				HealthPacks: 23,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    4,
				Classes:     []logparse.PlayerClass{logparse.Engineer, logparse.Scout},
				Healing:     922,
			},
			name["Golden Terrestrial"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       1,
				Assists:     13,
				Deaths:      5,
				Damage:      606,
				DamageTaken: 2733,
				HealthPacks: 6,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Medic},
				Healing:     19762,
			},
			name["Doctrine"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       18,
				Assists:     1,
				Deaths:      12,
				Damage:      5723,
				DamageTaken: 3933,
				HealthPacks: 4,
				BackStabs:   0,
				HeadShots:   18,
				Airshots:    0,
				Captures:    1,
				Classes:     []logparse.PlayerClass{logparse.Sniper},
				Healing:     101,
			},
			name["WitlessConnor"]: {
				Team:        logparse.RED,
				TimeStart:   time.Time{},
				TimeEnd:     time.Time{},
				Kills:       0,
				Assists:     0,
				Deaths:      1,
				Damage:      40,
				DamageTaken: 372,
				HealthPacks: 2,
				BackStabs:   0,
				HeadShots:   0,
				Airshots:    0,
				Captures:    0,
				Classes:     []logparse.PlayerClass{logparse.Spy},
				Healing:     57,
			},
		},
		medicSums: map[steamid.SID64]*MatchMedicSum{
			name["avg Q enjoyer"]: {
				Healing: 17368,
				Charges: map[logparse.Medigun]int{
					logparse.Uber: 4,
				},
				Drops:               2,
				AvgTimeToBuild:      42,
				AvgTimeBeforeUse:    28,
				NearFullChargeDeath: 1,
				AvgUberLength:       7,
				MajorAdvLost:        1,
				BiggestAdvLost:      39,
				DeathAfterCharge:    0,
				HealTargets:         map[steamid.SID64]*MatchClassSums{},
			},
			name["Golden Terrestrial"]: {
				Healing: 19545,
				Charges: map[logparse.Medigun]int{
					logparse.Uber: 6,
				},
				Drops:               1,
				AvgTimeToBuild:      40,
				AvgTimeBeforeUse:    30,
				NearFullChargeDeath: 0,
				AvgUberLength:       7.3,
				MajorAdvLost:        0,
				BiggestAdvLost:      0,
				DeathAfterCharge:    1,
				HealTargets:         map[steamid.SID64]*MatchClassSums{},
			},
		},
		teamSums: map[logparse.Team]*MatchTeamSum{
			logparse.RED: {
				Kills:     122,
				Damage:    40201,
				Charges:   6,
				Drops:     1,
				Caps:      6,
				MidFights: 2,
			},
			logparse.BLU: {
				Kills:     104,
				Damage:    45512,
				Charges:   4,
				Drops:     2,
				Caps:      4,
				MidFights: 1,
			},
		},
		rounds: []*MatchRoundSum{
			{
				Length: 313 * time.Second,
				Score: TeamScores{
					Red: 1,
					Blu: 0,
				},
				KillsBlu:  23,
				KillsRed:  33,
				UbersBlu:  1,
				UbersRed:  2,
				DamageBlu: 10605,
				DamageRed: 12805,
				MidFight:  logparse.RED,
			},
			{
				Length: 378 * time.Second,
				Score: TeamScores{
					Red: 2,
					Blu: 0,
				},
				KillsBlu:  38,
				KillsRed:  52,
				UbersBlu:  2,
				UbersRed:  3,
				DamageBlu: 15266,
				DamageRed: 18102,
				MidFight:  logparse.BLU,
			},
			{
				Length: 325 * time.Second,
				Score: TeamScores{
					Red: 3,
					Blu: 0,
				},
				KillsBlu:  34,
				KillsRed:  46,
				UbersBlu:  1,
				UbersRed:  1,
				DamageBlu: 15258,
				DamageRed: 12677,
				MidFight:  logparse.RED,
			},
		},
		classKills: map[steamid.SID64]*MatchClassSums{
			name["avg Q enjoyer"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     0,
				Demoman:  0,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      3,
			},
			name["Doctrine"]: {
				Scout:    3,
				Soldier:  0,
				Pyro:     2,
				Demoman:  4,
				Heavy:    1,
				Engineer: 3,
				Medic:    2,
				Sniper:   2,
				Spy:      1,
			},
			name["El Sur"]: {
				Scout:    1,
				Soldier:  3,
				Pyro:     1,
				Demoman:  1,
				Heavy:    4,
				Engineer: 1,
				Medic:    1,
				Sniper:   0,
				Spy:      3,
			},
			name["ExCalibre"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     0,
				Demoman:  1,
				Heavy:    0,
				Engineer: 2,
				Medic:    0,
				Sniper:   2,
				Spy:      1,
			},
			name["freakyjoy1.ttv"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     0,
				Demoman:  1,
				Heavy:    0,
				Engineer: 0,
				Medic:    0,
				Sniper:   1,
				Spy:      0,
			},
			name["Golden Terrestrial"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     0,
				Demoman:  0,
				Heavy:    0,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      1,
			},
			name["Invidia"]: {
				Scout:    2,
				Soldier:  1,
				Pyro:     1,
				Demoman:  1,
				Heavy:    0,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      2,
			},
			name["jumbuck"]: {
				Scout:    7,
				Soldier:  1,
				Pyro:     1,
				Demoman:  2,
				Heavy:    1,
				Engineer: 2,
				Medic:    1,
				Sniper:   1,
				Spy:      2,
			},
			name["Link"]: {
				Scout:    1,
				Soldier:  7,
				Pyro:     0,
				Demoman:  2,
				Heavy:    1,
				Engineer: 4,
				Medic:    2,
				Sniper:   7,
				Spy:      4,
			},
			name["Lochlore"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     2,
				Demoman:  5,
				Heavy:    0,
				Engineer: 1,
				Medic:    2,
				Sniper:   2,
				Spy:      0,
			},
			name["maz"]: {
				Scout:    0,
				Soldier:  6,
				Pyro:     2,
				Demoman:  2,
				Heavy:    2,
				Engineer: 2,
				Medic:    0,
				Sniper:   2,
				Spy:      2,
			},
			name["nomodick"]: {
				Scout:    4,
				Soldier:  0,
				Pyro:     1,
				Demoman:  4,
				Heavy:    1,
				Engineer: 1,
				Medic:    1,
				Sniper:   1,
				Spy:      0,
			},
			name["para"]: {
				Scout:    2,
				Soldier:  0,
				Pyro:     1,
				Demoman:  1,
				Heavy:    1,
				Engineer: 2,
				Medic:    0,
				Sniper:   2,
				Spy:      0,
			},
			name["Pride (Pyro Main)"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     3,
				Demoman:  1,
				Heavy:    4,
				Engineer: 0,
				Medic:    1,
				Sniper:   2,
				Spy:      1,
			},
			name["sentar"]: {
				Scout:    1,
				Soldier:  4,
				Pyro:     0,
				Demoman:  3,
				Heavy:    0,
				Engineer: 1,
				Medic:    1,
				Sniper:   1,
				Spy:      2,
			},
			name["Tiger"]: {
				Scout:    1,
				Soldier:  3,
				Pyro:     1,
				Demoman:  2,
				Heavy:    0,
				Engineer: 1,
				Medic:    0,
				Sniper:   0,
				Spy:      1,
			},
			name["Tunaaaaaa"]: {
				Scout:    4,
				Soldier:  3,
				Pyro:     2,
				Demoman:  1,
				Heavy:    0,
				Engineer: 2,
				Medic:    3,
				Sniper:   8,
				Spy:      3,
			},
			name["var"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     1,
				Demoman:  0,
				Heavy:    4,
				Engineer: 2,
				Medic:    0,
				Sniper:   1,
				Spy:      3,
			},
		},
		classKillsAssists: map[steamid.SID64]*MatchClassSums{
			name["avg Q enjoyer"]: {
				Scout:    1,
				Soldier:  1,
				Pyro:     1,
				Demoman:  1,
				Heavy:    3,
				Engineer: 1,
				Medic:    1,
				Sniper:   0,
				Spy:      3,
			},
			name["Doctrine"]: {
				Scout:    3,
				Soldier:  0,
				Pyro:     2,
				Demoman:  4,
				Heavy:    1,
				Engineer: 3,
				Medic:    2,
				Sniper:   3,
				Spy:      1,
			},
			name["El Sur"]: {
				Scout:    2,
				Soldier:  6,
				Pyro:     1,
				Demoman:  1,
				Heavy:    4,
				Engineer: 2,
				Medic:    1,
				Sniper:   0,
				Spy:      4,
			},
			name["ExCalibre"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     0,
				Demoman:  1,
				Heavy:    0,
				Engineer: 2,
				Medic:    0,
				Sniper:   2,
				Spy:      1,
			},
			name["freakyjoy1.ttv"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     1,
				Demoman:  1,
				Heavy:    0,
				Engineer: 0,
				Medic:    0,
				Sniper:   1,
				Spy:      0,
			},
			name["Golden Terrestrial"]: {
				Scout:    1,
				Soldier:  3,
				Pyro:     2,
				Demoman:  4,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      3,
			},
			name["Invidia"]: {
				Scout:    3,
				Soldier:  2,
				Pyro:     1,
				Demoman:  1,
				Heavy:    1,
				Engineer: 0,
				Medic:    1,
				Sniper:   2,
				Spy:      2,
			},
			name["jumbuck"]: {
				Scout:    7,
				Soldier:  1,
				Pyro:     1,
				Demoman:  2,
				Heavy:    2,
				Engineer: 2,
				Medic:    1,
				Sniper:   1,
				Spy:      2,
			},
			name["Link"]: {
				Scout:    2,
				Soldier:  8,
				Pyro:     1,
				Demoman:  2,
				Heavy:    2,
				Engineer: 4,
				Medic:    3,
				Sniper:   7,
				Spy:      4,
			},
			name["Lochlore"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     2,
				Demoman:  5,
				Heavy:    1,
				Engineer: 1,
				Medic:    2,
				Sniper:   2,
				Spy:      0,
			},
			name["maz"]: {
				Scout:    1,
				Soldier:  6,
				Pyro:     6,
				Demoman:  3,
				Heavy:    2,
				Engineer: 2,
				Medic:    0,
				Sniper:   3,
				Spy:      4,
			},
			name["nomodick"]: {
				Scout:    4,
				Soldier:  1,
				Pyro:     1,
				Demoman:  5,
				Heavy:    1,
				Engineer: 1,
				Medic:    1,
				Sniper:   2,
				Spy:      1,
			},
			name["para"]: {
				Scout:    3,
				Soldier:  0,
				Pyro:     1,
				Demoman:  1,
				Heavy:    1,
				Engineer: 2,
				Medic:    0,
				Sniper:   2,
				Spy:      0,
			},
			name["Pride (Pyro Main)"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     4,
				Demoman:  2,
				Heavy:    5,
				Engineer: 1,
				Medic:    1,
				Sniper:   2,
				Spy:      1,
			},
			name["sentar"]: {
				Scout:    3,
				Soldier:  5,
				Pyro:     0,
				Demoman:  3,
				Heavy:    1,
				Engineer: 1,
				Medic:    2,
				Sniper:   1,
				Spy:      5,
			},
			name["Tiger"]: {
				Scout:    3,
				Soldier:  3,
				Pyro:     2,
				Demoman:  3,
				Heavy:    2,
				Engineer: 2,
				Medic:    1,
				Sniper:   1,
				Spy:      5,
			},
			name["Tunaaaaaa"]: {
				Scout:    4,
				Soldier:  4,
				Pyro:     2,
				Demoman:  1,
				Heavy:    1,
				Engineer: 2,
				Medic:    3,
				Sniper:   8,
				Spy:      3,
			},
			name["var"]: {
				Scout:    1,
				Soldier:  1,
				Pyro:     3,
				Demoman:  1,
				Heavy:    7,
				Engineer: 5,
				Medic:    0,
				Sniper:   2,
				Spy:      3,
			},
		},
		classDeaths: map[steamid.SID64]*MatchClassSums{
			name["avg Q enjoyer"]: {
				Scout:    2,
				Soldier:  3,
				Pyro:     0,
				Demoman:  0,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   2,
				Spy:      1,
			},
			name["Doctrine"]: {
				Scout:    1,
				Soldier:  2,
				Pyro:     1,
				Demoman:  2,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   3,
				Spy:      2,
			},
			name["El Sur"]: {
				Scout:    4,
				Soldier:  1,
				Pyro:     0,
				Demoman:  4,
				Heavy:    1,
				Engineer: 0,
				Medic:    1,
				Sniper:   0,
				Spy:      0,
			},
			name["ExCalibre"]: {
				Scout:    7,
				Soldier:  5,
				Pyro:     1,
				Demoman:  0,
				Heavy:    0,
				Engineer: 1,
				Medic:    0,
				Sniper:   4,
				Spy:      1,
			},
			name["freakyjoy1.ttv"]: {
				Scout:    4,
				Soldier:  5,
				Pyro:     0,
				Demoman:  0,
				Heavy:    1,
				Engineer: 3,
				Medic:    0,
				Sniper:   1,
				Spy:      0,
			},
			name["Golden Terrestrial"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     1,
				Demoman:  1,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      2,
			},
			name["Invidia"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     4,
				Demoman:  1,
				Heavy:    2,
				Engineer: 0,
				Medic:    0,
				Sniper:   2,
				Spy:      5,
			},
			name["jumbuck"]: {
				Scout:    2,
				Soldier:  0,
				Pyro:     0,
				Demoman:  0,
				Heavy:    4,
				Engineer: 1,
				Medic:    0,
				Sniper:   1,
				Spy:      1,
			},
			name["Link"]: {
				Scout:    0,
				Soldier:  2,
				Pyro:     3,
				Demoman:  0,
				Heavy:    6,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      0,
			},
			name["Lochlore"]: {
				Scout:    5,
				Soldier:  3,
				Pyro:     1,
				Demoman:  2,
				Heavy:    3,
				Engineer: 1,
				Medic:    1,
				Sniper:   1,
				Spy:      0,
			},
			name["maz"]: {
				Scout:    2,
				Soldier:  2,
				Pyro:     2,
				Demoman:  0,
				Heavy:    3,
				Engineer: 1,
				Medic:    0,
				Sniper:   1,
				Spy:      1,
			},
			name["nomodick"]: {
				Scout:    3,
				Soldier:  1,
				Pyro:     3,
				Demoman:  1,
				Heavy:    2,
				Engineer: 1,
				Medic:    3,
				Sniper:   2,
				Spy:      0,
			},
			name["para"]: {
				Scout:    7,
				Soldier:  3,
				Pyro:     3,
				Demoman:  1,
				Heavy:    3,
				Engineer: 6,
				Medic:    0,
				Sniper:   0,
				Spy:      0,
			},
			name["Pride (Pyro Main)"]: {
				Scout:    2,
				Soldier:  1,
				Pyro:     2,
				Demoman:  1,
				Heavy:    1,
				Engineer: 2,
				Medic:    0,
				Sniper:   4,
				Spy:      3,
			},
			name["sentar"]: {
				Scout:    0,
				Soldier:  1,
				Pyro:     0,
				Demoman:  0,
				Heavy:    1,
				Engineer: 1,
				Medic:    0,
				Sniper:   1,
				Spy:      1,
			},
			name["Tiger"]: {
				Scout:    1,
				Soldier:  1,
				Pyro:     0,
				Demoman:  3,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      2,
			},
			name["Tunaaaaaa"]: {
				Scout:    1,
				Soldier:  0,
				Pyro:     4,
				Demoman:  1,
				Heavy:    1,
				Engineer: 1,
				Medic:    0,
				Sniper:   1,
				Spy:      0,
			},
			name["var"]: {
				Scout:    1,
				Soldier:  4,
				Pyro:     1,
				Demoman:  2,
				Heavy:    1,
				Engineer: 0,
				Medic:    0,
				Sniper:   3,
				Spy:      2,
			},
			name["WitlessConnor"]: {
				Scout:    0,
				Soldier:  0,
				Pyro:     0,
				Demoman:  1,
				Heavy:    0,
				Engineer: 0,
				Medic:    0,
				Sniper:   0,
				Spy:      0,
			},
		},
	}
	return match, name
}
