// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file discord/v1/discord.proto (package discord.v1, edition 2023)
/* eslint-disable */

import { DiscordService } from "./discord_pb";

/**
 * @generated from rpc discord.v1.DiscordService.SeedRoleIDs
 */
export const seedRoleIDs = DiscordService.method.seedRoleIDs;
