// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file notification/v1/notification.proto (package notification.v1, edition 2023)
/* eslint-disable */

import { NotificationService } from "./notification_pb";

/**
 * @generated from rpc notification.v1.NotificationService.Notifications
 */
export const notifications = NotificationService.method.notifications;

/**
 * @generated from rpc notification.v1.NotificationService.MarkRead
 */
export const markRead = NotificationService.method.markRead;

/**
 * @generated from rpc notification.v1.NotificationService.MarkReadAll
 */
export const markReadAll = NotificationService.method.markReadAll;

/**
 * @generated from rpc notification.v1.NotificationService.DeleteAll
 */
export const deleteAll = NotificationService.method.deleteAll;

/**
 * @generated from rpc notification.v1.NotificationService.Delete
 */
export const delete$ = NotificationService.method.delete;
