// @generated by protoc-gen-connect-query v2.2.0 with parameter "target=ts"
// @generated from file patreon/v1/patreon.proto (package patreon.v1, edition 2023)
/* eslint-disable */

import { PatreonService } from "./patreon_pb";

/**
 * @generated from rpc patreon.v1.PatreonService.Campaigns
 */
export const campaigns = PatreonService.method.campaigns;
