INCLUDE_DIR := shell('dirname $(which spcomp64)') + "/include"

all: build

fmt:
    find scripting/ -not -path "./include/*" -iname gbans.inc -o -iname *.sp -type f -exec sp_format {} \;

build:
    spcomp64 scripting/gbans.sp -o plugins/gbans.smx -i{{ INCLUDE_DIR }} -i scripting/include -v2

copy:
    cp -rv scripting/* $(HOME)/projects/uncletopia/roles/sourcemod/files/addons/sourcemod/scripting/
