// @generated by protoc-gen-es v2.11.0 with parameter "target=ts"
// @generated from file ban/v1/appeal.proto (package ban.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../buf/validate/validate_pb";
import { file_filter } from "../../filter_pb";
import { file_google_protobuf_duration, file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file ban/v1/appeal.proto.
 */
export const file_ban_v1_appeal: GenFile = /*@__PURE__*/
  fileDesc("ChNiYW4vdjEvYXBwZWFsLnByb3RvEgZiYW4udjEiEQoPTWVzc2FnZXNSZXF1ZXN0IhIKEE1lc3NhZ2VzUmVzcG9uc2UyUAoNQXBwZWFsU2VydmljZRI/CghNZXNzYWdlcxIXLmJhbi52MS5NZXNzYWdlc1JlcXVlc3QaGC5iYW4udjEuTWVzc2FnZXNSZXNwb25zZSIAQo0BCgpjb20uYmFuLnYxQgtBcHBlYWxQcm90b1ABWjlnaXRodWIuY29tL2xlaWdobWFjZG9uYWxkL2diYW5zL2ludGVybmFsL3JwYy9iYW4vdjE7YmFudjGiAgNCWFiqAgZCYW4uVjHKAgZCYW5cVjHiAhJCYW5cVjFcR1BCTWV0YWRhdGHqAgdCYW46OlYxYghlZGl0aW9uc3DoBw", [file_buf_validate_validate, file_filter, file_google_protobuf_empty, file_google_protobuf_timestamp, file_google_protobuf_duration]);

/**
 * @generated from message ban.v1.MessagesRequest
 */
export type MessagesRequest = Message<"ban.v1.MessagesRequest"> & {
};

/**
 * Describes the message ban.v1.MessagesRequest.
 * Use `create(MessagesRequestSchema)` to create a new message.
 */
export const MessagesRequestSchema: GenMessage<MessagesRequest> = /*@__PURE__*/
  messageDesc(file_ban_v1_appeal, 0);

/**
 * @generated from message ban.v1.MessagesResponse
 */
export type MessagesResponse = Message<"ban.v1.MessagesResponse"> & {
};

/**
 * Describes the message ban.v1.MessagesResponse.
 * Use `create(MessagesResponseSchema)` to create a new message.
 */
export const MessagesResponseSchema: GenMessage<MessagesResponse> = /*@__PURE__*/
  messageDesc(file_ban_v1_appeal, 1);

/**
 * @generated from service ban.v1.AppealService
 */
export const AppealService: GenService<{
  /**
   * @generated from rpc ban.v1.AppealService.Messages
   */
  messages: {
    methodKind: "unary";
    input: typeof MessagesRequestSchema;
    output: typeof MessagesResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_ban_v1_appeal, 0);

