// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: servers/v1/servers.proto

package serversv1

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	_ "github.com/leighmacdonald/gbans/internal/rpc/ban/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LatLong       *LatLong               `protobuf:"bytes,1,opt,name=lat_long,json=latLong" json:"lat_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateRequest) Reset() {
	*x = StateRequest{}
	mi := &file_servers_v1_servers_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateRequest) ProtoMessage() {}

func (x *StateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateRequest.ProtoReflect.Descriptor instead.
func (*StateRequest) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{0}
}

func (x *StateRequest) GetLatLong() *LatLong {
	if x != nil {
		return x.LatLong
	}
	return nil
}

type SafeServer struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *int32                 `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	Host          *string                `protobuf:"bytes,2,opt,name=host" json:"host,omitempty"`
	Port          *uint32                `protobuf:"varint,3,opt,name=port" json:"port,omitempty"`
	Ip            *string                `protobuf:"bytes,4,opt,name=ip" json:"ip,omitempty"`
	Name          *string                `protobuf:"bytes,5,opt,name=name" json:"name,omitempty"`
	NameShort     *string                `protobuf:"bytes,6,opt,name=name_short,json=nameShort" json:"name_short,omitempty"`
	Region        *string                `protobuf:"bytes,7,opt,name=region" json:"region,omitempty"`
	Cc            *string                `protobuf:"bytes,8,opt,name=cc" json:"cc,omitempty"`
	Players       *int32                 `protobuf:"varint,9,opt,name=players" json:"players,omitempty"`
	MaxPlayers    *int32                 `protobuf:"varint,10,opt,name=max_players,json=maxPlayers" json:"max_players,omitempty"`
	Bot           *int32                 `protobuf:"varint,11,opt,name=bot" json:"bot,omitempty"`
	Map           *string                `protobuf:"bytes,12,opt,name=map" json:"map,omitempty"`
	GameTypes     []string               `protobuf:"bytes,13,rep,name=game_types,json=gameTypes" json:"game_types,omitempty"`
	Latitude      *float32               `protobuf:"fixed32,14,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     *float32               `protobuf:"fixed32,15,opt,name=longitude" json:"longitude,omitempty"`
	Distance      *float32               `protobuf:"fixed32,16,opt,name=distance" json:"distance,omitempty"`
	Humans        *int32                 `protobuf:"varint,17,opt,name=humans" json:"humans,omitempty"`
	Tags          []string               `protobuf:"bytes,18,rep,name=tags" json:"tags,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SafeServer) Reset() {
	*x = SafeServer{}
	mi := &file_servers_v1_servers_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SafeServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SafeServer) ProtoMessage() {}

func (x *SafeServer) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SafeServer.ProtoReflect.Descriptor instead.
func (*SafeServer) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{1}
}

func (x *SafeServer) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *SafeServer) GetHost() string {
	if x != nil && x.Host != nil {
		return *x.Host
	}
	return ""
}

func (x *SafeServer) GetPort() uint32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *SafeServer) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

func (x *SafeServer) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SafeServer) GetNameShort() string {
	if x != nil && x.NameShort != nil {
		return *x.NameShort
	}
	return ""
}

func (x *SafeServer) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *SafeServer) GetCc() string {
	if x != nil && x.Cc != nil {
		return *x.Cc
	}
	return ""
}

func (x *SafeServer) GetPlayers() int32 {
	if x != nil && x.Players != nil {
		return *x.Players
	}
	return 0
}

func (x *SafeServer) GetMaxPlayers() int32 {
	if x != nil && x.MaxPlayers != nil {
		return *x.MaxPlayers
	}
	return 0
}

func (x *SafeServer) GetBot() int32 {
	if x != nil && x.Bot != nil {
		return *x.Bot
	}
	return 0
}

func (x *SafeServer) GetMap() string {
	if x != nil && x.Map != nil {
		return *x.Map
	}
	return ""
}

func (x *SafeServer) GetGameTypes() []string {
	if x != nil {
		return x.GameTypes
	}
	return nil
}

func (x *SafeServer) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *SafeServer) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *SafeServer) GetDistance() float32 {
	if x != nil && x.Distance != nil {
		return *x.Distance
	}
	return 0
}

func (x *SafeServer) GetHumans() int32 {
	if x != nil && x.Humans != nil {
		return *x.Humans
	}
	return 0
}

func (x *SafeServer) GetTags() []string {
	if x != nil {
		return x.Tags
	}
	return nil
}

type LatLong struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Latitude      *float32               `protobuf:"fixed32,1,opt,name=latitude" json:"latitude,omitempty"`
	Longitude     *float32               `protobuf:"fixed32,2,opt,name=longitude" json:"longitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LatLong) Reset() {
	*x = LatLong{}
	mi := &file_servers_v1_servers_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LatLong) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LatLong) ProtoMessage() {}

func (x *LatLong) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LatLong.ProtoReflect.Descriptor instead.
func (*LatLong) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{2}
}

func (x *LatLong) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *LatLong) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

type Server struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	ServerId           *int32                 `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	ShortName          *string                `protobuf:"bytes,2,opt,name=short_name,json=shortName" json:"short_name,omitempty"`
	Name               *string                `protobuf:"bytes,3,opt,name=name" json:"name,omitempty"`
	Address            *string                `protobuf:"bytes,4,opt,name=address" json:"address,omitempty"`
	AddressInternal    *string                `protobuf:"bytes,5,opt,name=address_internal,json=addressInternal" json:"address_internal,omitempty"`
	SdrEnabled         *bool                  `protobuf:"varint,6,opt,name=sdr_enabled,json=sdrEnabled" json:"sdr_enabled,omitempty"`
	Port               *int32                 `protobuf:"varint,7,opt,name=port" json:"port,omitempty"`
	Rcon               *string                `protobuf:"bytes,8,opt,name=rcon" json:"rcon,omitempty"`
	Password           *string                `protobuf:"bytes,9,opt,name=password" json:"password,omitempty"`
	IsEnabled          *bool                  `protobuf:"varint,10,opt,name=is_enabled,json=isEnabled" json:"is_enabled,omitempty"`
	Deleted            *bool                  `protobuf:"varint,11,opt,name=deleted" json:"deleted,omitempty"`
	Region             *string                `protobuf:"bytes,12,opt,name=region" json:"region,omitempty"`
	Cc                 *string                `protobuf:"bytes,13,opt,name=cc" json:"cc,omitempty"`
	Latitude           *float32               `protobuf:"fixed32,14,opt,name=latitude" json:"latitude,omitempty"`
	Longitude          *float32               `protobuf:"fixed32,15,opt,name=longitude" json:"longitude,omitempty"`
	LogSecret          *int32                 `protobuf:"varint,16,opt,name=log_secret,json=logSecret" json:"log_secret,omitempty"`
	EnableStats        *bool                  `protobuf:"varint,17,opt,name=enable_stats,json=enableStats" json:"enable_stats,omitempty"`
	TokenCreatedOn     *timestamppb.Timestamp `protobuf:"bytes,18,opt,name=token_created_on,json=tokenCreatedOn" json:"token_created_on,omitempty"`
	CreatedOn          *timestamppb.Timestamp `protobuf:"bytes,19,opt,name=created_on,json=createdOn" json:"created_on,omitempty"`
	UpdatedOn          *timestamppb.Timestamp `protobuf:"bytes,20,opt,name=updated_on,json=updatedOn" json:"updated_on,omitempty"`
	DiscordSeedRoleIds []string               `protobuf:"bytes,21,rep,name=discord_seed_role_ids,json=discordSeedRoleIds" json:"discord_seed_role_ids,omitempty"`
	Ip                 *string                `protobuf:"bytes,22,opt,name=ip" json:"ip,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Server) Reset() {
	*x = Server{}
	mi := &file_servers_v1_servers_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Server) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Server) ProtoMessage() {}

func (x *Server) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Server.ProtoReflect.Descriptor instead.
func (*Server) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{3}
}

func (x *Server) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *Server) GetShortName() string {
	if x != nil && x.ShortName != nil {
		return *x.ShortName
	}
	return ""
}

func (x *Server) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Server) GetAddress() string {
	if x != nil && x.Address != nil {
		return *x.Address
	}
	return ""
}

func (x *Server) GetAddressInternal() string {
	if x != nil && x.AddressInternal != nil {
		return *x.AddressInternal
	}
	return ""
}

func (x *Server) GetSdrEnabled() bool {
	if x != nil && x.SdrEnabled != nil {
		return *x.SdrEnabled
	}
	return false
}

func (x *Server) GetPort() int32 {
	if x != nil && x.Port != nil {
		return *x.Port
	}
	return 0
}

func (x *Server) GetRcon() string {
	if x != nil && x.Rcon != nil {
		return *x.Rcon
	}
	return ""
}

func (x *Server) GetPassword() string {
	if x != nil && x.Password != nil {
		return *x.Password
	}
	return ""
}

func (x *Server) GetIsEnabled() bool {
	if x != nil && x.IsEnabled != nil {
		return *x.IsEnabled
	}
	return false
}

func (x *Server) GetDeleted() bool {
	if x != nil && x.Deleted != nil {
		return *x.Deleted
	}
	return false
}

func (x *Server) GetRegion() string {
	if x != nil && x.Region != nil {
		return *x.Region
	}
	return ""
}

func (x *Server) GetCc() string {
	if x != nil && x.Cc != nil {
		return *x.Cc
	}
	return ""
}

func (x *Server) GetLatitude() float32 {
	if x != nil && x.Latitude != nil {
		return *x.Latitude
	}
	return 0
}

func (x *Server) GetLongitude() float32 {
	if x != nil && x.Longitude != nil {
		return *x.Longitude
	}
	return 0
}

func (x *Server) GetLogSecret() int32 {
	if x != nil && x.LogSecret != nil {
		return *x.LogSecret
	}
	return 0
}

func (x *Server) GetEnableStats() bool {
	if x != nil && x.EnableStats != nil {
		return *x.EnableStats
	}
	return false
}

func (x *Server) GetTokenCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.TokenCreatedOn
	}
	return nil
}

func (x *Server) GetCreatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedOn
	}
	return nil
}

func (x *Server) GetUpdatedOn() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedOn
	}
	return nil
}

func (x *Server) GetDiscordSeedRoleIds() []string {
	if x != nil {
		return x.DiscordSeedRoleIds
	}
	return nil
}

func (x *Server) GetIp() string {
	if x != nil && x.Ip != nil {
		return *x.Ip
	}
	return ""
}

type StateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*SafeServer          `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	LatLong       *LatLong               `protobuf:"bytes,2,opt,name=lat_long,json=latLong" json:"lat_long,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StateResponse) Reset() {
	*x = StateResponse{}
	mi := &file_servers_v1_servers_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StateResponse) ProtoMessage() {}

func (x *StateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StateResponse.ProtoReflect.Descriptor instead.
func (*StateResponse) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{4}
}

func (x *StateResponse) GetServers() []*SafeServer {
	if x != nil {
		return x.Servers
	}
	return nil
}

func (x *StateResponse) GetLatLong() *LatLong {
	if x != nil {
		return x.LatLong
	}
	return nil
}

type ServerInfoSafe struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ServerNameLong *string                `protobuf:"bytes,1,opt,name=server_name_long,json=serverNameLong" json:"server_name_long,omitempty"`
	ServerName     *string                `protobuf:"bytes,2,opt,name=server_name,json=serverName" json:"server_name,omitempty"`
	ServerId       *int32                 `protobuf:"varint,3,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	Colour         *string                `protobuf:"bytes,4,opt,name=colour" json:"colour,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ServerInfoSafe) Reset() {
	*x = ServerInfoSafe{}
	mi := &file_servers_v1_servers_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerInfoSafe) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerInfoSafe) ProtoMessage() {}

func (x *ServerInfoSafe) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerInfoSafe.ProtoReflect.Descriptor instead.
func (*ServerInfoSafe) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{5}
}

func (x *ServerInfoSafe) GetServerNameLong() string {
	if x != nil && x.ServerNameLong != nil {
		return *x.ServerNameLong
	}
	return ""
}

func (x *ServerInfoSafe) GetServerName() string {
	if x != nil && x.ServerName != nil {
		return *x.ServerName
	}
	return ""
}

func (x *ServerInfoSafe) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

func (x *ServerInfoSafe) GetColour() string {
	if x != nil && x.Colour != nil {
		return *x.Colour
	}
	return ""
}

type ServersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*ServerInfoSafe      `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersResponse) Reset() {
	*x = ServersResponse{}
	mi := &file_servers_v1_servers_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersResponse) ProtoMessage() {}

func (x *ServersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersResponse.ProtoReflect.Descriptor instead.
func (*ServersResponse) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{6}
}

func (x *ServersResponse) GetServers() []*ServerInfoSafe {
	if x != nil {
		return x.Servers
	}
	return nil
}

type EditServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditServerRequest) Reset() {
	*x = EditServerRequest{}
	mi := &file_servers_v1_servers_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditServerRequest) ProtoMessage() {}

func (x *EditServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditServerRequest.ProtoReflect.Descriptor instead.
func (*EditServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{7}
}

func (x *EditServerRequest) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type EditServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Server        *Server                `protobuf:"bytes,1,opt,name=server" json:"server,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EditServerResponse) Reset() {
	*x = EditServerResponse{}
	mi := &file_servers_v1_servers_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EditServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EditServerResponse) ProtoMessage() {}

func (x *EditServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EditServerResponse.ProtoReflect.Descriptor instead.
func (*EditServerResponse) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{8}
}

func (x *EditServerResponse) GetServer() *Server {
	if x != nil {
		return x.Server
	}
	return nil
}

type DeleteServerRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServerId      *int32                 `protobuf:"varint,1,opt,name=server_id,json=serverId" json:"server_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerRequest) Reset() {
	*x = DeleteServerRequest{}
	mi := &file_servers_v1_servers_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerRequest) ProtoMessage() {}

func (x *DeleteServerRequest) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerRequest.ProtoReflect.Descriptor instead.
func (*DeleteServerRequest) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteServerRequest) GetServerId() int32 {
	if x != nil && x.ServerId != nil {
		return *x.ServerId
	}
	return 0
}

type DeleteServerResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteServerResponse) Reset() {
	*x = DeleteServerResponse{}
	mi := &file_servers_v1_servers_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteServerResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteServerResponse) ProtoMessage() {}

func (x *DeleteServerResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteServerResponse.ProtoReflect.Descriptor instead.
func (*DeleteServerResponse) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{10}
}

type ServersAdminResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Servers       []*Server              `protobuf:"bytes,1,rep,name=servers" json:"servers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServersAdminResponse) Reset() {
	*x = ServersAdminResponse{}
	mi := &file_servers_v1_servers_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServersAdminResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServersAdminResponse) ProtoMessage() {}

func (x *ServersAdminResponse) ProtoReflect() protoreflect.Message {
	mi := &file_servers_v1_servers_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServersAdminResponse.ProtoReflect.Descriptor instead.
func (*ServersAdminResponse) Descriptor() ([]byte, []int) {
	return file_servers_v1_servers_proto_rawDescGZIP(), []int{11}
}

func (x *ServersAdminResponse) GetServers() []*Server {
	if x != nil {
		return x.Servers
	}
	return nil
}

var File_servers_v1_servers_proto protoreflect.FileDescriptor

const file_servers_v1_servers_proto_rawDesc = "" +
	"\n" +
	"\x18servers/v1/servers.proto\x12\n" +
	"servers.v1\x1a\x10ban/v1/ban.proto\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\">\n" +
	"\fStateRequest\x12.\n" +
	"\blat_long\x18\x01 \x01(\v2\x13.servers.v1.LatLongR\alatLong\"\xd7\x03\n" +
	"\n" +
	"SafeServer\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1f\n" +
	"\x04host\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\xa8\x01\x01R\x04host\x12 \n" +
	"\x04port\x18\x03 \x01(\rB\f\xbaH\t\xc8\x01\x01*\x04\x18\xff\xff\x03R\x04port\x12\x0e\n" +
	"\x02ip\x18\x04 \x01(\tR\x02ip\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"name_short\x18\x06 \x01(\tR\tnameShort\x12\x16\n" +
	"\x06region\x18\a \x01(\tR\x06region\x12\x0e\n" +
	"\x02cc\x18\b \x01(\tR\x02cc\x12\x18\n" +
	"\aplayers\x18\t \x01(\x05R\aplayers\x12\x1f\n" +
	"\vmax_players\x18\n" +
	" \x01(\x05R\n" +
	"maxPlayers\x12\x10\n" +
	"\x03bot\x18\v \x01(\x05R\x03bot\x12\x10\n" +
	"\x03map\x18\f \x01(\tR\x03map\x12\x1d\n" +
	"\n" +
	"game_types\x18\r \x03(\tR\tgameTypes\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x02R\tlongitude\x12\x1a\n" +
	"\bdistance\x18\x10 \x01(\x02R\bdistance\x12\x16\n" +
	"\x06humans\x18\x11 \x01(\x05R\x06humans\x12\x12\n" +
	"\x04tags\x18\x12 \x03(\tR\x04tags\"e\n" +
	"\aLatLong\x12+\n" +
	"\blatitude\x18\x01 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x00\xb4B-\x00\x00\xb4\xc2R\blatitude\x12-\n" +
	"\tlongitude\x18\x02 \x01(\x02B\x0f\xbaH\f\n" +
	"\n" +
	"\x1d\x00\x004C-\x00\x004\xc3R\tlongitude\"\xde\x05\n" +
	"\x06Server\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\x12\x1d\n" +
	"\n" +
	"short_name\x18\x02 \x01(\tR\tshortName\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x18\n" +
	"\aaddress\x18\x04 \x01(\tR\aaddress\x12)\n" +
	"\x10address_internal\x18\x05 \x01(\tR\x0faddressInternal\x12\x1f\n" +
	"\vsdr_enabled\x18\x06 \x01(\bR\n" +
	"sdrEnabled\x12\x12\n" +
	"\x04port\x18\a \x01(\x05R\x04port\x12\x12\n" +
	"\x04rcon\x18\b \x01(\tR\x04rcon\x12\x1a\n" +
	"\bpassword\x18\t \x01(\tR\bpassword\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\n" +
	" \x01(\bR\tisEnabled\x12\x18\n" +
	"\adeleted\x18\v \x01(\bR\adeleted\x12\x16\n" +
	"\x06region\x18\f \x01(\tR\x06region\x12\x0e\n" +
	"\x02cc\x18\r \x01(\tR\x02cc\x12\x1a\n" +
	"\blatitude\x18\x0e \x01(\x02R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x0f \x01(\x02R\tlongitude\x12\x1d\n" +
	"\n" +
	"log_secret\x18\x10 \x01(\x05R\tlogSecret\x12!\n" +
	"\fenable_stats\x18\x11 \x01(\bR\venableStats\x12D\n" +
	"\x10token_created_on\x18\x12 \x01(\v2\x1a.google.protobuf.TimestampR\x0etokenCreatedOn\x129\n" +
	"\n" +
	"created_on\x18\x13 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedOn\x129\n" +
	"\n" +
	"updated_on\x18\x14 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedOn\x121\n" +
	"\x15discord_seed_role_ids\x18\x15 \x03(\tR\x12discordSeedRoleIds\x12\x0e\n" +
	"\x02ip\x18\x16 \x01(\tR\x02ip\"q\n" +
	"\rStateResponse\x120\n" +
	"\aservers\x18\x01 \x03(\v2\x16.servers.v1.SafeServerR\aservers\x12.\n" +
	"\blat_long\x18\x02 \x01(\v2\x13.servers.v1.LatLongR\alatLong\"\x90\x01\n" +
	"\x0eServerInfoSafe\x12(\n" +
	"\x10server_name_long\x18\x01 \x01(\tR\x0eserverNameLong\x12\x1f\n" +
	"\vserver_name\x18\x02 \x01(\tR\n" +
	"serverName\x12\x1b\n" +
	"\tserver_id\x18\x03 \x01(\x05R\bserverId\x12\x16\n" +
	"\x06colour\x18\x04 \x01(\tR\x06colour\"G\n" +
	"\x0fServersResponse\x124\n" +
	"\aservers\x18\x01 \x03(\v2\x1a.servers.v1.ServerInfoSafeR\aservers\"?\n" +
	"\x11EditServerRequest\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.servers.v1.ServerR\x06server\"@\n" +
	"\x12EditServerResponse\x12*\n" +
	"\x06server\x18\x01 \x01(\v2\x12.servers.v1.ServerR\x06server\"2\n" +
	"\x13DeleteServerRequest\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\x05R\bserverId\"\x16\n" +
	"\x14DeleteServerResponse\"D\n" +
	"\x14ServersAdminResponse\x12,\n" +
	"\aservers\x18\x01 \x03(\v2\x12.servers.v1.ServerR\aservers2\xee\x02\n" +
	"\x0eServersService\x12<\n" +
	"\x05State\x12\x18.servers.v1.StateRequest\x1a\x19.servers.v1.StateResponse\x12>\n" +
	"\aServers\x12\x16.google.protobuf.Empty\x1a\x1b.servers.v1.ServersResponse\x12K\n" +
	"\n" +
	"EditServer\x12\x1d.servers.v1.EditServerRequest\x1a\x1e.servers.v1.EditServerResponse\x12G\n" +
	"\fDeleteServer\x12\x1f.servers.v1.DeleteServerRequest\x1a\x16.google.protobuf.Empty\x12H\n" +
	"\fServersAdmin\x12\x16.google.protobuf.Empty\x1a .servers.v1.ServersAdminResponseB\xaa\x01\n" +
	"\x0ecom.servers.v1B\fServersProtoP\x01ZAgithub.com/leighmacdonald/gbans/internal/rpc/servers/v1;serversv1\xa2\x02\x03SXX\xaa\x02\n" +
	"Servers.V1\xca\x02\n" +
	"Servers\\V1\xe2\x02\x16Servers\\V1\\GPBMetadata\xea\x02\vServers::V1b\beditionsp\xe8\a"

var (
	file_servers_v1_servers_proto_rawDescOnce sync.Once
	file_servers_v1_servers_proto_rawDescData []byte
)

func file_servers_v1_servers_proto_rawDescGZIP() []byte {
	file_servers_v1_servers_proto_rawDescOnce.Do(func() {
		file_servers_v1_servers_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_servers_v1_servers_proto_rawDesc), len(file_servers_v1_servers_proto_rawDesc)))
	})
	return file_servers_v1_servers_proto_rawDescData
}

var file_servers_v1_servers_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_servers_v1_servers_proto_goTypes = []any{
	(*StateRequest)(nil),          // 0: servers.v1.StateRequest
	(*SafeServer)(nil),            // 1: servers.v1.SafeServer
	(*LatLong)(nil),               // 2: servers.v1.LatLong
	(*Server)(nil),                // 3: servers.v1.Server
	(*StateResponse)(nil),         // 4: servers.v1.StateResponse
	(*ServerInfoSafe)(nil),        // 5: servers.v1.ServerInfoSafe
	(*ServersResponse)(nil),       // 6: servers.v1.ServersResponse
	(*EditServerRequest)(nil),     // 7: servers.v1.EditServerRequest
	(*EditServerResponse)(nil),    // 8: servers.v1.EditServerResponse
	(*DeleteServerRequest)(nil),   // 9: servers.v1.DeleteServerRequest
	(*DeleteServerResponse)(nil),  // 10: servers.v1.DeleteServerResponse
	(*ServersAdminResponse)(nil),  // 11: servers.v1.ServersAdminResponse
	(*timestamppb.Timestamp)(nil), // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),         // 13: google.protobuf.Empty
}
var file_servers_v1_servers_proto_depIdxs = []int32{
	2,  // 0: servers.v1.StateRequest.lat_long:type_name -> servers.v1.LatLong
	12, // 1: servers.v1.Server.token_created_on:type_name -> google.protobuf.Timestamp
	12, // 2: servers.v1.Server.created_on:type_name -> google.protobuf.Timestamp
	12, // 3: servers.v1.Server.updated_on:type_name -> google.protobuf.Timestamp
	1,  // 4: servers.v1.StateResponse.servers:type_name -> servers.v1.SafeServer
	2,  // 5: servers.v1.StateResponse.lat_long:type_name -> servers.v1.LatLong
	5,  // 6: servers.v1.ServersResponse.servers:type_name -> servers.v1.ServerInfoSafe
	3,  // 7: servers.v1.EditServerRequest.server:type_name -> servers.v1.Server
	3,  // 8: servers.v1.EditServerResponse.server:type_name -> servers.v1.Server
	3,  // 9: servers.v1.ServersAdminResponse.servers:type_name -> servers.v1.Server
	0,  // 10: servers.v1.ServersService.State:input_type -> servers.v1.StateRequest
	13, // 11: servers.v1.ServersService.Servers:input_type -> google.protobuf.Empty
	7,  // 12: servers.v1.ServersService.EditServer:input_type -> servers.v1.EditServerRequest
	9,  // 13: servers.v1.ServersService.DeleteServer:input_type -> servers.v1.DeleteServerRequest
	13, // 14: servers.v1.ServersService.ServersAdmin:input_type -> google.protobuf.Empty
	4,  // 15: servers.v1.ServersService.State:output_type -> servers.v1.StateResponse
	6,  // 16: servers.v1.ServersService.Servers:output_type -> servers.v1.ServersResponse
	8,  // 17: servers.v1.ServersService.EditServer:output_type -> servers.v1.EditServerResponse
	13, // 18: servers.v1.ServersService.DeleteServer:output_type -> google.protobuf.Empty
	11, // 19: servers.v1.ServersService.ServersAdmin:output_type -> servers.v1.ServersAdminResponse
	15, // [15:20] is the sub-list for method output_type
	10, // [10:15] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_servers_v1_servers_proto_init() }
func file_servers_v1_servers_proto_init() {
	if File_servers_v1_servers_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_servers_v1_servers_proto_rawDesc), len(file_servers_v1_servers_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_servers_v1_servers_proto_goTypes,
		DependencyIndexes: file_servers_v1_servers_proto_depIdxs,
		MessageInfos:      file_servers_v1_servers_proto_msgTypes,
	}.Build()
	File_servers_v1_servers_proto = out.File
	file_servers_v1_servers_proto_goTypes = nil
	file_servers_v1_servers_proto_depIdxs = nil
}
