package domain

import "errors"

var (
	ErrRowResults          = errors.New("resulting rows contain error")
	ErrTxStart             = errors.New("could not start transaction")
	ErrTxCommit            = errors.New("failed to commit tx changes")
	ErrTxRollback          = errors.New("could not rollback transaction")
	ErrPoolFailed          = errors.New("could not create store pool")
	ErrUUIDGen             = errors.New("could not generate uuid")
	ErrCreateQuery         = errors.New("failed to generate query")
	ErrCountQuery          = errors.New("failed to get count result")
	ErrTooShort            = errors.New("value too short")
	ErrInvalidParameter    = errors.New("invalid parameter format")
	ErrPermissionDenied    = errors.New("permission denied")
	ErrBadRequest          = errors.New("invalid request")
	ErrInternal            = errors.New("internal server error")
	ErrParamKeyMissing     = errors.New("param key not found")
	ErrParamParse          = errors.New("failed to parse param value")
	ErrParamInvalid        = errors.New("param value invalid")
	ErrScanResult          = errors.New("failed to scan result")
	ErrUnknownServerID     = errors.New("unknown server id")
	ErrSelfReport          = errors.New("cannot self report")
	ErrReportExists        = errors.New("cannot create report while existing report open")
	ErrAssetCreateFailed   = errors.New("failed to create asset")
	ErrAssetPut            = errors.New("unable to create asset on remote store")
	ErrAssetSave           = errors.New("failed to save asset metadata")
	ErrInvalidFormat       = errors.New("invalid format")
	ErrDuplicateMediaName  = errors.New("duplicate media name")
	ErrSaveMedia           = errors.New("could not save media")
	ErrFetchMedia          = errors.New("failed to fetch media asset")
	ErrEmptyToken          = errors.New("invalid access token decoded")
	ErrContestLoadEntries  = errors.New("failed to load existing contest entries")
	ErrContestMaxEntries   = errors.New("entries count exceed max_submission limits")
	ErrEntryCreate         = errors.New("failed to create new contest entry")
	ErrEntrySave           = errors.New("failed to save contest entry")
	ErrThreadLocked        = errors.New("thread is locked")
	ErrCreateToken         = errors.New("failed to create new access token")
	ErrRefreshToken        = errors.New("failed to create new refresh token")
	ErrClientIP            = errors.New("failed to parse IP")
	ErrSaveToken           = errors.New("failed to save new createRefresh token")
	ErrSignToken           = errors.New("failed create signed string")
	ErrSignJWT             = errors.New("failed create signed JWT string")
	ErrAuthHeader          = errors.New("failed to bind auth header")
	ErrMalformedAuthHeader = errors.New("invalid auth header format")
	ErrCookieKeyMissing    = errors.New("cookie key missing, cannot generate token")
	ErrInvalidContestID    = errors.New("invalid contest id")
	ErrInvalidDescription  = errors.New("invalid description, cannot be empty")
	ErrGenerateUUID        = errors.New("failed to generate uuid")
	ErrTitleEmpty          = errors.New("title cannot be empty")
	ErrDescriptionEmpty    = errors.New("description cannot be empty")
	ErrEndDateBefore       = errors.New("end date comes before start date")
	ErrInvalidThread       = errors.New("invalid thread id")
)
